### ISSUE TITLE
unable to start sly after update

### ISSUE THREAD

**Issue by mfiano** [joaotavora/sly#100]
I updated to the latest MELPA sly release (sly-20160620.632) and when I run (unless (sly-connected-p) (sly)) I now get the following error:

```
Debugger entered--Lisp error: (file-error "Searching for program" "no such file or directory" "lisp")
  start-process("inferior-lisp" #<buffer *sly-started inferior-lisp for lisp*> "lisp")
  apply(start-process "inferior-lisp" #<buffer *sly-started inferior-lisp for lisp*> "lisp" nil)
  start-file-process("inferior-lisp" #<buffer *sly-started inferior-lisp for lisp*> "lisp")
  apply(start-file-process "inferior-lisp" #<buffer *sly-started inferior-lisp for lisp*> "lisp" nil)
  comint-exec-1("inferior-lisp" #<buffer *sly-started inferior-lisp for lisp*> "lisp" nil)
  comint-exec(#<buffer *sly-started inferior-lisp for lisp*> "inferior-lisp" "lisp" nil nil)
  sly-start-lisp("lisp" nil nil nil "*sly-started inferior-lisp for lisp*")
  sly-maybe-start-lisp("lisp" nil nil nil "*sly-started inferior-lisp for lisp*")
  sly-start(:program "lisp")
  apply(sly-start (:program "lisp"))
  sly-start*((:program "lisp"))
  sly()
  (if (sly-connected-p) nil (sly))
  (unless (sly-connected-p) (sly))
  eval((unless (sly-connected-p) (sly)) nil)
  eval-expression((unless (sly-connected-p) (sly)) nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

**Comment by joaotavora** [comment]
Obvious question: do you have a "lisp" executable somewhere in your PATH?

Another question, does it work if you start it with `M-x sly`

**Comment by axionix** [comment]
I've never had a 'lisp' executable. and yes, it does work with M-x sly

**Comment by joaotavora** [comment]
So I suppose `M-x sly` asks you to if you want to try some automatically guessed `sbcl` executable then?

**Comment by axionix** [comment]
M-x sly doesn't ask and automatically starts sbcl. I have this in my config:

```
(setq sly-lisp-implementations
          `((sbcl ("sbcl" "--core" ,(expand-file-name "~/.sbcl/basic.core"))
                  :env ("SBCL_HOME=/usr/lib/sbcl"))))
```

**Comment by joaotavora** [comment]
Ah OK, that makes sense too. If you hadn't, then `M-x sly` would have done as I said. But never mind this.

What happened is I changed the behaviour os the function `sly`. When called interactively, it works as before: it looks at `sly-lisp-implementations`, then `inferior-lisp-program` then guesses. Also interactively it behaves differently when prefixed with a `C-u`. See its documentation for more details.

But you are calling it programatically, using `M-x eval-expression` or `M-:` (might I ask why BTW?).  In those cases, it errors out when no suitable arguments have been given, as a good function should do. 

So you can either use `M-: (unless (sly-connected-p) (sly 'sbcl))` or `M-: (unless (sly-connected-p) (sly nil nil t))` or `M-: (unless (sly-connected-p) (call-interactively 'sly))` start using `M-x sly` or create your `axionix/maybe-start-sly` command that checks for `sly-connected-p`:

```lisp
(defun axionix/maybe-start-sly ()
  (interactive)
  (sly nil nil t))
```

I think this last method is The Right Thing, what do you think?

**Comment by axionix** [comment]
Ah. I was only using M-x eval-expression to debug the problem that stemmed from this failing:

```
(add-hook 'sly-mode-hook (lambda () (unless (sly-connected-p) (sly))))
```

...which always worked in the past. What do you suggest I change to fix the above snippet then?

**Comment by joaotavora** [comment]
I see, you want sly started when you visit some lisp file, right? So you should change it to 

```lisp
(add-hook 'sly-mode-hook 'axionix/maybe-start-sly)
```

Or some of the other alternatives. But perhaps I should byte the bullet and bring the old behaviour back, whereby programatically calling `sly` also does some guessing.

**Comment by axionix** [comment]
Yes that is what i want. I'll do what you suggested in the meantime. Thank you.

Could you reply/close this issue after the old behavior is back, if you do plan on doing that?

**Comment by joaotavora** [comment]
> Could you reply/close this issue after the old behavior is back, if you do plan on doing that?

Sure, that's what I always do :-)

**Comment by joaotavora** [comment]
Should be fixed, ping here when you get the chance to test it.

**Comment by mfiano** [comment]
Yes, it seems to be fixed. Thanks.
