### ISSUE TITLE
Weird interaction with Spinneret: intermittent line-wrapping behaviour

### ISSUE THREAD

**Issue by PuercoPop** [joaotavora/sly#113]
I'm reporting this issue here instead that on spinneret because this only happens on sly. It doesn't happen with Slime or in the bare REPL.

Basically evaluate the following code in the REPL multiple times and you'll see that the line breaks are at different places in repeated evaluations of the same code.

```lisp
(spinneret:with-html (:span.class1.class2.class3 (:a :href "#" "hello")))
```

![image](https://cloud.githubusercontent.com/assets/387111/23640953/b79d9a20-02be-11e7-8b8d-70900e4d7d74.png)

Any idea of what may be going wrong?

cc: @ruricolist

**Comment by ruricolist** [comment]
From the Spinneret side, I suspect that the state of the Lisp pretty printer is not getting reset between evaluations, and consequently wrapping because it does not realize the line has been broken.

**Comment by ruricolist** [comment]
Here's a minimal example of the problem with pretty-printing, with nothing to do with Spinneret:

```
(pprint-logical-block (*standard-output* nil)
  (pprint-newline :mandatory *standard-output*)
  (write-string "Hello" *standard-output*))
```

Evaluate repeatedly for a scrolling banner effect.

The problem does not take effect across REPLs. That is, all REPLs have the same problem, but each has its own state.

The problem only occurs with direct use of the pretty printer. Pretty printing of objects by the REPL itself behaves normally (starts at the left margin). 

Interestingly, using the pretty printer, then pretty-printing a long list, then using the printer again, does not reset the state of the margin.

```
;; New REPL.

CL-USER> (setq *print-right-margin* 40 *print-pretty* t)
T
CL-USER> (pprint-logical-block (*standard-output* nil)
             (pprint-newline :mandatory *standard-output*)
             (write-string "Hello" *standard-output*))

Hello
NIL
CL-USER> (pprint-logical-block (*standard-output* nil)
             (pprint-newline :mandatory *standard-output*)
             (write-string "Hello" *standard-output*))

     Hello
NIL

;; Note that the state is not reset by pretty-printing an object.

CL-USER> '(hello hello hello hello hello hello hello hello)
(HELLO HELLO HELLO HELLO HELLO HELLO
 HELLO HELLO)
CL-USER> (pprint-logical-block (*standard-output* nil)
             (pprint-newline :mandatory *standard-output*)
             (write-string "Hello" *standard-output*))

          Hello
NIL
CL-USER> 
```

**Comment by joaotavora** [comment]
Thansk a lot both of you for the detailed information. I'll take a look at this tomorrow asap!

**Comment by joaotavora** [comment]
I've not come much far, but I've noticed that `(terpri)` resets the state that you want to reset. The questions are:

* who is destructively modifying state
* what state is being modified
* why it isn't being reset

I don't have an answer to any of these questions yet...

**Comment by PuercoPop** [comment]
@joaotavora given my complete ignorance of Lisp's pretty printer I don't have the answer not any intuition either. Was hoping that because you were more familiar the mrepl code you'd have at least a vague idea of what could it be.

**Comment by joaotavora** [comment]
@PuercoPop it might be related to the opening of the dedicated output stream in `contrib/slynk-mrepl.lisp`. Some lines at the end mention the `:line` buffering type for socket streams, that only sbcl and cmucl support. I can't check right now, but I wonder if the problem happens in ccl, for example...

**Comment by PuercoPop** [comment]
#### Affected
- SBCL
- ECL

#### Unaffected
- CCL
- ABCL
- CLISP

**Comment by joaotavora** [comment]
Right. So after some lengthy analysis (I hadn't done this in a while, kinda rusty I guess) I found the culprit. The combination of SBCL's `:line` buffering style and a dedicated socket for REPL output is to blame.

It's probably a bug in SBCL: the `output-column` slot of the stream struct doesn't get updated when using  output functions from the pretty printer domain. After having a look at SBCL's `code/pprint.lisp` and `code/fdstream.lisp` I think the problem is there, but didn't get to the bottom of it.

So you setup SLIME to use these options it will probably behave similarly. It doesn't because, by default, it doesn't use `:line` buffering style nor the dedicated output socket.

SLY's defaults use these two options, but it's easy to change them from `~/.slynkrc`. (that is to say, it is now, after my latest commit)

I personally recommend keeping dedicated stream for local connects, so probably the easiest would be to add

```lisp
(setq slynk:*dedicated-output-stream-buffering* t)
```

To your `~/.slynkrc` or `~/.slynk.lisp` file.

**Comment by PuercoPop** [comment]
I'm unable to reproduce the issue in recent versions of Sly/Spinneret

**Comment by joaotavora** [comment]
> I'm unable to reproduce the issue in recent versions of Sly/Spinneret

More likely the bug has been fixed in a recent SBCL
