### ISSUE TITLE
Typo in Readme.md

### ISSUE THREAD

**Issue by gpadd** [joaotavora/sly#117]
There is a typo at line 64-65 in the README.md file,
Previously:
If you wish to byte-compile SLY yourself (not needed generally) you can do `make
compile contrib-compile` in the dir where you cloned SLY.
Should be:
If you wish to byte-compile SLY yourself (not needed generally) you can do `make
compile compile-contrib` in the dir where you cloned SLY.

**Comment by joaotavora** [comment]
Thanks
