### ISSUE TITLE
sly-mrepl-mode-map void

### ISSUE THREAD

**Issue by mfiano** [joaotavora/sly#120]
I'm not sure when this regression took place as I haven't updated sly in about 6 months, but a recent upgrade broke sly-mrepl-mode-map.

`Symbol’s value as variable is void: sly-mrepl-mode-map`

...unless I specifically load the sly-mrepl package in a "with-eval-after-load sly" form.

**Comment by joaotavora** [comment]
A recent upgrade to what exactly? SLY?

Anyway, a `define-key` to a package-specific map should either come after a `require` of that package or inside a `with-eval-after-load` block as you suggest. It's slightly more correct to use `with-eval-after-load sly-mrepl` though.

Does it work OK with that line?

I guess the load order before the upgrade was defining that map early and you got away with the crime.

**Comment by mfiano** [comment]
Ah, I was always do `(use-package sly :bind (sly-mrepl-mode-map ...)))` (I'm not sure if that syntax is correct being away from my config, but you get the point). It wasn't until last week that I upgraded sly and I had to move the bind out of sly's use-package form and do `(use-package sly-mrepl :after sly :bind ...)`

**Comment by joaotavora** [comment]
I had, until now, no idea what the semantics of the `:bind` clause in`use-package` is, I can only build upon core emacs stuff and `use-package` isn't core, though i admit its popular. 

On a tangent, don't you get curious about learning Emacs with just its bare bones and ditching those million little packages? It takes less time than you think and generally becomes more consistent.
