### ISSUE TITLE
Optionally allow xref target to reuse source window

### ISSUE THREAD

**Issue by mfiano** [joaotavora/sly#123]
Rather than reusing a random window, optionally allow `M-.` to create its target buffer in the same window that it was issued in. This is so I don't have to constantly restore the previous buffer manually, for when the buffers I have open are important not to change. This is a feature request that branched off of a bug fix in #121 

Note that `target` here refers to the source code buffer that is jumped to, not the ephemeral xref buffer.

**Comment by joaotavora** [comment]
Can you try the `123-sly-xref-popup-method` branch?

**Comment by mfiano** [comment]
@joaotavora Yay! This works beautifully.

**Comment by joaotavora** [comment]
It's just a prototype. But give it some testing. After some thought, I'm leaning on making the behaviour you request the default behaviour. The decision whether to use a new window (or frame, for that matter), should be taken by the used in the existing commands `sly-edit-definition-other-window` and `sly-edit-definition-other-frame`. So the customization variable is actually bloat.

**Comment by joaotavora** [comment]
When I say "it's just a prototype" means it might very well fail for some case and I don't know if I will include it in master.

**Comment by mfiano** [comment]
I have been testing it for about a half hour now without fail. I look forward to having it tracked by MELPA, should you reconsider though.

**Comment by joaotavora** [comment]
I like the approach in the branch `123-another-approach` better, and you probably will too, since your idea is now the default. It has much simpler code but I would like to see a bit of testing before I push it off to master.

**Comment by mfiano** [comment]
Sure thing. I will test it for a few days/weeks and report back my findings. I very much appreciate your fast responses/fixes to my issues, and your overall dedication to this project. That is the best feature of all, and why I have been recommending people try Sly for a couple years now.

**Comment by joaotavora** [comment]
I added some unit tests to give it a beating. Being more confident, I merged this onto master. 

Also, thanks for bringing this issue to my attention. The behaviour you suggest does make a lot more sense. I guess this had been an annoyance for so long (in SLIME and SLY) that I got used to it and thought it to be the correct behaviour, but it's not. One shouldn't mess with the user's window configuration if one can.

**Comment by mfiano** [comment]
@joaotavora Xach is trying out Sly this month, and his first day he did a little write up here: http://lispblog.xach.com/post/165078221528/september-of-sly

In it he says:

> Window management in sly-selector confuses me - expect REPL to replace current window, but it seems to go somewhere else every time

I'm wondering if this issue can be extended to that.

**Comment by joaotavora** [comment]
Thanks for sharing, that's pretty cool. I guess I don't follow many blogs... @xach's comments seem pretty reasonable, I'll ask him to open issues and see what I can do.

**Comment by joaotavora** [comment]
I wrote Zach an email. There's a one-line workaround with:

```lisp
(add-to-list 'display-buffer-alist `("*sly-mrepl" . (switch-to-buffer)))
```

But I guess I could add a `sly-mrepl-this-window` command
