### ISSUE TITLE
Back-references are not reset after restarting image

### ISSUE THREAD

**Issue by PuercoPop** [joaotavora/sly#127]
When reseting the image, through the `sly-mrepl-shortcut` (`,` -> restart image), the back-reference counter is not updated.

To reproduce, open SLY input some values, restart the image and type `#v`, you'll see the previous values are still counted even if unavailable.

**Comment by joaotavora** [comment]
Oh, good one. Wonder how to fix this...

**Comment by joaotavora** [comment]
Well, so are any REPL results, those are also invalid.

**Comment by joaotavora** [comment]
Can you try out the fix in 12cce5e?

**Comment by PuercoPop** [comment]
The fix works!

Btw, one thing that would help working with back-references is a pop-up similar to the one of [helm-swoop](https://github.com/ShingoFukuyama/helm-swoop)
