### ISSUE TITLE
Emacs stuck on Sly repl request

### ISSUE THREAD

**Issue by Zulu-Inuoe** [joaotavora/sly#132]
Hello,

I installed sly via package-install, and cleared my configuration of any and all references to SLIME.
I start sly, and it connects properly and brings up the repl. Attempting to evaluate anything at the repl will cause emacs to become unresponsive.
Killing the lisp process doesn't solve the issue. I'm force to kill emacs.

I've tried starting slynk separately to see if it would provide any more information, but to no avail.

If I try to interrupt the repl (before trying to evaluate anything) it will crash SBCL with nested errors:
```
13: ((LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD))
14: ((FLET #:WITHOUT-INTERRUPTS-BODY-1138 :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
15: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
16: ((FLET #:WITHOUT-INTERRUPTS-BODY-358 :IN SB-THREAD::CALL-WITH-MUTEX))
17: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {5C1FB4B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1003E5A663}>> NIL T NIL)
18: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1003E5A663}> NIL #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD) {1003E59BDB}> (#<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1003E5A663}> #<SB-THREAD:THREAD "slynk-indentation-cache-thread" RUNNING {1005DE8153}> #<SB-THREAD:THREAD "reader-thread" RUNNING {1005DE8003}> #<SB-THREAD:THREAD "control-thread" RUNNING {1005DE45B3}> #<SB-THREAD:THREAD "Slynk Sentinel" RUNNING {1005B52413}> #<SB-THREAD:THREAD "main thread" RUNNING {1002DBA9F3}>) NIL NIL NIL NIL)
19: ("foreign function: #x4338BC")
20: ("foreign function: #x403751")
21: ("foreign function: #x4501E0")
Help! ERROR-ERROR is 2 levels deep. Will try to reset the IO streams by calling STREAM-COLD-INIT-OR-RESET.
```
etc

My setup:
* Sly 20171011.809
* Emacs 25.0.90.3 AMD64
* SBCL 1.3.18 AMD64
* Windows 10 AMD64

**Comment by joaotavora** [comment]
Wilfredo Velázquez-Rodríguez <notifications@github.com> writes:

> Hello,
>
> I installed sly via package-install, and cleared my configuration of
> any and all references to SLIME.  I start sly, and it connects
> properly and brings up the repl. Attempting to evaluate anything at
> the repl will cause emacs to become unresponsive.

I suppose you're positive that you can't exit out of that freeze by
multiple presses of C-g, or ESC ESC ESC? Just checking (it's very
strange for an external process to freeze Emacs.)

> Killing the lisp process doesn't solve the issue. I'm force to kill
> emacs.

Can you "crash" SLY while having the *sly-events* buffer opened up in
some other Emacs window? This would allow you to get a glimpse of what
is happening.

> I've tried starting slynk separately to see if it would provide any more information, but to no avail.
>
> If I try to interrupt the repl (before trying to evaluate anything) it will crash SBCL with nested errors:
>
> 13: ((LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD))
> 14: ((FLET #:WITHOUT-INTERRUPTS-BODY-1138 :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
> 15: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
> 16: ((FLET #:WITHOUT-INTERRUPTS-BODY-358 :IN SB-THREAD::CALL-WITH-MUTEX))
> 17: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {5C1FB4B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1003E5A663}>> NIL T NIL)
> 18: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1003E5A663}> NIL #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD) {1003E59BDB}> (#<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1003E5A663}> #<SB-THREAD:THREAD "slynk-indentation-cache-thread" RUNNING {1005DE8153}> #<SB-THREAD:THREAD "reader-thread" RUNNING {1005DE8003}> #<SB-THREAD:THREAD "control-thread" RUNNING {1005DE45B3}> #<SB-THREAD:THREAD "Slynk Sentinel" RUNNING {1005B52413}> #<SB-THREAD:THREAD "main thread" RUNNING {1002DBA9F3}>) NIL NIL NIL NIL)
> 19: ("foreign function: #x4338BC")
> 20: ("foreign function: #x403751")
> 21: ("foreign function: #x4501E0")
> Help! ERROR-ERROR is 2 levels deep. Will try to reset the IO streams
> by calling STREAM-COLD-INIT-OR-RESET.

Where are you extracting this backtrace from. Emacs or a separate
terminal where you started sbcl? Can you also show the stack frames 1 to
12?

Besides clearing any and all references to SLIME (you shouldn't have
needed this though), do you have access to a shell?

If so, place yourself in the directory where package-install downloaded
SLY (it should be "/your-home/.emacs.d/elpa/sly-something") and type:

   $ /path/to/emacs.exe -Q -L . -l sly-autoloads.el --eval '(setq inferior-lisp-program "path/to/sbcl.exe")' -f sly

Otherwise, move your .emacs or other init files completely out of the
way and start Emacs again. Proceed to evaluate in the *scratch* buffer:

    (add-to-list 'load-path "path/to/sly")
    (require 'sly-autoloads)
    (setq inferior-lisp-program "path/to/sbcl.exe")

Then M-x sly

> My setup:
>
> * Sly 20171011.809
> * Emacs 25.0.90.3
>
I don't think there's much reason to be using what looks like old
pretest version of Emacs (other than it probably works fine :-)) But,
can you try with Emacs 25.1, 25.2 or 25.3?

> * SBCL 1.3.18

Is this a binary obtained from a particular place your did you compile
it on your own?

**Comment by Zulu-Inuoe** [comment]
I moved my .emacs.d folder and tested with a 'naked' emacs, and it worked. I'm sorry, I don't know why I didn't try that first.
So I bisected my init file and came up with this line being at fault:

`(setq-default comint-process-echoes 'on)`

The reason I have this turned on is becuase of the comments [here](https://www.gnu.org/software/emacs/manual/html_node/efaq-w32/Shell-echo.html). But since I hardly use the emacs shell, so I'm fine leaving it off.

Now, interestingly this only seems to affect sly on the 'first' eval request. If I enable comint-process-echoes after I've done an eval on sly, things are fine. Though a sayoonara command exhibited the same behavior.

By the way, C-g works to quit out of this 'frozen' state so I don't have to quit emacs. Though Esc Esc Esc does not. Additionally, no events were logged to sly-events, nor inferior-lisp that seem to indicate anything going wrong.

I'll reproduce the situation and get back to you with a full stack trace
That back trace was from running slynk in SBCL outside of sly. That is, manually opening up a server in a separate terminal.

As per my setup:
* I'm using latest win32 AMD64 SBCL build from [sbcl.org](http://www.sbcl.org/platform-table.html)
* I installed emacs on Windows at a time where that was... difficult, at best. That's given me a aversion to changing my (working) setup. That said, while I doubt a new emacs version will fix this issue I'll upgrade anyway.

Thanks for your response!

**Comment by joaotavora** [comment]
Wilfredo Velázquez-Rodríguez <notifications@github.com> writes:

> I moved my .emacs.d folder and tested with a 'naked' emacs, and it worked. I'm sorry, I don't know why I didn't try that first.
> So I bisected my init file and came up with this line being at fault:
>
> (setq-default comint-process-echoes 'on)
>
> The reason I have this turned on is becuase of the comments here. But
> since I hardly use the emacs shell, so I'm fine leaving it off.

I think that you needn't do that. I'll patch SLY's REPL to set that
variable locally to nil, which is good protective practive anyway. After
this, you can either keep that line in your .emacs or move it to
to an eshell-specific hook.

> Now, interestingly this only seems to affect sly on the 'first' eval
> request. If I enable comint-process-echoes after I've done an eval on
> sly, things are fine.

Probably some off-by-one thing :-)

> Though a sayoonara command exhibited the same behavior.

Are you saying that even with comint-process-echoes set to nil,
the sayonaara command freezes?

> By the way, C-g works to quit out of this 'frozen' state so I don't
> have to quit emacs. Though Esc Esc Esc does not.

Ah yes, ESC ESC ESC is a similar but different command.

> Additionally, no events were logged to sly-events, nor inferior-lisp
> that seem to indicate anything going wrong.

Must be something really specific to comint.el, before SLY or Lisp even
enters the picture.

> I'll reproduce the situation and get back to you with a full stack trace
> That back trace was from running slynk in SBCL outside of sly. That
> is, manually opening up a server in a separate terminal.

I don't think that's necessary if you confirm that everything works
nicely with comint-process-echoes set to nil. In that case we've
identified the culprit and it's very straightforward to protect SLY
against it.

> As per my setup:
>
> * I'm using latest win32 AMD64 SBCL build from sbcl.org * I installed
> emacs on Windows at a time where that was... difficult, at
> best. That's given me a aversion to changing my (working) setup. That
> said, while I doubt a new emacs version will fix this issue I'll
> upgrade anyway.

Yes, keep that version. Or update to the 26 pretest, where a bunch of
new features, mine included, need your testing :-)

> Thanks for your response!

Thank you for your report.
