### ISSUE TITLE
Sly doesn't seem to be well started. Got very basic completion. Slime conflicts ?

### ISSUE THREAD

**Issue by vindarel** [joaotavora/sly#137]
Hello,

I tried Sly correctly with emacs -Q: working fuzzy completion, working C-r history search, but they don't work with my current config. I can start Sly (I get the message `"Slime detected… remove it for the current session?"`), but its completion system is the most basic one (typing "(ql:ql" shows usual results but TAB doesn't complete ("no completion at point" and "not unique"), C-n gives "no dynamic expansion found" and Enter enters a new line), and C-r is emacs' one, not Sly's.

I disabled everything Slime-related in my config (everything I found!). I removed Slime-related packages: ac-slime, slime-company, slime-annot, slime-company. It removed the prompt message at startup but doesn't change the rest.

Now I don't know where to investigate, so any ideas are welcome.

**Comment by PuercoPop** [comment]
I agree with @vindarel regarding fuzzy completion. After it was rewritten its 'quality' deteriorated. For example I use to do ql:apr<tab> to get system apropos but since the rewrite that is like the third.

Ive look into the code (a looong time ago) and couldnt understand the reasoning behind the ranking formula. I'm curious where it's from. It would be a good idea to split matches for packages and symbols when a : is present. Fortunately the new system is plugable.

**Comment by joaotavora** [comment]
@PuercoPop, I'm more than happy to hear your opinion, and possibly help come up with some solution, but here I think @vindarel is describing another problem altogether.

If I understand correctly SLY works as expected for @vindarel when he starts it without his normal configuration `-Q` but not when he loads it up in his normal configuration (which has SLIME, as would be expected). In that situation only, he gets "basic" completion. @vindarel, can you confirm this?

**Comment by joaotavora** [comment]
@PuercoPop I've opened #138 to deal with your completion woes

**Comment by vindarel** [comment]
I confirm that I have a nice completion with `emacs -Q`, but the useless one with my config, *even after I removed my slime config and deleted slime-related packages in the elpa/ directory*, or at least tried.

BTW @PuercoPop  with `(ql:apr TAB` I get  `(ql:system-apropos)` as the first occurence ;)

**Comment by joaotavora** [comment]
@vindarel, can you post your emacs configuration somewhere? Can I find it on github?

**Comment by vindarel** [comment]
errr… sure ? https://gitlab.com/emacs-stuff/my-elisp/blob/master/myemacs.org 

I commented out Slime stuff: https://gitlab.com/emacs-stuff/my-elisp/commit/c58d068c8f592417f0c3a8fcb3701e26688264d8 (and then deleted some elpa packages, not all).

and my elpa packages in the elpa/ directory: https://gitlab.com/snippets/1692572

**Comment by joaotavora** [comment]
@vindarel, after doing minor tweaks to your `myemacs.org` (quite a gigantic configuration file), I can't reproduce your problem. 

I even try with SLIME enabled and then try `M-x sly` and then answer `y` at the prompt. The resulting REPL has "nice completion".

I am turning off `evil-mode` though, using `M-x turn-off-evil-mode`. After I do this completion seems to work OK.

**Comment by vindarel** [comment]
so no surprise I'll have to work on my config… thanks for having a look.
