### ISSUE TITLE
When Installing Alongside SLIME SLY's REPL Does Not Come Up

### ISSUE THREAD

**Issue by artforlife** [joaotavora/sly#139]
I tried to install SLY with `M-x package-install` alongside the existing SLIME installation, just to try it out. However, after installing and compiling the files, my Emacs looks as illustrated by the screenshot attached. 

Am I missing something? Also, is it possible to get the Stickers extension working on SLIME without installing the entire SLY?

**Comment by artforlife** [comment]
![screenshot from 2018-01-11 11 22 58](https://user-images.githubusercontent.com/8064423/34837890-d9c9e93a-f6c1-11e7-8e42-08b9be4db8dc.png)

**Comment by joaotavora** [comment]
>Am I missing something?

I couldn't reproduce your behaviour with a clean Emacs -Q run. I install slime, start it and play around a bit. Then I install sly, answer "yes" at the prompt and play around with that some more.

So in your case there's something odd with your configuration (can you post it somewhere?)

But I think that you can switch to the REPL buffer using `C-x b` which probably came up but is hidden. Or you can probably quit with `M-x sly-quit-lisp` and restart with `M-x sly` (or don't quit and start a new session with `M-x sly`). In those cases I don't think the warning will come up again and you'll probably be greeted with the REPL.

> Also, is it possible to get the Stickers extension working on SLIME without installing the entire SLY?

No, stickers are exclusive to SLY.

**Comment by joaotavora** [comment]
Closing for lack of feedback. Will reopen if this changes.
