### ISSUE TITLE
SLY remote connection closed unexpectedly

### ISSUE THREAD

**Issue by stardiviner** [joaotavora/sly#144]
When I set with:
```elisp
(setq print-quoted t
         print-circle t)
```
SLY connection will closed unexpectedly.

**Comment by joaotavora** [comment]
Oh dear, that *does* sound serious. But exactly *when* does SLY close unexpectedly? On `M-x sly`, i.e. when starting? Or in some other occasion?

**Comment by stardiviner** [comment]
I start sly with `[M-x sly]`, Then type `(ql:`, I have `company-mode` enabled. After typing `(ql:`, sly reports error that remote connection closed.

**Comment by joaotavora** [comment]
Confirmed it! Should be easy to fix, but I'm away from a reliable internet connection in my computer right now
