### ISSUE TITLE
Code, copied from the REPL's history to the lisp buffer remains read-only

### ISSUE THREAD

**Issue by svetlyak40wt** [joaotavora/sly#146]
Emacs [manual says](https://www.gnu.org/software/emacs/manual/html_node/elisp/Yanking.html) that read-only property should be removed, because it is in the `yank-excluded-properties` list:

```
ELISP> yank-excluded-properties
(category field follow-link fontified font-lock-face help-echo intangible invisible keymap local-map mouse-face read-only yan\
k-handler)
```

However, it is not removed.

Here are text properties of the text in the REPL history:

```
ELISP> (text-properties-at (point))
(keymap
 (keymap
  (mouse-2 . sly-mrepl-insert-input)
  (return . sly-mrepl-insert-input)
  (13 . sly-mrepl-insert-input))
 field sly-mrepl-input read-only t help-echo "mouse-2: insert after prompt as new input" mouse-face highlight font-lock-face \
comint-highlight-input front-sticky
 (read-only)
 fontified t)
```

and here are properties of the same text, pasted into the lisp file:

```
(fontified t keymap
           (keymap
            (mouse-2 . sly-mrepl-insert-input)
            (return . sly-mrepl-insert-input)
            (13 . sly-mrepl-insert-input))
           field sly-mrepl-input read-only t mouse-face highlight font-lock-face comint-highlight-input front-sticky
           (read-only))
```

**Comment by joaotavora** [comment]
Can't reproduce this, sorry. Can you reproduce it from a clean "Emacs -Q" run, i.e. with none of your existing configuration except for SLY?

Also, please provide the precise Emacs version you are using.

Thanks,
João

**Comment by svetlyak40wt** [comment]
You right, with `emacs -Q` I can't reproduce this bug.

Do you have any ideas how could I find out what is in my configuration causes it?

**Comment by joaotavora** [comment]
> Do you have any ideas how could I find out what is in my configuration causes it?

Err, not really, but if you bisect it (comment half of it, and retest) you could probably figure out the culprit in a handful of steps.

If you share your config, I'll have a look if I can

**Comment by svetlyak40wt** [comment]
Yeah! I found it!

It [lispy-mode](https://github.com/abo-abo/lispy) causes this bug. When it is disabled, everything is OK.

I think, this is because Lispy mode binds it's own lispy-yank function on the default shortcut. I've checked and `yank` itself works as expected.

I've created an issue in the Lispy repository: https://github.com/abo-abo/lispy/issues/394

**Comment by joaotavora** [comment]
Nice!
