### ISSUE TITLE
Sticker button context menu items not functioning

### ISSUE THREAD

**Issue by mfiano** [joaotavora/sly#148]
Hello, I'm back with another bug report. Decided to finally start using "stickers" and I came across the following. I add a sticker with the dwim function, C-c C-c to arm it, run some code touching this to capture a recording, then I fetch the sticker to turn it green. Right clicking the green sticker has the items "Copy to REPL" and "Inspect". Both of these options fail to work, with the message `[sly] button is from an older connection`. This is even the case with a single lisp connection and a fresh emacs instance, and using the latest Sly. Thanks for looking into it!

**Comment by joaotavora** [comment]
Hi Michael thanks for the report. I'll look into this as soon as I get back from a short holiday, as I don't have my computer with me. In the meantime can you tell me if regular sticker replay is working ok? That's `C-c C-s C-r`

**Comment by mfiano** [comment]
Yes, that works fine.

**Comment by joaotavora** [comment]
Should be fixed. Thanks for the report

**Comment by mfiano** [comment]
Thanks @joaotavora . Any chance you could hop on that other forum to discuss something unrelated?
