### ISSUE TITLE
Unable to Use Stickers and Some Other Key Chords When Using Lisp Image

### ISSUE THREAD

**Issue by artforlife** [joaotavora/sly#149]
I have been trying to switch to SLY for my development needs and encountered a problem. Namely, it does not seem to work well when I attempt to start it with a Lisp image. 

I have the following code that I use to start my image:

```
(defun start-image (port)
  (load "/xxx/xxx/lib/elisp/allegro.el")
  (interactive "nCyc server port offset: ")
  ;; Allegro CL Emacs-Lisp interface
  (load "/opt/local/pkg/acl100-smp.64/eli/fi-site-init.el")
  ;; Allegro SubL Highlighting
  (load "allegro-highlight-subl")
  ;; Executable image name.
  (setq fi:common-lisp-image-name "/opt/local/pkg/acl100-smp.64/mlisp")
  ;; Default core image file name.
  ;; @todo get root to add logical link
  ;; (setq fi:common-lisp-image-file "/opt/local/pkg/acl90/alisp.dxl")
  (setq fi:common-lisp-image-file "/opt/local/pkg/acl100-smp.64/alisp.dxl")
  ;; Toolset designator
  (setq allegro-toolset "Allegro-altair")
  (setq allegro-default-directory (concat "~/build/"
                      (downcase (getenv "XXX_PLATFORM"))
                      "/allegro-altair/"))
  (let* ((default-directory (expand-file-name "~/xxxx/xxxxx/allegro-altair/head/"))
     (rcs-type   "src")
     (source-tag "head")
     (image-file (file-truename "/xxx/xxxxx/head/nightly/allegro-altair/latest"))
     (setup-file (dwim-setup-file port))
     (parameters (format "-I %s -L ~/%s/%s/xxxxxxx/xxx/lisp-build/setup/%s"
                 image-file rcs-type source-tag setup-file)))
    (set-fi-port (+ 1 (dwim-services-offset port)))
    (setq inferior-lisp-program (format "%s %s" fi:common-lisp-image-name parameters))
 (sly)))
```

The image starts successfully. The only change I had to make to this function is change the last line to `(sly)` from `(slime)`.

As part of the project setup, I define a couple of new modes. With SLIME, I simply hooked into those modes, and things worked. However, the SLY they do not.

Here is the code: 
```

(add-hook 'common-lisp-mode-hook #'sly-mode)
(add-hook 'fi:lisp-mode-hook #'sly-mode)
(add-hook 'fi:lisp-mode-hook #'sly-stickers-mode)
(add-hook 'fi:common-lisp-mode-hook #'sly-mode)
(add-hook 'fi:inferior-common-lisp-mode-hook  #'sly-mode)
```

The problem comes when I begin working on the actual code. Instead of being able to place stickers, I get an error about undefined key-chord. The same goes for compilation key-chords like `C-c C-c` and `C-c C-k`.  

What is more, when one opens a `.lisp` file from the drive using `C-x C-f`, the Stickers and compilation shortcuts work. However, if one does `M-.` on a function and is lead to another file, the Stickers and the compilation shortcuts stop working. Hence, it appears that using the definition feature changes something.

Do you have any suggestion about what may be the problem? How can I troubleshoot this?

**Comment by joaotavora** [comment]
It seems you are using a very curious setup in that you use ELI (Franz's emacs-lisp-interface) and SLY/SLIME. This is very odd and unrecommended, regardless if you're using SLY or SLIME.

Anyway, it's a good bet that the problem less in your `add-hook` block, where, I hope you don't mind me saying, you seem to be adding lines without knowing very well what you're doing :).

It turns out you don't need any of those lines in SLY (and probably in SLIME, too). So just get rid of that setup and try again.

It should work. If it doesn't, I'll try to reproduce it in my machine.

By the way, the reason you don't get the shortcuts is that you are toggling the modes an odd number of times with your `add-hook` gymnastics.

**Comment by artforlife** [comment]
I will try. Actually, the reason I had to add those hooks was to get the SLIME working originally.

**Comment by joaotavora** [comment]
> I will try. Actually, the reason I had to add those hooks was to get the SLIME working originally.

I believe you. But even for SLIME you shouldn't need them (if I recall correctly). It's just a lucky coincidence that you by hooking SLIME as such you probably toggled `slime-mode` an even number of times, which is a noop.

**Comment by artforlife** [comment]
Strange. Are you saying that SLIME should hook into all Lisp modes automatically? As you can see, I am defining custom modes which have new names and of which SLIME may not be aware. How is it possible?

**Comment by artforlife** [comment]
When I comment out the above `add-hook` entries, the SLY menu disappears for `*.lisp` files altogether.

**Comment by joaotavora** [comment]
@artforlife, what is the major mode in a `.lisp` source file? To discover place yourself in a `.lisp` source file and type `C-h v major-mode RET`.

**Comment by artforlife** [comment]
This is what I get:

```
major-mode is a variable defined in `C source code'.
Its value is fi:common-lisp-mode
Original value was fundamental-mode
Local in buffer inference-kernel.lisp; global value is fundamental-mode

  Automatically becomes buffer-local when set.
```

**Comment by joaotavora** [comment]
> When I comment out the above add-hook entries, the SLY menu disappears for *.lisp files altogether.

I remember ELI being so dumb that it replaces Emacs's perfectly good `lisp-mode` with `fi:lisp-mode`. That's horrible, but if you want to keep using parts of ELI, try this:

Replace

```
(add-hook 'common-lisp-mode-hook #'sly-mode)
(add-hook 'fi:lisp-mode-hook #'sly-mode)
(add-hook 'fi:lisp-mode-hook #'sly-stickers-mode)
(add-hook 'fi:common-lisp-mode-hook #'sly-mode)
(add-hook 'fi:inferior-common-lisp-mode-hook  #'sly-mode)
```

With
```
(add-hook 'fi:common-lisp-mode-hook #'sly-editing-mode)
```

This should fix it. 

(But you should really get rid of ELI)

**Comment by joaotavora** [comment]
As to your question, you're more or less right. 

> As you can see, I am defining custom modes which have new names and of which SLIME may not be aware. How is it possible?

You are not defining the modes, ELI is, but SLIME doens't hook into those modes. It could, but it (sanely) decides not too. SLY follows suit.

**Comment by artforlife** [comment]
What exactly is ELI and why is it bad? :-)

**Comment by joaotavora** [comment]
I explained in my first reply what it is. It is an earlier and very inferior alternative to SLIME. It isn't maintained properly by Franz, and breaks parts of Emacs.

If  you are connecting by SLIME you aren't even really using it. My advice is to reevaluate the need for each line of your configuration.

But tell me, is it working now?

**Comment by artforlife** [comment]
I see. So it was a private, proprietary alternative to SLIME?

And I am trying now. I shall let you know!

**Comment by artforlife** [comment]
At first glance, it seems to be working! Thank you for you help and thank you for the awesome product! 

If there are issues, I shall follow up here.

**Comment by joaotavora** [comment]
By the way, the ELI thing this is also why your previous issue #139 was happening.
