### ISSUE TITLE
Send Interactive Object to Variable

### ISSUE THREAD

**Issue by artforlife** [joaotavora/sly#151]
Another suggestion for a feature:

It would be cool if we could have a "Send to Variable" option on the right-click context menu of interactive objects. What this would do is roughly equivalent to evaluating the following in the REPL: `(setq *variable-name* <Interactive Object>)`. One could be asked for the variable name immediately after running the option from the context menu. 

Essentially, it would produce a variable at the top level that would contain this object and with which one could evaluate things. At the moment, when I use "Copy to REPL" feature, it copies the object to the REPL, but there does not seem to be a straightforward way to begin doing evaluations with that object. Perhaps I am missing something. Please correct me.

**Comment by joaotavora** [comment]
> At the moment, when I use "Copy to REPL" feature, it copies the object to the REPL, but there does not seem to be a straightforward way to begin doing evaluations with that object. Perhaps I am missing something. Please correct me.

Indeed I think you are. When you copy to the REPL, the variable `*` now holds the object as its value, making it a perfect candidate for doing evaluations. If this is not very clear from the documentation, I sure could use some help improving it, especially from a native English speaker..

BTW, another w way to do evaluation on returned objects is via "backreferences". Look this up in the manual and tell me if you don't understand something.
