### ISSUE TITLE
Sly-mrepl behaviour

### ISSUE THREAD

**Issue by ntrocado** [joaotavora/sly#158]
M-x sly-mrepl or C-c C-z replaces current buffer with the repl, even if the repl is already visible in another window. Slime would change to the repl window. Is this the expected behaviour or is there anything misconfigured in my system? I'm using Emacs 25.3.1 on Windows.

**Comment by joaotavora** [comment]
> Slime would change to the repl window. Is this the expected behaviour or is there anything misconfigured in my system? I'm using Emacs 25.3.1 on Windows.

No nothing misconfigured. I'm wondering if I should copy this slime behaviour. If the window is already visible, you think SLY should just switch to it, right?

**Comment by joaotavora** [comment]
Your suggestion makes sense, so I fixed it. Obrigado
