### ISSUE TITLE
Controlling how debugger windows are opened

### ISSUE THREAD

**Issue by ruricolist** [joaotavora/sly#160]
My least favorite thing about Sly is the exploding debugger windows. I'm typing away in buffer X while Lisp code runs in the background. When the Lisp code running hits an error, it foregrounds the debugger window using `pop-to-buffer`. But because I'm still typing, and the debugger uses letters as single-key shortcuts, anything can happen -- quitting and losing the backtrace, invoking restarts at random, nasal demons.

Would you be open to a pull request that adds a defcustom option to control how debugger windows are opened?

**Comment by joaotavora** [comment]
> Would you be open to a pull request that adds a defcustom option to control how debugger windows are opened?

yes!

**Comment by ruricolist** [comment]
So `sly-db-activate` is written to use `pop-to-buffer` when its third argument, `select`, is non-nil. But on the Lisp side (in `sly-db-loop`) `:debug-activate` is hard-coded to always send `nil` as the third argument. Is the `select` argument vestigial?

**Comment by joaotavora** [comment]
> Is the select argument vestigial?

Very much so. At least in `sly-db-loop` it has never been activated, judging from `M-x vc-region-history`, which took me back to 2003. It might have existed to support some other, non-CL backend, perhaps, or some intermediate experimental version version.

I'll clean this up.

**Comment by joaotavora** [comment]
> some intermediate experimental version.

More or less, I investigated a little bit further. There used to be a `sldb-break-with-default-debugger` that passed `select` as t (it's the equivalent of `sly-db-break-with-default-debugger` that should switch to the native debugger). It doesn't anymore, it just calls `invoke-debugger` basically.

**Comment by joaotavora** [comment]
Heads up @ruricolist, after playing around a bit with `sly-db-focus-debugger`, I redesigned it a bit.  It now defaults to `auto` which means that the debugger will be focused iff the user is expecting it, i.e. if the user has done nothing else in the meantime.  Tell me what you think of this approach.  It's also very simple implementation wise.

**Comment by ruricolist** [comment]
I haven't had a chance to try it out yet, but I wonder: how does this interact with the minibuffer? If you use a command that reads from the minibuffer I don't think last-command is updated until the read is finished.

**Comment by joaotavora** [comment]
> how does this interact with the minibuffer?

That is a good question. When I read it, I wondered a bit, and then read the code again.

> If you use a command that reads from the minibuffer I don't think last-command is updated until the read is finished.

Right, but it will still be updated in time for the debugger activation.

In a synchronous evaluation request (`sly-eval`) you are really actively waiting for a `:return` event, either normal (`:ok`) or non-local exit (`:abort` and a condition). Those do come in mid-command, even in the non-local case.  But the debugger activation (the `:debug` event) request always comes in post command, even in synchronous evaluations.  

In the mREPL, we use `channel-send`, which is different from `sly-eval`, but the debugger behavior is still the same.
