### ISSUE TITLE
sly completion company-capf has a cannot understand annotation

### ISSUE THREAD

**Issue by stardiviner** [joaotavora/sly#161]
![sly completion annotations](https://user-images.githubusercontent.com/378699/41264145-c34d8daa-6e1d-11e8-95d0-9d19c55a1505.png)

Because `sly-company` is deprecated now, and `sly` now support company-mode by `company-capf` now. I found the annotation is really weird. can't understand what it is.

**Comment by joaotavora** [comment]
You're right, it's quite cryptic unless you're already used to it.  What do you think of this?
![image](https://user-images.githubusercontent.com/387011/41283682-25c816c4-6e2f-11e8-9ed3-1aa17078e490.png)

**Comment by stardiviner** [comment]
This one in screenshot is annotation. Have to admit that is cryptic. Can't understand it intuitively.
Can sly prove this annotation or have any option for this?

**Comment by joaotavora** [comment]
I don't understand exactly what you mean. In the previous version, it was indeed cryptic, but the version I pushed now should be less cryptic. "Fn" means function, "var" means special variable, etc. The percentage after it tells you how well the completion candidate matched.

**Comment by stardiviner** [comment]
One more thing, can the annotation align more better:
when the candidate completion match score is different length, the annotation is not align well:

![image](https://user-images.githubusercontent.com/378699/41325336-41cff810-6eec-11e8-80a1-a9bcaecd5bd9.png)

The first candidate annotation is wider than other candidate annotations. Make the percent number has a fixed length? WDYT?

**Comment by joaotavora** [comment]
> Hmmm, OK.

Actually, I don't undestand what is happening in your system... This is what I get from an `Emacs -Q` session
```
emacs -Q -L . -l sly.el -f sly -L ~/.emacs.d/elpa/company-20180317.1008/ -l company -f global-company-mode --eval '(setq company-tooltip-align-annotations t)'
```

![image](https://user-images.githubusercontent.com/387011/41327201-644c6af4-6eba-11e8-8c1a-8148ed5f7e86.png)

**Comment by stardiviner** [comment]
Hmm, I tested with your command on my machine. Indeed, company works as your screenshot.
I used `company-box` package. Seems it cause this wrong align. I will post an issue on `company-box`. Thanks for your help. @joaotavora
