### ISSUE TITLE
Feature Suggestion: Ability to Inspect Multiple Objects at the Same Time

### ISSUE THREAD

**Issue by artforlife** [joaotavora/sly#163]
Such thing may already exist. In that case, I would love how to do use it. Suppose I want to inspect two objects by putting them side by side in inspector buffers. It would be nice if those inspectors behaved independently. That is, one should be able to go into and out of nested structures within an object without affecting the second inspector buffer.

At the moment, I can only summon a single inspector buffer which gets overridden whenever I inspect a new object.

**Comment by joaotavora** [comment]
This already exists, but is not very well tested. Try `C-u C-c I` instead of the usual `C-c I`

**Comment by joaotavora** [comment]
Closing, Feel free to comment once you evaluate the existing feature.
