### ISSUE TITLE
`sly-flex-completion` looks ugly

### ISSUE THREAD

**Issue by lnguyen46** [joaotavora/sly#166]
This is a minor issue but I find it really annoying when writing code.

<img width="726" alt="screen shot 2018-07-02 at 23 26 12" src="https://user-images.githubusercontent.com/22726858/42175790-ee176d56-7e50-11e8-9b78-53e6c4d32629.png">

1. My computer run:
+ Mac OS 10.13.5
+ GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511) of 2018-05-31)
+ sly-20180630.215 (`from MELPA`)
+ SBCL 1.4.3 (`$ ros run -- --version`)

2. Reproduce:
+ `M-x sly`
+ Open file `.lisp`, or jump to REPL
+ Type something

**Comment by joaotavora** [comment]
You should set `company-tooltip-align-annotations` to t.

**Comment by joaotavora** [comment]
(and lobby in [company-mode](https://github.com/company-mode/company-mode) to make that the default)
