### ISSUE TITLE
Minor annoyance regarding Autodoc

### ISSUE THREAD

**Issue by drot** [joaotavora/sly#168]
If you visit a `.lisp` file before issuing `M-x sly` you either have to revert the buffer or reopen the file in order to get information display in the echo area.

Tested with:
```
GNU Emacs 26.1.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-06-30
sly-20180703.253
```

**Comment by joaotavora** [comment]
Thanks for the report.  This had annoyed me since SLIME a long time ago, but I never had the motivation to fix it.  It should be working now.
