### ISSUE TITLE
[sly-info] Not finding info file

### ISSUE THREAD

**Issue by rprimus** [joaotavora/sly#170]
Fri Jul  6 14:33:38 BST 2018

### System Info:

- **ProductName**:	Mac OS X
**ProductVersion**:	10.13.6
**BuildVersion**:	17G54a
- **Emacs**: "GNU Emacs 26.1 (build 1, x86_64-apple-darwin17.7.0, Carbon Version 158 AppKit 1561.4) of 2018-06-14"
- **sly**: 20180703.1308 (from MELPA)
- **lisp**: SBCL 1.4.9

### Problem:
`sly-info` command is not finding the `sly.info` file in the sly package directory.

Am asked to run `make`:
```
helm-M-x: [sly] No sly.info, run ‘make -C doc sly.info’ in /Users/rprimus/.emacs.d/prelude/elpa/sly-20180703.1308/
```

0.  `sly.info` already exists in the (elpa directory (and is available via `C-h i`)
1.  There is no supplied `Makefile`.

### Steps to reproduce:
![sly-info-2](https://user-images.githubusercontent.com/278414/42383490-46073ede-812f-11e8-9135-a141ca973b6d.gif)

**Comment by rprimus** [comment]
Fri Jul  6 15:27:57 BST 2018

### Update:
`sly-info--file` returns `‘~/dotfiles/.emacs.d/elpa/sly-20180703.1308/sly.el’`
and is looking for `"doc/sly.info"`.   This fails as there is no `doc` subdirectory.

`mkdir doc && mv sly.info doc` solves the problem.

**Comment by rprimus** [comment]
Fri Jul  6 15:56:05 BST 2018

I didn't modify the error message.

**Comment by joaotavora** [comment]
`sly--info-file` could look up two directories, right?  First `./doc`, then `.`, and then only failing that would it issue the error.

**Comment by rprimus** [comment]
Fri Jul  6 18:08:27 BST 2018

> sly--info-file could look up two directories, right? First ./doc, then ., and then only failing that would it issue the error.

Sounds good.

> Possibly it does not exist in the melpa-based installation that you're using.

Might be worth installing `sly` via emacs' in-built package system (like I did)  to see what is installed and modify the recipe to include any missing directories/files - so that the error message
1.  makes sense and
2. is actionable.
