### ISSUE TITLE
[GUI] [Completions] Instructions and inconsistencies with terminal emacs

### ISSUE THREAD

**Issue by rprimus** [joaotavora/sly#182]
Mon Jul 16 19:40:45 BST 2018

<details>
<summary>System Info:</summary>
<hr>

### System Info:

- **OS**:
  - ProductName:	Mac OS X
  - ProductVersion:	10.13.6
  - BuildVersion:	17G65
- **Emacs**: GNU Emacs 26.1 (build 1, x86_64-apple-darwin17.7.0, Carbon Version 158 AppKit 1561.4) of 2018-06-14
- **Lisp**: SBCL 1.4.9
- **sly**: sly-20180715.603
</details>
<br>

1.  The instructions mention `TAB` and `C-p` for navigation.
      This should be `C-n` and `C-p` for navigation.

2.  In terminal emacs,  both `TAB` and `RET` make a selection and returns user to the mREPL.
     In GUI emacs, `RET` on the  selection causes a backtrace.
     (Whatever is at the mREPL is evaluated.)

![sly-completions](https://user-images.githubusercontent.com/278414/42776956-8e3d0914-8930-11e8-81e9-fc9ce5792e8b.gif)

**Comment by joaotavora** [comment]
easy enough to fix, thanks

**Comment by rprimus** [comment]
Mon Jul 16 22:11:30 BST 2018

Not sure if I needed to open two separate issues.

That fix took care of point 1.

Point 2 (`RET`) invoking the debugger is still happening (in the GUI).

**Comment by joaotavora** [comment]
> Point 2 (RET) invoking the debugger is still happening (in the GUI).

Oh you're right.  Sorry I got ahead of myself
