### ISSUE TITLE
[melpa] [recipe] [repo] capitaomorte ...

### ISSUE THREAD

**Issue by rprimus** [joaotavora/sly#184]
Tue Jul 31 02:13:58 BST 2018

Simply trying to use [`paradox`](https://github.com/Malabarba/paradox) has led here.

The following package recipes all (still) reference `capitaomorte` as the repo:
```
autopair
efire
sly
sly-hello-world
sly-macrostep
sly-named-readtables
sly-quicklisp
```

github.com  forwards any connections (http/s, ssh) to the correct repo, however,  
the generated `recipes.json` file contains incorrect/old data.  Any process using this file 
will similarly produce incorrect results.

FYI: MELPA team (@milkypostman, @purcell, @tarsius), Paradox (@Malabarba)
There may be other packages that have changed locations that may not have had their 
recipes updated.

**Comment by rprimus** [comment]
I forgot to include the method to reproduce - I checked by:

1. git clone melpa/melpa
2. cd melpa
3. make json
4. ag -i capitaomorte recipes

A fresh copy of recipes.json was created.

-primus
"If I had more time, I would have written you a shorter letter" - Pascal
"It isn't what you make, it's what you don't lose!"
http://www.catb.org/esr/faqs/smart-questions.html
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by rprimus** [comment]
Tue Aug  7 18:42:28 BST 2018

After some research, it appears that the github REST (v3) API also handles redirects for relocated repos.

So,  there isn't a requirement to have the melpa recipes list the current repo - unless github's redirect mechanism breaks.

**Comment by tarsius** [comment]
I've updated the recipes.
