### ISSUE TITLE
Feature Suggestion: something like `slime-call-defun`

### ISSUE THREAD

**Issue by fouric** [joaotavora/sly#186]
`slime-call-defun` is a convenience function that, in the words of the docstring, "Insert[s] a call to the toplevel form defined around point into the REPL." I find it quite nice to have (for instance, I can chain it together with `slime-compile-defun` to compile a function and switch to a REPL with the form to call the function already in place), and would love to have an equivalent function in Sly.

Would this be an acceptable feature to have? If so, might we be able to crib code from SLIME itself?

**Comment by joaotavora** [comment]
> Would this be an acceptable feature to have? If so, might we be able to crib code from SLIME itself?

Yes, and probably yes.

**Comment by Ambrevar** [comment]
Any update on this?  :)

**Comment by joaotavora** [comment]
> Any update on this? :)

No.  Are you working on it? ;-)

**Comment by Ambrevar** [comment]
Yes!  See #376 ;)

**Comment by joaotavora** [comment]
Continued in #376
