### ISSUE TITLE
Kill Sly Buffers on Quit

### ISSUE THREAD

**Issue by Zulu-Inuoe** [joaotavora/sly#190]
It'd be nice if calling `sly-quit-lisp` or `sayoonara` at the mrepl would kill the sly buffers and windows.
As it stands, quitting sly leaves me with the mrepl, events, and any inspector/debugger buffers that happened to be open at the time.

**Comment by joaotavora** [comment]
Good idea, but better make it an option and fine tuneable. I like the repl,
as it is reused when I start or restart the same lisp.

**Comment by joaotavora** [comment]
Check it out in the latest master and tell me what you think.

**Comment by Zulu-Inuoe** [comment]
Sorry about the very late response on this one but I just had a chance to try it and it works great except for two things: 
1. The window sticks around as well (even if my keep list is nil), but that may very well be a separate issue altogether.
2. Calling restart from the mrepl will kill the buffer and re-create it. In itself would not be awful except that because it doesn't kill the window, it then displays the buffer in the other window, which basically causes my window configuration to flip backwards

Purely out of curiosity: What's the use in keeping even the repl buffer when shutting down sly? Was it keep it around for this very restart issue?

Thanks !
