### ISSUE TITLE
Feature suggestion: allow CL plugins to inject elisp code

### ISSUE THREAD

**Issue by svetlyak40wt** [joaotavora/sly#192]
For example, there is a [log4slime](https://github.com/7max/log4cl/blob/master/log4slime.asd) module, which must be loaded first in CL repl, and then manually installed into the Emacs by loading elisp counterpart.

It would be cool to create a plugins system which will allow to do load only CL part and have Elisp part be injected into Emacs automatically. For example:

1. I do (ql:quickload :log4sly) in the REPL.
2. Emacs ask me if I want to enable log4sly plugin for the session.
3. I answer 'yes'
4. Extension is loaded, keybindings are configured automatically, etc.

**Comment by joaotavora** [comment]
I personally think this is a bad idea, you should rather have SLY contribs with an Elisp and CL side.  But if you don't want that try `slynk:eval-in-emacs` (making sure that the `(setq sly-enable-evaluate-in-emacs t)` variable is set beforehand to allow injection.

```
CL-USER> (slynk:eval-in-emacs 'user-init-file)
"/home/capitaomorte/.emacs.d/init.el"
CL-USER> 
```
