### ISSUE TITLE
Feature Suggestion: Launch a World in SLY

### ISSUE THREAD

**Issue by artforlife** [joaotavora/sly#194]
This feature may already exist, but I can't seem to find it. It would be useful if we had a way to start SLY using a particular world/image file. That is, for the regular start, we do `M-x SLY`. To launch a saved world, we may do something like `M-x SLY` -> `Enter name of image file: ~/image.dxl` -> We get a REPL with the loaded world.

**Comment by stardiviner** [comment]
This is interesting, I have not found this feature in SLY neither.

**Comment by rprimus** [comment]
Thu Nov  1 15:06:28 GMT 2018

Might not be *exactly* what you're looking for:

[Setting up a custom image](http://joaotavora.github.io/sly/#Loading-Slynk-faster)

The above uses `SBCL` - for: 
- `CCL`:  ("ccl" "-I" "ccl.image")
- `Allegro`: ("alisp" "-I" image.dxl")

**Comment by joaotavora** [comment]
@artforlife , @stardiviner :+1: 

@rprimus is mostly right, the way to do this is `sly-lisp-implementations`
```
sly-lisp-implementations is a variable defined in `sly.el'.
Its value is nil

Documentation:
*A list of known Lisp implementations.
The list should have the form:
  ((NAME (PROGRAM PROGRAM-ARGS...) &key KEYWORD-ARGS) ...)

NAME is a symbol for the implementation.
PROGRAM and PROGRAM-ARGS are strings used to start the Lisp process.
For KEYWORD-ARGS see `sly-start'.

Here's an example:
 ((cmucl ("/opt/cmucl/bin/lisp" "-quiet") :init sly-init-command)
  (acl ("acl7") :coding-system emacs-mule))

[back]
```

Just fill this list with whatever you like, use `C-u M-x sly` and name the implementation/world by a chosen name.
