### ISSUE TITLE
Feature request: command for starting in ask mode

### ISSUE THREAD

**Issue by mfiano** [joaotavora/sly#202]
I would very much like commands that are able to start Sly with a negative or positive prefix argument to invoke "ask" mode, so that I may bind them to keys in my config. Thanks!

**Comment by joaotavora** [comment]
Refactoring the `sly` function (a major can-of-worms) to be reusable would probably be a good idea.  But for now I would just do something like:
```lisp
(defun joaot/sly-asking ()
  "Start `sly' like with `M-- M-x sly'"
  (interactive)
  (let ((current-prefix-arg '-))
    (sly nil nil t)))
```
99% untested
