### ISSUE TITLE
Feature request: separate sly-mrepl-[previous/next]-input-or-button

### ISSUE THREAD

**Issue by mfiano** [joaotavora/sly#203]
It would be useful to separate the functionality for previous/next input/button. I would like to bind a key that *only* cycles input and not buttons.

**Comment by joaotavora** [comment]
So you want something that behaves like `M-n` and `M-p` after the prompt, but does so everywhere in the buffer. If so, I'm pretty sure the `comint.el` base library already provides those commands, and you can keybind them to whatever you want (I don't have Emacs in front of me, so can't check right now).

**Comment by mfiano** [comment]
Yes, the reason being is sometimes my point is not exactly on the input line and I don't notice, so the default functionality will jump up in the buffer when I try to cycle through the previous input lines. It's just mildly annoying at my own fault, and it'd save me a bit of time.

**Comment by mfiano** [comment]
The comint commands expect the point to be in the input line, or else a message saying otherwise is emitted.

**Comment by joaotavora** [comment]
So if you chain a command that goes to end buffer with a cycling command it should work, right? You can make a keyboard macro or define a simple command in your `.emacs` file. Try it out, if you can't i`ll help you n once I get home.

**Comment by joaotavora** [comment]
Try these two
```
(defun mfiano/comint-previous-input (arg)
  (interactive "*p")
  (end-of-buffer)
  (comint-previous-input arg))

(defun mfiano/comint-next-input (arg)
  (interactive "*p")
  (mfiano/comint-previous-input (-1 arg)))
```

**Comment by mfiano** [comment]
Thanks, that's pretty much what I got. Works! :+1:

**Comment by joaotavora** [comment]
Cool. Actually the `-1` should be `-` there. Edited
