### ISSUE TITLE
sly-eval return value is truncated

### ISSUE THREAD

**Issue by haqle314** [joaotavora/sly#211]
Org babel uses `sly-eval` to evaluate lisp code and insert the results into the current buffer. Problem is long result is truncated
For example, if I run this code, everything works as expected

    #+BEGIN_SRC lisp :results value table
    (loop for i from 1 below 10
          collect (list i (/ i) (* i i)))
	#+END_SRC

    #+RESULTS:
    | 1 | 1   |  1 |
    | 2 | 1/2 |  4 |
    | 3 | 1/3 |  9 |
    | 4 | 1/4 | 16 |
    | 5 | 1/5 | 25 |
    | 6 | 1/6 | 36 |
    | 7 | 1/7 | 49 |
    | 8 | 1/8 | 64 |
    | 9 | 1/9 | 81 |

If the returned list gets too long, the result that org receive is truncated.

    #+BEGIN_SRC lisp :results value table
    (loop for i from 1 below 40
          collect (list i (/ i) (* i i)))
    #+END_SRC

	#+RESULTS:
    | (1 1 1) | (2 1/2 4) | (3 1/3 9) | (4 1/4 16) | (5 1/5 25) | (6 1/6 36) | (7 1/7 49) | (8 1/8 64) | (9 1/9 81) | (10 1/10 100) | (11 1/11 121) | (12 1/12 144) | (13 1/13 169) | (14 1/14 196) | (15 1/15 225) | (16 1/16 256) | (17 1/17 289) | (18 1/18 324) | (19 1/19 361) | (20 1/20 400) | (21 1/21 441) | (22 1/22 484) | (23 1/23 529) | (24 1/24 576) | (25 1/25 625) | (26 1/26 676) | (27 1/27 729) | (28 1/28 784) | (29 1/29 841) | (30 1/30 900) | (31 1/31 961) | (32 1/32 1024) | (33 1/33 1089) | (34 1/34 1156) | (35 1/35 1225) | (36 1/36 1296) | (37 1/37 1369) | (38 1/38 1444) | .. |

How do I make sure that `sly-eval` return the entire list without truncation? I thought this might have something to do with `*print-length*` but my `slynk:*slynk-pprint-bindings*` already has `(*print-length* . nil)`.

**Comment by joaotavora** [comment]
Wow, i didn't know org-babel could do that. Anyway, I reproduced it: let's see what can be done...

**Comment by digash** [comment]
Just got bit by the same bug. Is there any workaround?

**Comment by joaotavora** [comment]
> Just got bit by the same bug. Is there any workaround?

No sorry. The workaround is to bite the bullet and fix this.  It's not particularly hard, just time-consuming, and I forgot about it.  I'll try to get to it tomorrow.

**Comment by joaotavora** [comment]
Should be fixed. Please test. You'll still hit a limit, though much later, at 512 (and not 40).  If that bothers you you need to turn **on** `*PRINT-CIRCLE*` in `SLYNK:*SLYNK-PPRINT-BINDINGS*`, because the 512 is a failsafe for dealing with some infinitely recursive structures.

**Comment by digash** [comment]
Works! 512 more than enough for my use-cases.
Thank you very much for awesome and quick job.
