### ISSUE TITLE
sly-mrepl-sync issue

### ISSUE THREAD

**Issue by mfiano** [joaotavora/sly#227]
If I use `sly-mrepl-sync` to switch the package and directory of the REPL, and then sometime afterwards my project directory structure changes such that the previously set directory no longer exists, when issuing `sly-restart-inferior-lisp` Sly crashes instead of noticing that the directory doesn't exist.

**Comment by joaotavora** [comment]
> Sly crashes instead of noticing that the directory doesn't exist.

Probably. Marking this a bug, short fix welcome. Thanks.

**Comment by mfiano** [comment]
I'm not sure if you meant to close an open bug ticket or not :)

**Comment by joaotavora** [comment]
🤦‍♂
