### ISSUE TITLE
Debugger: Restarts cannot be selected by the enter key

### ISSUE THREAD

**Issue by guicho271828** [joaotavora/sly#230]
```lisp
(error "hi!")
```

```
hi!
   [Condition of type SIMPLE-ERROR]

Restarts:
■0:□[RETRY] Retry SLY mREPL○evaluation request.
 1: [*ABORT] Return to SLY's top level.
 2: [ABORT-BREAK] Reset this thread
 3: [ABORT] Kill this thread
```

It works when I hit enter when the cursor is over `[RETRY]`, but It does not work when I hit enter in the position anywhere else, e.g. the positions indicated by ■,□,○.

**Comment by joaotavora** [comment]
Hmmm, thanks for the report, but this is per design.  The button is whatever is between the `[]`.  All buttons in SLY work like this.  You can also use the numbers, or `q` and `a` for quit and abort.

**Comment by guicho271828** [comment]
The problem is, when there are more than 10 restarts, then it is unable to select 10'th or later restarts by e.g. hitting 1, then 0 (bc the 1st restart is then selected.)

When I switch the buffer to the debugger, the cursor position is at ■. In SLIME the entire line is a button. It is actually interrupting my flow (I mean, the flow as a mental state) as I hit enter multiple times until I realize I have to move the cursor. Perhaps the fix is to change the default cursor position to the first `[`.

**Comment by joaotavora** [comment]
> Perhaps the fix is to change the default cursor position to the first [.

Yes! You can probably use a button-navigation function for that. I forget the name right now (on mobile).
