### ISSUE TITLE
Command menu: resurrect "in" keyword for "in-package" aside from "set package", "cd" keyword for "set directory"

### ISSUE THREAD

**Issue by guicho271828** [joaotavora/sly#231]
these shortcuts from SLIME are much more convenient and easier to memorize compared to "set package" and "set directory".
By the way, SLIME command menu is also bad, they have not-so-useful commands like resend-form and requires 4 keys "rest" to autocomplete restart-inferior-lisp .

Also some feature suggestions: 

+ `ql` or `quickload`
+ `cs` or `change system` for loading an asdf system and cd to its system-source-directory, 
+ `test system` for calling asdf:test-system
+ `load system`. ("compile system" is not included in favor of "change system", since compilation usually requires loading)
+ `in*` or `in-package*`, an enhanced version of in-package + cd, something like  which will change the package as well as change the directory to the definition path of the package.

**Comment by joaotavora** [comment]
> in* or in-package*, an enhanced version of in-package + cd, something like which will change the package as well as change the directory to the definition path of the package.

It's not exactly the same, but SLY has this feature `sly-mrepl-sync` in the REPL, bound to `C-c ~`.  It syncs the dir and the package.   

There are external contribs for doing the quickload and possibly also ASDF thingies.  It's a question of binding those commands to the `sly-mrepl-shortcut-alist`

**Comment by joaotavora** [comment]
https://github.com/joaotavora/sly-quicklisp is the link to the quicklisp contrib and someone did the sly-asdf thing the other day.  I don't know the URL but shouldn't be hard to google.

**Comment by guicho271828** [comment]
oops, but I happened to implement the ideas myself. do you consider adding them?

**Comment by guicho271828** [comment]
Personally separating a single function to a separate contrib is an overkill, and considering how everyone uses quicklisp it seems fair to included it in the main repo. Thank you for the link, I will borrow the completion logic.

**Comment by joaotavora** [comment]
> oops, but I happened to implement the ideas myself. do you consider adding them?

The `in-package` and `cd` can go in, yes, though they're a little redundant. But I will merge them (I would merge things more quickly if you followed the commit message guidelines).

What other ideas did you implement yourself?

> Personally separating a single function to a separate contrib is an overkill, and considering how everyone uses quicklisp it seems fair to included it in the main repo.

Thanks for your opinion, but contribs tend to grow, and they do so more freely in separate repos.  You can easily install a contrib with `M-x package-install RET <contrib name>`.  The tendency is for things to come _out_ of the main repo.  You can't do this is SLIME because of a technical issue, which I can explain later.

**Comment by guicho271828** [comment]
I mean, technically sly-mrepl is already in the contrib directory, and the line thats needed is just 6 lines for quicklisp. a06f4ae6757968be62f44485511773ead87827db

**Comment by guicho271828** [comment]
Edit: 8.

**Comment by joaotavora** [comment]
> What other ideas did you implement yourself?

Oh I didn't see those commits when I commented about `sly-quicklisp`.

**Comment by joaotavora** [comment]
You can very easily put those 8 lines in your `.emacs`.  If a lot of demand appears for this, I will put it somewhere in SLY.  But not `sly-mrepl`, which is about  the REPL concept, not some special library.

**Comment by guicho271828** [comment]
So it will be like, you don't plan to improve the default experience of sly. hmm... I like more batteries included, but this is your repo anyways, so fine.

**Comment by joaotavora** [comment]
> you don't plan to improve the default experience of sly. 

I do, just not this particular way. Your proposal makes Sly the IDE depend on two libraries.  Popular these libraries are, that's akward, at least in my opinion. It belongs in a contrib or in a configuration. Sly should depend on nothing but a CL implementation  and Emacs.

**Comment by guicho271828** [comment]
On the other end of extremes, I won't call it a good state when people going over stackoverflow to find some emacs lisp snippet to copy-paste. 
Perhaps some additional metapackage like sly-fanciest might work.

Also I have yet another problem: I don't use `package-install` to install slime nor sly, I install them from quicklisp and let Roswell handle the additional configuration. (`ros install slime` and `ros install sly` will download them via quicklisp and also have [`helper.el`](https://github.com/roswell/roswell/blob/5b74ca4357a01b1b60fd3b97d9a2f469caee7b54/lisp/helper.el) that lets you switch between slime and sly from the command line.
