### ISSUE TITLE
`sly-import-symbol-at-point` hangs on package conflict

### ISSUE THREAD

**Issue by ruricolist** [joaotavora/sly#236]
A minimal case, `auto.lisp`:

```
(defpackage :auto
  (:use :cl)
  (:shadow :car))
(in-package :auto)

(cl:car '(x . y))
```

If I call `sly-import-symbol-at-point` on `cl:car` (causing a package conflict) Emacs hangs until I `C-g`, whereupon the Sly debugger appears.

**Comment by joaotavora** [comment]
Ack. I think I saw this too, the other day. Thanks for reporting, I'll try to have a look later on...

**Comment by joaotavora** [comment]
Actually, turns out it was our join "focus debugger sometimes" mischief over at #160 that causes the "hanging". At least I think so. Can't quite nail down the problem tho.

**Comment by joaotavora** [comment]
Yep, but you're off the hook: it was something I removed later on...

**Comment by joaotavora** [comment]
Actually, it was only superficially to #160, only bcc7b612d4ee52a8ecc38e3e4c05cdab1f1a5bcd
