### ISSUE TITLE
`read` related functions not working

### ISSUE THREAD

**Issue by sheepduke** [joaotavora/sly#238]
I encountered a problem when using SLY in Emacs.

In the lisp file buffer, when evaluating any function that requires user input, e.g. `(read-line)`, the SLY throws error after I input anything ant hit <enter> in the mrepl.

The backtrace is as below:

```
attempt to THROW to a tag that does not exist: (NIL)
   [Condition of type SB-INT:SIMPLE-CONTROL-ERROR]

Restarts:
 0: [*ABORT] Return to SLY's top level.
 1: [ABORT] abort thread (#<THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1005B5CB23}>)

Backtrace:
 0: (THROW)
 1: (SLYNK-MREPL::MREPL-READ #<SLYNK-MREPL::MREPL mrepl-1-1> "hell ..)
 2: (SLYNK::PROCESS-REQUESTS NIL)
 3: ((LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD))
 4: ((LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD))
 5: (SLYNK-SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION SLYNK:SLYNK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD) {1005B880AB}>)
 6: ((FLET SLYNK-BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "/home/sheep/.emacs.d/elpa/sly-20190523.1801/slynk/backend/sbcl.lisp") #<FUNCTION SLYNK:SLYNK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-CHA..
 7: ((LAMBDA NIL :IN SLYNK::CALL-WITH-LISTENER))
 8: (SLYNK::CALL-WITH-BINDINGS ((*PACKAGE* . #<PACKAGE "COMMON-LISP-USER">) (*) (**) (***) (/) (//) ...) #<CLOSURE (LAMBDA NIL :IN SLYNK::CALL-WITH-LISTENER) {1005B880EB}>)
 9: ((LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD))
10: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
11: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
12: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
13: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
14: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7F5C14CCED7B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
15: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1005B5CB23}> NIL #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-CHANNEL-THREAD) {1005B5C11B}> NIL)
16: ("foreign function: call_into_lisp")
17: ("foreign function: new_thread_trampoline")
```

But if I evaluate `(read-line)` in the mrepl itself, the error disappears and everything works well.

Some environment information:
```
GNU Emacs 26.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.8) of 2019-04-13
[sly] SLY 1.0.0-beta-2
```

Since it is a Common Lisp error, I suppose is related to SLY itself.

Any thoughts? 

Thanks in advance!

**Comment by joaotavora** [comment]
> Any thoughts?

What did you expect? What should happen if you `read` outside the REPL?

**Comment by sheepduke** [comment]
Well, as the SLY says : switch to the mrepl and wait for the user input.

Then, I input something and hit enter, my program continues.

Now when I hit enter, an error occured and I could not get it working afterwards.

**Comment by joaotavora** [comment]
> Well, as the SLY says : switch to the mrepl and wait for the user input.

Who is "the SLY" here?

I am having trouble understanding your ideas. Here is what I understand:

1. There is indeed a problem when you evaluate code that uses `read` **outside** the context of a REPL evaluation, such as when using `C-x C-e`.
2. This happens very infrequently for me, but it is indeed an error.
3. I asked you your opinion about what should happen.  Do you think the user should be asked to switch to the REPL and input some sexp there? Not only is this not easy to do, but what if there are multiple concurrent such requests?  
4.  my opinion is that it's better just to error earlier when `read` happen outside a REPL evaluation.
5. Anyone knows how SLIME behaves in this situation?

**Comment by sheepduke** [comment]
I was outside so my description might not be precise. Sorry.

> Who is "the SLY" here?

"The SLY" here means, when I evaluate `(read-line)` in my Lisp buffer, the message shows `[sly] Listener waiting for input to read`.

> 3. I asked you your opinion about what should happen. Do you think the user should be asked to switch to the REPL and input some sexp there? Not only is this not easy to do, but what if there are multiple concurrent such requests?
> 4. my opinion is that it's better just to error earlier when read happen outside a REPL evaluation.
> 5. Anyone knows how SLIME behaves in this situation?

I have used SLIME for a long time before. If I recall correctly, when I evaluated `(read-line)` in the Lisp buffer, SLIME would have prompted the similar message and let me input something in the REPL. Afterwards, my input was fed to the Lisp implementation and the evaluation went on.

IMHO it is useful because it makes it easy to test functions that deal with user input.

**Comment by joaotavora** [comment]
> I have used SLIME for a long time before. If I recall correctly, when I evaluated (read-line) in the Lisp buffer, SLIME would have prompted the similar message and let me input something in the REPL. Afterwards, my input was fed to the Lisp implementation and the evaluation went on.

Sorry to hear you gave up on SLY. This is still an interesting bug tho: I have tested this (with the SLIME maintainer who works besides me) and it doesn't work very well when  multiple `(read)`  are issued from different buffers concurrently.  Ideally you want this to be "modal" like minibuffer input. I'll see what I can do: it's not going to behave like SLIME (hopefully better tho).

**Comment by sheepduke** [comment]
On 2019-06-21 05:08, João Távora <notifications@github.com> wrote:
> Sorry to hear you gave up on SLY. 
>
Well, there are several reasons that I decided to use SLIME (for
now). The most important one is that I need test `read-line` stuff and
SLY does not work :-(

Also SLY is significantly slower than SLIME from my perspective.

> This is still an interesting bug tho: I have tested this (with the SLIME maintainer who works besides me) and it doesn't work very well when  multiple `(read)`  are issued from different buffers concurrently.  Ideally you want this to be "modal" like minibuffer input. I'll see what I can do: it's not going to behave like SLIME (hopefully better tho).
>
Well, I would say this bug happens even with single SLY connection...

I will definitely try SLY later after this bug is solved. :-)

**Comment by joaotavora** [comment]
> Well, there are several reasons that I decided to use SLIME (for now). The most important one is that I need test `read-line` stuff and SLY does not work :-(

It works if you test these function from the REPL.  But I agree it won't indeed work if you evaluate these from non-REPL buffers.  Until you brought this issue to my attention, I had always thought of these kinds of evaluations as non-interactive.

> Also SLY is significantly slower than SLIME from my perspective.

I cannot understand this.  In what operations?  Can you open a new issue and describe the problem?  Can you maybe measure a similar operation in both SLY and SLIME?

> Well, I would say this bug happens even with single SLY connection...

I never said it didn't.  What I wrote is that, in SLIME, if you evaluate a `(read...)` form in a non-REPL buffer, then switch to another buffer and evaluate another `(read...)` form there, you put the single SLIME REPL in a strange inconsistent state.  Even with a single evaluation, I don't think it's a very good interface.  This has nothing to do with multiple connections.

> I will definitely try SLY later after this bug is solved. :-)

OK, I'll see what I can do.

**Comment by sheepduke** [comment]
On 2019-06-22 08:19, João Távora <notifications@github.com> wrote:
>> Well, there are several reasons that I decided to use SLIME (for now). The most important one is that I need test `read-line` stuff and SLY does not work :-(
>
> It works if you test these function from the REPL.  But I agree it won't indeed work if you evaluate these from non-REPL buffers.  Until you brought this issue to my attention, I had always thought of these kinds of evaluations as non-interactive.
>
Well, I sometimes test interactive Lisp scripts directly in a Lisp buffer. Maybe that's why I found this ;-)

>> Also SLY is significantly slower than SLIME from my perspective.
>
> I cannot understand this.  In what operations?  Can you open a new issue and describe the problem?  Can you maybe measure a similar operation in both SLY and SLIME?
>
Hmmm, hard to say. I have never tested them. I will try that maybe next week. (Got busy working on something else, sorry.)

>> Well, I would say this bug happens even with single SLY connection...
>
> I never said it didn't.  What I wrote is that, in SLIME, if you evaluate a `(read...)` form in a non-REPL buffer, then switch to another buffer and evaluate another `(read...)` form there, you put the single SLIME REPL in a strange inconsistent state.  Even with a single evaluation, I don't think it's a very good interface.  This has nothing to do with multiple connections.
>
Ah! I misunderstood you, sorry. You are right. I just tested the situation and SLIME behaved weirdly.

Probably using mini buffer has the same effect. Since there is only one mini-buffer (unless weirdly customized), what happens if the user leave the mini buffer and invoke another `(read)`?

**Comment by joaotavora** [comment]
> what happens if the user leave the mini buffer and invoke another `(read)`?

Leaving the minibuffer is indeed possible but rarer.  Normally you either finish your input or type `C-g` to cancel.  But if the user does leave and invoke another `read` I think that second `read` should error with some message that you have a pending minibuffer waiting and you should finish that one first.

**Comment by sheepduke** [comment]
> Leaving the minibuffer is indeed possible but rarer.  Normally you either finish your input or type `C-g` to cancel.  But if the user does leave and invoke another `read` I think that second `read` should error with some message that you have a pending minibuffer waiting and you should finish that one first.
>
What is the difference between using mini buffer and jumping to REPL buffer then?

**Comment by joaotavora** [comment]
> What is the difference between using mini buffer and jumping to REPL buffer then?

Good question.  Perhaps it does make for a better interface to use the REPL exclusively, but error on multiple pipelined reads, which is something for which it is hard to design a good interface.  I'll write some code tomorrow.

**Comment by sheepduke** [comment]
On 2019-06-23 09:14, João Távora <notifications@github.com> wrote:
> Good question.  Perhaps it does make for a better interface to use the REPL exclusively, but error on multiple pipelined reads, which is something for which it is hard to design a good interface.  I'll write some code tomorrow.
>
I can not wait to try it out. I really miss that SLY cat. ;-)
