### ISSUE TITLE
Docstring on first character of line breaks sly-compile-defun

### ISSUE THREAD

**Issue by Zulu-Inuoe** [joaotavora/sly#239]
Given a buffer `blah.lisp`:
```lisp
(defun foo ()
  "I am a docstring
 (which causes no problems"
  )

(defun bar ()
  "I am a docstring
(which breaks sexp parsing"
  )
```
If I place my cursor at any point after `bar`, I get this backtrace when trying to `sly-compile-defun`:
```lisp
Debugger entered--Lisp error: (scan-error "Unbalanced parentheses" 102 137)
  scan-sexps(102 1)
  forward-sexp(1)
  #f(compiled-function () #<bytecode 0x1002634a9>)()
  end-of-defun()
  sly-region-for-defun-at-point()
  sly-compile-defun(nil)
  funcall-interactively(sly-compile-defun nil)
  call-interactively(sly-compile-defun nil nil)
  command-execute(sly-compile-defun)
```

I'm not sure what to attribute this to, because paredit experiences similar behaviour:
```lisp
Debugger entered--Lisp error: (scan-error "Unbalanced parentheses" 128 137)
  scan-sexps(128 1)
  forward-sexp(1)
  paredit-string-start+end-points()
  paredit-enclosing-string-start()
  paredit-move-backward()
  paredit-backward(1)
  funcall-interactively(paredit-backward 1)
  call-interactively(paredit-backward nil nil)
  command-execute(paredit-backward)
```

**Comment by joaotavora** [comment]
> because paredit experiences similar behaviour

That's because this is a (longstanding?) Emacs bug, I think. Avoid the situation or escape the opening parenthesis somehow.

**Comment by alexanderbarbosa** [comment]
jeez

**Comment by hjudt** [comment]
I have another example that seems similar:
`(defun confusing-docstring ()
  "This is a docstring with a function call on the beginning of the
(second line) that confuses emacs."
  (+ 1 2)
  (+ 3 4))
`
Going inside that function, e.g. on (+ 1 2) or (+ 3 4) and hitting C-m-h selects `(second line)` instead of the whole function. Also, hitting C-m-x does not compile the function but complains about line being an unbound variable.
Inserting a space character before (second line) so that it is not at the start of the line restores the proper behaviour.

**Comment by joaotavora** [comment]
Yes it's the same emacs bug. Can you do us a favor and search the emacs bug tracker for the bug so we can link them?

**Comment by hjudt** [comment]
I tried, but I couldn't find a proper match, using terms parens and docstring. Here is one that might somehow be related: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=22717 (for shell-script-mode)

**Comment by joaotavora** [comment]
Read this https://www.gnu.org/software/emacs/manual/html_node/emacs/Left-Margin-Paren.html

There is this thread of discussion about it https://debbugs.gnu.org/cgi/bugreport.cgi?bug=21871, but the variable is from 2000 so there's probably many more such threads.  It's not even considered a bug anymore (I would beg to differ, but it doesn't bother me so much).

**Comment by xuchunyang** [comment]
[(emacs) Font Lock](https://www.gnu.org/software/emacs/manual/html_node/emacs/Font-Lock.html) also explains the reason of the convention:

> Comment and string fontification (or “syntactic” fontification)
> relies on analysis of the syntactic structure of the buffer text.  For
> the sake of speed, some modes, including Lisp mode, rely on a special
> convention: an open-parenthesis or open-brace in the leftmost column
> always defines the beginning of a defun, and is thus always outside any
> string or comment.  Therefore, you should avoid placing an
> open-parenthesis or open-brace in the leftmost column, if it is inside a
> string or comment.  *Note Left Margin Paren::, for details.

Just in case you've not read it.

**Comment by npostavs** [comment]
This should be fixed in Emacs `master` (version 27), by the way.

https://debbugs.gnu.org/20761
https://debbugs.gnu.org/20284

**Comment by joaotavora** [comment]
> This should be fixed in Emacs master (version 27), by the way.

I should have asked sooner then :-)

**Comment by hjudt** [comment]
That's great news and the articles are both funny and interesting. So I will be waiting for Emacs 27...
