### ISSUE TITLE
Calling (sb-debug:list-backtrace) crashes Sly:  pretty printer limits need reviewing.

### ISSUE THREAD

**Issue by PuercoPop** [joaotavora/sly#241]
To reproduce start a fresh sly with

`$ emacs -Q -L . -l sly-autoloads --eval '(setq inferior-lisp-program "sbcl")' -f sly`

And eval `(sb-debug:list-backtrace)`. The repl immediately 'crashes' and the inferior-lisp seems to be in an infinite loop.

```
CL-USER> (sb-debug:list-backtrace)
Control stack guard page temporarily disabled: proceed with caution
; Lisp connection closed unexpectedly: connection broken by remote peer
; --------------------------------------------------------
```

<details>
<summary> Output of the inferior lisp buffer</summary>
<pre>
encode-message
decode-message
dispatch-event: (:EMACS-CHANNEL-SEND 1 (:PROCESS "(sb-debug:list-backtrace)"))
send-event: #<SB-THREAD:THREAD "sly-channel-1-mrepl-remote-1" RUNNING {100394D013}> (:EMACS-CHANNEL-SEND #<SLYNK-MREPL::MREPL mrepl-1-1> (:PROCESS "(sb-debug:list-backtrace)"))
dispatch-event: (:CHANNEL-SEND 1 (:WRITE-VALUES (("((SB-INT:SIMPLE-EVAL-IN-LEXENV (LIST-BACKTRACE) #<NULL-LEXENV>)
 (EVAL (LIST-BACKTRACE)) ((LAMBDA () :IN SLYNK-MREPL::MREPL-EVAL-1))
 (SLYNK::CALL-WITH-RETRY-RESTART \"Retry SLY mREPL evaluation request.\"
                                 #<CLOSURE (LAMBDA ()
                                             :IN
                                             SLYNK-MREPL::MREPL-EVAL-1) {1003CDC58B}>)
 ((LAMBDA () :IN SLYNK-MREPL::MREPL-EVAL-1))
 ((LAMBDA () :IN SLYNK::CALL-WITH-LISTENER))
 (SLYNK::CALL-WITH-BINDINGS
  ((*PACKAGE* . #<PACKAGE \"COMMON-LISP-USER\">) (*) (**) (***) (/) (//) (///)
   (+ LIST-BACKTRACE) (++) (+++)
   (SLYNK-MREPL::*HISTORY*
    . #((((SB-INT:SIMPLE-EVAL-IN-LEXENV (LIST-BACKTRACE) #<NULL-LEXENV>)
          (EVAL (LIST-BACKTRACE)) ((LAMBDA () :IN SLYNK-MREPL::MREPL-EVAL-1))
          (SLYNK::CALL-WITH-RETRY-RESTART \"Retry SLY mREPL evaluation request.\"
                                          #<CLOSURE (LAMBDA ()
                                                      :IN
                                                      SLYNK-MREPL::MREPL-EVAL-1) {1003CDC58B}>)
          ((LAMBDA () :IN SLYNK-MREPL::MREPL-EVAL-1))
          ((LAMBDA () :IN SLYNK::CALL-WITH-LISTENER))
          (SLYNK::CALL-WITH-BINDINGS
           ((*PACKAGE* . #<PACKAGE \"COMMON-LISP-USER\">) (*) (**) (***) (/) (//)
            (///) (+ LIST-BACKTRACE) (++) (+++)
            (SLYNK-MREPL::*HISTORY*
             . #((((SB-INT:SIMPLE-EVAL-IN-LEXENV (LIST-BACKTRACE)
                                                 #<NULL-LEXENV>)
                   (EVAL (LIST-BACKTRACE))
                   ((LAMBDA () :IN SLYNK-MREPL::MREPL-EVAL-1))
                   (SLYNK::CALL-WITH-RETRY-RESTART
                    \"Retry SLY mREPL evaluation request.\"
                    #<CLOSURE (LAMBDA ()
                                :IN
                                SLYNK-MREPL::MREPL-EVAL-1) {1003CDC58B}>)
                   ((LAMBDA () :IN SLYNK-MREPL::MREPL-EVAL-1))
                   ((LAMBDA () :IN SLYNK::CALL-WITH-LISTENER))
                   (SLYNK::CALL-WITH-BINDINGS
                    ((*PACKAGE* . #<PACKAGE \"COMMON-LISP-USER\">) (*) (**) (***)
                     (/) (//) (///) (+ LIST-BACKTRACE) (++) (+++)
                     (SLYNK-MREPL::*HISTORY*
                      . #((((SB-INT:SIMPLE-EVAL-IN-LEXENV (LIST-BACKTRACE)
                                                          #<NULL-LEXENV>)
                            (EVAL (LIST-BACKTRACE))
                            ((LAMBDA () :IN SLYNK-MREPL::MREPL-EVAL-1))
                            (SLYNK::CALL-WITH-RETRY-RESTART
                             \"Retry SLY mREPL evaluation request.\"
                             #<CLOSURE (LAMBDA ()
                                         :IN
                                         SLYNK-MREPL::MREPL-EVAL-1) {1003CDC58B}>)
                            ((LAMBDA () :IN SLYNK-MREPL::MREPL-EVAL-1))
                            ((LAMBDA () :IN SLYNK::CALL-WITH-LISTENER))
                            (SLYNK::CALL-WITH-BINDINGS
                             ((*PACKAGE* . #<PACKAGE \"COMMON-LISP-USER\">) (*)
                              (**) (***) (/) (//) (///) (+ LIST-BACKTRACE) (++)
                              (+++)
                              (SLYNK-MREPL::*HISTORY*
                               . #((((SB-INT:SIMPLE-EVAL-IN-LEXENV
                                      (LIST-BACKTRACE) #<NULL-LEXENV>)
                                     (EVAL (LIST-BACKTRACE))
                                     ((LAMBDA ()
                                        :IN
                                        SLYNK-MREPL::MREPL-EVAL-1))
                                     (SLYNK::CALL-WITH-RETRY-RESTART
                                      \"Retry SLY mREPL evaluation request.\"
                                      #<CLOSURE (LAMBDA ()
                                                  :IN
                                                  SLYNK-MREPL::MREPL-EVAL-1) {1003CDC58B}>)
                                     ((LAMBDA ()
                                        :IN
                                        SLYNK-MREPL::MREPL-EVAL-1))
                                     ((LAMBDA ()
... continues ad-infinitum
</pre>
</details>

**Comment by joaotavora** [comment]
Better do something like:
```lisp
(setf (cdr (assoc '*print-level* slynk:*slynk-pprint-bindings*)) 10)
```

or 

```lisp
(setf (cdr (assoc '*print-circle* slynk:*slynk-pprint-bindings*)) t)
```

If you're going to attempt this kind of down-the-rabbit-hole thing.  

These things should probably be the default.  Or something.  How does SLIME behave? I'm going to review these functions in the scope of #211, so I'll handle it there.

**Comment by joaotavora** [comment]
closing this in favor of #211.

**Comment by joaotavora** [comment]
Should be fixed, please test...

**Comment by PuercoPop** [comment]
Can confirm it is fixed. Thanks @joaotavora
