### ISSUE TITLE
uiop:define-package indent rule

### ISSUE THREAD

**Issue by mfiano** [joaotavora/sly#243]
Please please please add an indentation rule for uiop's `define-package`. This is just bad:
```lisp
(uiop:define-package #:golden-utils
    (:nicknames #:au)
  (:use #:cl)
  (:mix-reexport #:alexandria))
```

**Comment by joaotavora** [comment]
It'd work if it were `(defmacro define-package (package &body clauses)...)` instead of `&rest` clauses...  (and if you were online). AFAIK that's how SLY/SLIME has always indented such forms.  But you can make exceptions from your Emacs init file (just don't remember how exactly ATM)

**Comment by mfiano** [comment]
Yes, I'm aware. I figured I'd ask here, since I saw recent `uiop:define-package` support in a PR, and I work with several developers and the form is constantly being committed back to the wrong indentation. Perhaps this should be reported to `asdf` if that cannot be done internal to Sly.

**Comment by joaotavora** [comment]
I guess if we added support for `uiop:define-package` elsewhere we can hardcode its indentation, too.  PR welcome.

**Comment by svetlyak40wt** [comment]
> But you can make exceptions from your Emacs init file (just don't remember how exactly ATM)

Probably SLY supports http://quickdocs.org/trivial-indent/?

**Comment by joaotavora** [comment]
Probably SLY supports http://quickdocs.org/trivial-indent/?

No idea. I had a brief look and don't understand how that is simpler than just:

```
(put 'uiop:define-package 'common-lisp-indent-function '(as defpackage))
```

which is what the proposed commit fd918c8 does, btw.  Please test it and report back.

**Comment by joaotavora** [comment]
> I had a brief look and 

Apparently someone added sly support (https://github.com/Shinmera/trivial-indent/issues/1).  Apparently is has to be loaded into the lisp before SLY/SLIME comes up, I personally don't like that.

**Comment by mfiano** [comment]
@joaotavora Ah you beat me to it, thanks. I'll test this in the coming day or 2 and report back. As much as the fix belongs in `asdf` itself, implementations are very slow at updating the bundled version, and it'd be years until it had any real effect.

**Comment by mfiano** [comment]
I tested this well enough and I don't see a reason not to merge this into master now. Thanks!
