### ISSUE TITLE
Inspecting SLYNK-TRACE-DIALOG::TRACE-ENTRY is mostly broken (was "Cannot sly-mrepl-copy-part-to-repl from for trace-entries")

### ISSUE THREAD

**Issue by deepestthought42** [joaotavora/sly#245]
In `*sly-scratch*`:
```lisp
;; define this function:
(defun inspector-test (a b)
  (list a b))
```

Doing a `sly-trace-dialog-toggle-trace` on `inspector-test`, calling it:
```lisp
(inspector-test "a" "b")
```
inspecting the trace and then trying to `sly-mrepl-copy-part-to-repl` in the inspector on
e.g. the trace entry object results in (for sbcl):

`The value
  NIL
is not of type
  SLYNK::ISTATE
   [Condition of type TYPE-ERROR]
`
Similar under allegro. Most recent version and of sly and sbcl.

**Comment by joaotavora** [comment]
most unusual.  I use this function every single day, especially under allegro (but also sbcl). How did you install SLY? Can you reproduce this from an Emacs -Q run?

**Comment by joaotavora** [comment]
Hmm, rereading your report, there might be something more subtle.  What exactly are you trying to return to the REPL.  What does "inspecting the trace" mean.  It is inspecting the `SLYNK-TRACE-DIALOG::TRACE-ENTRY` object?

**Comment by deepestthought42** [comment]
In transit now so can't check at the moment, but yes, it works unless
inspecting the trace-entry object.

**Comment by joaotavora** [comment]
Hmmm, I think I understand what's going on.  It only happens with `TRACE-ENTRY` objects, and is probably related to multiple inspectors.  It's a bug, thanks for reporting.

**Comment by joaotavora** [comment]
@deepestthought42 should be fixed.  Please test.

**Comment by deepestthought42** [comment]
Indeed, it works now. Thanks!
