### ISSUE TITLE
Strange behaviour on HTML doc buttons

### ISSUE THREAD

**Issue by equwal** [joaotavora/sly#246]
These brackets jump above and below the buttons when you decrease the width of you screen.
[Image of strange behaviour in the doc](https://spensertruex.com/static/strange-behaviour-sly.png)

**Comment by joaotavora** [comment]
This is irreproducible here. What browser are you using?

**Comment by equwal** [comment]
That is just firefox, albeit a somewhat outdated version 60.6.2

**Comment by joaotavora** [comment]
Alright, I reproduced it.

**Comment by joaotavora** [comment]
Alright, I reproduced it.

**Comment by joaotavora** [comment]
You can work on this, but I don't think it's worth it.

**Comment by joaotavora** [comment]
To clarify: if you do work on this and the solution is less than, say, 20 lines in total, then I will merge it.
