### ISSUE TITLE
Feature request: eval in frame functionality

### ISSUE THREAD

**Issue by mfiano** [joaotavora/sly#248]
It would be incredibly useful if `sly-db-eval-in-frame` could be told to emit to the REPL the return value of what I evaluate inside of a stack frame. Instead of using `setf` to assign it to some global variable, so that I can just inspect the thing at point in the REPL for large aggregate objects like nested hash tables. I have no idea how difficult something like this would be to implement. Just throwing the idea out there :)

**Comment by joaotavora** [comment]
I usually use `i` for this, the return the inspected object to the REPL. Apart from the extra keystroke, is there anything that this method doesn't do for you? (PS: it's not particularly hard to implement, but we already have `e`, `d` and `i` which all do basically the same thing, so I think twice before adding yet another one).

**Comment by mfiano** [comment]
Oh my use case is to press `e` on a particular frame, and then in the minibuffer prompt I evaluate something in that frame, but the result is not inspectable as far as I am aware. I would like to capture the return value of evaluating something in a frame, so that I *can* inspect it.

**Comment by joaotavora** [comment]
but if you press `i` instead of `e` won't it work?

**Comment by mfiano** [comment]
Yes actually. I am not sure why I was thinking that did not allow one to evaluate an arbitrary form to inspect. I thought it just inspected the locals of that frame. I guess that completely solves my issue and invalidates this issue. Sorry for the noise, and thank you :)

**Comment by joaotavora** [comment]
> I thought it just inspected the locals of that frame.

You can click on those directly (but you probably know that).

BTW what implementation are you using? SBCL normally optimizes out every local variable but the arguments.

> Sorry for the noise, and thank you :)

No problem

**Comment by mfiano** [comment]
Yes, I'm aware, and yes, SBCL. `C-u C-c C-c` will usually give better results in that regard.

**Comment by joaotavora** [comment]
> C-u C-c C-c will usually give better results in that regard.

Oh nice, I always forget about that.
