### ISSUE TITLE
Use completing-read (for Helm/Ivy) on comma-commands

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#261]
See https://github.com/emacs-helm/helm/issues/2165#issuecomment-506822836.

**Comment by joaotavora** [comment]
@Ambrevar try this commit and tell me if it fixes this.  Helm, Ivy, or whatever the completion framework du jour is should now work in comma-commands, and other completion bits in SLY, provided they hook onto `completing-read-function`.  `ido-mode` still pops in as a fallback if the user has left `completing-read-function` uncustomized

**Comment by Ambrevar** [comment]
Nice!

I've briefly tested over comma-commands an sly-quickload and it seems to
work fine.

Is there any other area where SLY used to use its own completion?

**Comment by joaotavora** [comment]
> Is there any other area where SLY used to use its own completion?

A couple more, yes.  Like when your have multiple connections and SLY asks you to choose one.  Or with `M-x sly-info`.  That sort of stuff.  The only problem place where Helm is not going to work cleanly is when completing symbol names, but I really do think the problem is on Helm's side.

**Comment by Ambrevar** [comment]
Thanks for the tips, just realized the is a bug in sly-info ;)  See
#263.

As I mentioned in the Helm-SLIME pull request, I've got completion to
work via helm-company.  It seems to work perfectly (it displays the
percentage).  Is there another problem I'd be missing?

**Comment by joaotavora** [comment]
What is helm company? Is it a helm backend that uses company to collect the candidates.  If so, since company is a compliant backend, that's probably a good solution. 

> Is there another problem I'd be missing?

Maybe not, try adding or removing some characters to narrow down and expand the symbol completion search.

**Comment by Ambrevar** [comment]
Thanks for the patch!

helm-company is a frontend to company.

Adding characters works as expected.
I can't remove characters however, because Helm input is empty with
helm-company, but that's expected so it's all good then!
