### ISSUE TITLE
Expand sly-info--file to accept system installs

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#263]
Currently sly-info--file will report that sly.info is missing if SLY was installed at the system level (e.g. with Guix).
I propose to add `Info-directory-list` to the list.

**Comment by joaotavora** [comment]
> I propose to add Info-directory-list to the list.

Sorry if it's obvious, but does you proposal fix the problem?  Does it also fix it in other situations (i.e. not only Guix?)

**Comment by Ambrevar** [comment]
Indeed, `Info-directory-list` is not specific to Guix, it should work for everyone.

Here is a patched function that works for me (and I hope would work in all cases):
```elisp
(defun sly-info--file ()
  (or (cl-some (lambda (subdir)
                 (cl-flet ((existing-file (name)
                                          (let* ((path (expand-file-name subdir sly-path))
                                                 (probe (expand-file-name name path)))
                                            (and (file-exists-p probe) probe))))
                   (or (existing-file "sly.info")
                       (existing-file "sly.info.gz"))))
               (append '("doc" ".") Info-directory-list))
      (sly-error
       "No sly.info, run `make -C doc sly.info' from a SLY git checkout")))
```

**Comment by joaotavora** [comment]
OK. You'll probably run into a separate problem with finding the pngs for some of the info sections, but that a different problem reported somewhere around here.

**Comment by Ambrevar** [comment]
Indeed, I get a bunch of


    [image src="images/tutorial-1.png"]

**Comment by Ambrevar** [comment]
Note the support for compressed files in my example.

**Comment by joaotavora** [comment]
I pushed your version

**Comment by Ambrevar** [comment]
Thanks!
