### ISSUE TITLE
Mention Helm-SLY in the readme?

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#267]
Now that Helm-SLY is up, what about mentioning it in the README, maybe after the contribs?

**Comment by joaotavora** [comment]
OK. But keep it short.  Something like "For Helm fans, see <link to Helm SLY>". As far as I understand, the Helm developer is working on improvements that should, in principle, render Helm SLY obsolete (which is a good thing, right?).

**Comment by Ambrevar** [comment]
Actually it wouldn't: what the Helm developer mentioned was about code completion,
which Helm SLY does not tackle at all.

What Helm SLY does is essentially adding completion which lacks in SLY,
e.g.

- list of connections
- list of other Lisp buffers (threads, scratch, etc.)
- Xref.

SLIME suffer from the same issues.  To make Helm-SLY (mostly) obsolete
(which would be a good thing :p),
we would need to use completion-read instead of buffers in those places.

If that's too controversial a change, maybe an option to choose between
completion and buffers?

**Comment by joaotavora** [comment]
> Actually it wouldn't: what the Helm developer mentioned was about code completion,
which Helm SLY does not tackle at all.

I haven't followed those developments closely, I was jus t guessing.

> If that's too controversial a change, maybe an option to choose between
completion and buffers?

I don't know exactly what you mean, but you already have `sly-symbol-completion-mode`.  If you make that `nil` then `completing-read` is used for symbols (and xref completion, too, I think).  Otherwise, for connections, and such, just set `completing-read-function` and SLY should use that, too.  It is only if you leave `completing-read-function` set to its default value that SLY will use `ido-mode`.

**Comment by Ambrevar** [comment]
I think there is a misunderstanding.

What Helm-SLY aims to replace are those commands:

- sly-list-connections
- sly-who-*
- sly-edit-definition
- sly-apropos*

All those commands bring up a buffer.
I'm not sure how to get completion over connections.

What helm-sly-list-connections does: it brings up a Helm buffer of
connections / REPLs, which the user can fuzzy-search, narrow down,
multi-select, all the Helm goodies.  The user can execute different
actions on the selected connections, like show, rename, delete, etc.

**Comment by joaotavora** [comment]
> I think there is a misunderstanding.

> What Helm-SLY aims to replace are those commands:

Oh indeed there was.  Cool.  So make a PR for the README.md and maybe show a gif in the Helm-sly homepage.

**Comment by Ambrevar** [comment]
I'll make a PR.

What do you think of adding completion so SLY like I suggested?

**Comment by joaotavora** [comment]
> What do you think of adding completion so SLY like I suggested?

You meant "to", right? 

If so , I don't understand SLY already has completion where I think it needs it: completing symbol names, the most important thing, and also it uses `completing-read` for things such as connections, REPL comma-actions, etc... I don't think that will/should change much.

Where else do you think completion is useful? `*SLY xref*` buffers are not going away, for example.  At most they are being replaced by the nicer built-in Emacs `*xref*` buffers, if that's what you are asking.

**Comment by Ambrevar** [comment]
Yes, I meant "to".

Even with Apropos and Xref buffers staying, we could offer an option /
alternative command where the user would _complete_ against the list of
suggestions.

This alone would make Helm-SLY mostly obsolete.

**Comment by Ambrevar** [comment]
This is now in the readme.
