### ISSUE TITLE
Restore C-c M-o (sly-mrepl-clear-repl)

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#268]
SLIME has a the `C-c M-o` binding by default to clear the buffer.
This can be useful when working with code that produces huge outputs multiple times, which can make the REPL slow or break fontification / lispy / paredit / rainbow-delimiters / etc.

Thoughts?

**Comment by joaotavora** [comment]
I'll accept a PR that adds this to `contrib/sly-mrepl.el`

**Comment by joaotavora** [comment]
Fixe in master.
