### ISSUE TITLE
Custom face for exported symbols

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#269]
I originally posted this for SLIME: https://github.com/slime/slime/issues/522.
For reference:

In Common Lisp it's easy to programmatically get the list of exported symbols:

```lisp
(let ((package (find-package foo))
      (symbols nil))
  (do-external-symbols (s package symbols)
    (when (eq (symbol-package s) package)
      (push s symbols)))
  symbols)
```

What would be neat is to highlight them in Emacs, e.g. use a custom face for exported symbols.
What do you think?

I'd be happy to provide a patch, but I'm not too knowledgeable with Slynk so any guidance for a starting point would be very welcome!

**Comment by Ambrevar** [comment]
More generally, SLY could expose an interface for semantic customization, i.e. fontify depending on the package, if it's a macro, etc.  And what about doing other things beyond fontification?

**Comment by joaotavora** [comment]
Let's put this on hold for the moment until #270 is sorted out.  As you point out there, there would probably be shared implementation details.

**Comment by joaotavora** [comment]
I'll re-open once #270 starts working a bit.
