### ISSUE TITLE
what font is that in the GIF section of the README?

### ISSUE THREAD

**Issue by cschep** [joaotavora/sly#278]
Love that font in the GIF section of the README, what is it? :)

Thanks for the hard work!

**Comment by joaotavora** [comment]
I believe it's Terminus or "misc-fixed" or some variation thereof.  http://terminus-font.sourceforge.net/
Might be misc-fixed http://underpop.online.fr/l/linux-console-fonts-for-windows-in-ttf-and-fon/ (for windows).

Anyway, it's not antialiased.

**Comment by cschep** [comment]
thanks so much!
