### ISSUE TITLE
`company-abort` while company completion within sly-REPL crashes emacs

### ISSUE THREAD

**Issue by bymoz089** [joaotavora/sly#279]
## Description:
trying to abort a company-complete popup while working in sly crashes/freezes emacs.

## How to reproduce:
  1. Start emacs without configuration `emacs -Q`
  2. initialize package manager `(require 'package) (package-initialize)`
  3. load and enable company `(require 'company) (global-company-mode)`
  4. load sly (require 'sly)
  5. start REPL `M-x sly`
  6. enter something into the REPL to be completed like `(ql-`
  7. wait for company-completion popup to appear
  8. go down the completion list with `<down>` or `C-n`
  9. abort completion with `C-g`
  10. result: emacs freezes and a backtrace is printed to terminal

## backtrace:

> #>emacs -Q
> *** longjmp causes uninitialized stack frame ***: emacs terminated
> ======= Backtrace: =========
> /lib/i386-linux-gnu/libc.so.6(+0x6738a)[0xf600238a]
> /lib/i386-linux-gnu/libc.so.6(__fortify_fail+0x37)[0xf6093747]
> /lib/i386-linux-gnu/libc.so.6(+0xf862a)[0xf609362a]
> /lib/i386-linux-gnu/libc.so.6(__longjmp_chk+0x3e)[0xf609359e]
> emacs[0x81328c4]
> emacs[0x814210d]
> emacs[0x81e9a5c]
> emacs[0x8064e36]
> emacs[0x813ec2c]
> emacs[0x813f11b]
> emacs[0x8140c6c]
> emacs[0x81a720f]
> emacs[0x8131e6f]
> emacs[0x81a71a3]
> emacs[0x8131e1b]
> emacs[0x8136637]
> emacs[0x81369c5]
> emacs[0x805ad0a]
> /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf6)[0xf5fb3286]
> emacs[0x805b9f0]
> ======= Memory map: ========
> 08048000-082d5000 r-xp 00000000 08:03 1442822                            /usr/bin/emacs25-x
> 082d5000-082d9000 r--p 0028c000 08:03 1442822                            /usr/bin/emacs25-x
> 082d9000-08a6f000 rw-p 00290000 08:03 1442822                            /usr/bin/emacs25-x
> 093d8000-09fda000 rw-p 00000000 00:00 0                                  [heap]
> f1639000-f163a000 rw-p 00000000 00:00 0 
> f163a000-f1640000 r-xp 00000000 08:03 526924                             /usr/lib/i386-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so
> f1640000-f1641000 r--p 00005000 08:03 526924                             /usr/lib/i386-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so
> f1641000-f1642000 rw-p 00006000 08:03 526924                             /usr/lib/i386-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so
> f1642000-f1647000 r--p 00000000 08:03 1186681                            /usr/share/icons/hicolor/icon-theme.cache
> ...
> Fatal error 6: Aborted

## System Details:
  - Sly version: SLY 1.0.0-beta-2
  - Emacs version: 25.1.x
  - Company version: 2019.11.06.2247 from MELPA
  - Operating System: Linux

**Comment by joaotavora** [comment]
Thanks for the report,

This is an Emacs bug, fixed in 26.2 or 26.3, if I'm not mistaken.

You must either upgrade to one of those versions or give up using company
and Sly together.

Sorry,
João

**Comment by bymoz089** [comment]
Thanks for the fast response and provided solution., I thought it has to do with Sly, because it never happened before. Sorry for the noise.

**Comment by joaotavora** [comment]
I thought so too, for a long time.  I wish I had had your reproduction recipe and backtrace some 1 year ago.  Eventually I got there.
