### ISSUE TITLE
Optionally disable sticker's before and after breaking

### ISSUE THREAD

**Issue by arichiardi** [joaotavora/sly#281]
Hi there, I have been dabbling my feet with `sly` and CL and I am trying the sticker feature.

I am wondering if I am missing something, but it seems that the before and after feature convey the necessary information and, if not, they can be disabled.

From what I understand the workflow would be to break at a sticker to analyze its result, and to break on a "before" sticker to analyze the inputs.

However I cannot see the inputs in the "before" sticker for instance.

Yes well, maybe I am missing something indeed. If the above statement is true, can I disable them? They are quite numerous especially while arming many forms at the time :smile:

Thanks and sorry for my newbity!

**Comment by joaotavora** [comment]
> I am wondering if I am missing something, but it seems that the before and after feature convey the necessary information and, if not, they can be disabled.

You are using "breaking stickers", right? If so, it does make sense to selectively enable breaking before/breaking after, or not at all.

> However I cannot see the inputs in the "before" sticker for instance.

This is a bug, I think.  Or rather, I just forgot to implement that.

I will see what I can do.

**Comment by joaotavora** [comment]
> > However I cannot see the inputs in the "before" sticker for instance.
> This is a bug, I think. Or rather, I just forgot to implement that.

Doh.  I didn't forget to implement it.  It just doesn't make sense.  A sticker is an annotation of an evaluated expression, it does not have "input" like a trace entry.

So I will just do the first part.

**Comment by arichiardi** [comment]
> You are using "breaking stickers", right?

Yep

> I will see what I can do.

Thank you and thank you, was not sure I had the clear picture in front of me :smile:

**Comment by arichiardi** [comment]
Awesome thanks!
