### ISSUE TITLE
[sly] REPL is busy (then gets stuck forever)

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#283]
When interacting with the REPL (e.g. loading a system, then entering an expression at the prompt and pressing RET) I frequently get the message

```
[sly] REPL is busy 
```
after which nothing happens, and the REPL seems to be stuck forever.

I'm not quite sure how to invertigate from there.

Is it possible to interrupt whatever keeps the REPL busy? (`sly-interrupt` does not work.)

I'm using Sly commit 0a3b817.

**Comment by joaotavora** [comment]
> Is it possible to interrupt whatever keeps the REPL busy? (sly-interrupt does not work.)

Hmm. It should though.  What implementation are you using?  Can you provide an `Emacs -Q` recipe that demonstrates the problem?  Heres a template for doing that: https://github.com/joaotavora/sly/blob/master/CONTRIBUTING.md#reporting-bugs

**Comment by Ambrevar** [comment]
Sorry for the late response.  I believe the issue is with CFFI and the
main thread blocking somehow.
Probably not related to SLY, so I'm closing this.
