### ISSUE TITLE
Feature Suggestion: sticker faces

### ISSUE THREAD

**Issue by tttuuu888** [joaotavora/sly#285]
First of all, thanks a lot for this great package.

I have a suggestion for sticker function.
(or maybe I didn't find a way to set this)

It would be nice if I can set current sticker FACE.
I can still find the position with a cursor and a flash but different FACE setting would be definitely helpful.

And, now the current sticker flashes twice within about 3 seconds. 
But if I move to next sticker in a second, the previous sticker still flash after about 2 seconds, which is a little bit confusing. 
I think the second flash should be canceled in this case. Or it would okay if it just flash twice without interval.

In case of I'm missing something, I would appreciate for pointing it out.

Thanks.

**Comment by joaotavora** [comment]
> But if I move to next sticker in a second, the previous sticker still flash after about 2 seconds, which is a little bit confusing.

Yeah, I've been tweaking this lately.  Maybe I shouldn't have.  I'll have a look.  Be sure to be on the very latest version though, because I've tweaked it more than once.

**Comment by joaotavora** [comment]
So the "interleaved flashing of stickers" (#286) problem is solved.  I supposed this leaves the rest of your report as a feature suggestion.

**Comment by tttuuu888** [comment]
@joaotavora Thank you for quick feedback and update. 
I just updated sly and it works great!
Thanks a lot.

**Comment by joaotavora** [comment]
Regarding sticker and faces, there are already  some faces:

```lisp
(defface sly-stickers-placed-face
  '((((background dark)) (:background "light grey" :foreground "black"))
    (t (:background "light grey")))
  "Face for sticker just set")

(defface sly-stickers-armed-face
  '((t (:strike-through nil :inherit hi-blue)))
  "Face for stickers that have been armed")

(defface sly-stickers-recordings-face
  '((t (:strike-through nil :inherit hi-green)))
  "Face for stickers that have new recordings")

(defface sly-stickers-empty-face
  '((t (:strike-through nil :inherit hi-pink)))
  "Face for stickers that have no recordings.")

(defface sly-stickers-exited-non-locally-face
  '((t (:strike-through t :inherit sly-stickers-empty-face)))
  "Face for stickers that have exited non-locally.")
```

However, be careful customizing them, because they only make sense with certain attributes: because stickers are nested, faces without the `:background-color` attribute don't make any sense.

If you mean the face used for temporarily highlighting the stickers when you're replaying or breaking on them, I think you want to customize the `highlight` face.

**Comment by tttuuu888** [comment]
Thank you for further explanation.

Since now flashing works fine, I found I'm not confused anymore.
And I also found 'v' to flash the current sticker again is also very useful.
So I think now it's good as it is and this issue could be closed.

Thanks.

**Comment by joaotavora** [comment]
OK!
