### ISSUE TITLE
Sly's fancy inspector confused by errors in a STANDARD-CLASS's PRINT-OBJECT method

### ISSUE THREAD

**Issue by pouar** [joaotavora/sly#287]
test case after writing this code then trying to inspect the class
```
; Cleared REPL history
CL-USER> (defclass test () ((a :initform :a :accessor a)))
#<STANDARD-CLASS COMMON-LISP-USER::TEST>
CL-USER> (defmethod print-object ((obj test) stream)
           (print-unreadable-object (obj stream :type t :identity t)
             (write (a obj) :stream stream)))
#<STANDARD-METHOD COMMON-LISP:PRINT-OBJECT (TEST T) {100CB2BCA3}>
CL-USER> (sb-mop:finalize-inheritance (find-class 'test))
NIL
CL-USER> (find-class 'test)
#<STANDARD-CLASS COMMON-LISP-USER::TEST>
#<TEST <<error printing object>> {10085E5F53}>#<TEST <<error printing object>> {10085E5F53}>
CL-USER> 
```

**Comment by pouar** [comment]
works fine in SLIME

**Comment by joaotavora** [comment]
Indeed, this is quite the bug.  It's breaking around the time when it's trying to print the "Prototype" object, whatever that is.

**Comment by pouar** [comment]
http://metamodular.com/CLOS-MOP/class-prototype.html

**Comment by pouar** [comment]
in SBCL, it creates an uninitialized instance

**Comment by pouar** [comment]
using allocate-instance

**Comment by joaotavora** [comment]
Yes, this works perfectly fine in allegro

**Comment by joaotavora** [comment]
FTR, even if it did have perfectly bound slots your r`write` funcall is garbled.  `stream` is a keyword arg. I've edited your recipe.

**Comment by joaotavora** [comment]
Whew! that was a tough one, can you test?

**Comment by pouar** [comment]
seems to work, thanks
