### ISSUE TITLE
Minus sign - variable is always NIL in sly (current prompt variable).

### ISSUE THREAD

**Issue by equwal** [joaotavora/sly#288]
The minus sign should work in the way described [here in CLtL2](https://www.cs.cmu.edu/Groups/AI/html/cltl/clm/node181.html#SECTION002420000000000000000), or [in the hyperspec](http://www.lispworks.com/documentation/HyperSpec/Body/v__.htm). In sly, it is always `NIL`.

Examples:
```common-lisp
;;; Expected
> -
-
>
;;; Actual
> -
NIL
> 
;;; Expected
> (cons - -)
((CONS - -) CONS - -) ;Cute, huh?
;;; Actual
> (cons - -)
(NIL . NIL)
```

I'm told that SLIME works okay ([irc log on this](https://irclog.whitequark.org/lisp/2019-12-10)).

Here is a function that does maintain `-`.
```common-lisp
(slynk::eval-region "-")
```

**Comment by equwal** [comment]
I suggest reopening, since running the elisp:
```emacs-lisp
(sly-interactive-eval "-") => NIL
```
is broken still.

**Comment by joaotavora** [comment]
I don't agree.  `sly-interactive-eval` has nothing to do with the REPL.  Why do think it does?

**Comment by equwal** [comment]
> I don't agree. `sly-interactive-eval` has nothing to do with the REPL. Why do think it does?

Indeed, I should have been focused on `sly-eval-last-expression`, which is also not working.

So running a form in a lisp file with `C-x C-e` that has `-` in it will have `-` as `NIL`.

**Comment by joaotavora** [comment]
> So running a form in a lisp file with C-x C-e that has - in it will have - as NIL.

Yes. That's the way it should work. As far as I read from the hyperspec, `-` should only have meaning in a REPL.

**Comment by equwal** [comment]
> As far as I read from the hyperspec, `-` should only have meaning in a REPL.

>  The value of - is the form that is currently being evaluated by the Lisp read-eval-print loop. 

I agree with you
