### ISSUE TITLE
Strange behavior with debugger/REPL

### ISSUE THREAD

**Issue by mfiano** [joaotavora/sly#294]
This has been an ongoing issue for me for about 6 months now, but only now reporting it. The problem is hard to reproduce, as it only occurs about once per day after using Emacs for a good 12 hours. The problem is, *sometimes* when attempting to exit the debugger, the window does not close, and Emacs is "busy", until I either `C-g` or click on another window, at which point the actual closing of the window happens, but it inserts a series of 4 semi-colons separated by spaces into the mrepl: `;  ;  ;  ;`. I have no idea what could be causing this, or if it's my config or not, as bisecting such a rare issue is impractical with my extensive configuration. I am hoping these symptoms give someone an idea of what could be happening so I can limit it down a bit. Thanks.

**Comment by equwal** [comment]
The above commit was mis-labeled.

**Comment by equwal** [comment]
Can you turn on a profiler and try to find the function that runs when this happens? It is probably a problem with your configuration.

**Comment by joaotavora** [comment]
I don't think a "profiler" is the answer, but maybe you mean setting `debug-on-quit` to `t`, so the user gets a backtrace when pressing that `C-g`.

Some questions:

1, what "debugger" are you talking about? Is it SLY's or Emacs's?  

2. can it be that after 12 hours your Lisp is responding slowly to SLY's synchronous requests?  Maybe because it is global-GC'ing.

3. Is the REPL unusable after the four consecutive `;`?

**Comment by mfiano** [comment]
I could, though I don't know what effect the instrumentation might have after possibly many hours between occurrences. I am a bit unfamiliar with profiling this sort of thing though. I am only hesitant because I just don't want to leak RAM and lose my work (and pay).

**Comment by mfiano** [comment]
@joaotavora It would be sly-db

**Comment by mfiano** [comment]
The REPL is still usable. I can remove the semi colons and continue on

**Comment by mfiano** [comment]
Also I had it happen today and it's not always a literal `; ; ; ;`, though that is the most common thing inserted into the REPL. Sometimes there are more than 1 space between semi-colons. Earlier today it inserted this into the REPL: `  ;                     ;                     ;                     ;`

**Comment by equwal** [comment]
> I don't think a "profiler" is the answer, but maybe you mean setting `debug-on-quit` to `t`, so the user gets a backtrace when pressing that `C-g`.

Specifically you want a profiler that shows what functions are called when, rather than something like a statistical profiler.

**Comment by joaotavora** [comment]
> Specifically you want a profiler that shows what functions are called when, rather than something like a statistical profiler.

So @mfiano should just log every emacs lisp function call for 12 hours straight?

That doesn't sound like a "profiler" to me, rather  a "trace every function". And it doesn't sound like a good bug-hunting strategy, but that's just my opinion.

**Comment by mfiano** [comment]
@joaotavora Ok I found a way to easily reproduce it. In my current application I have it `(error "foo")` after a random number of seconds. I just got it to occur after about 20 times. Sadly, `C-g` did not invoke the debugger with `debug-on-error` set t `t`.

**Comment by joaotavora** [comment]
It's `debug-on-quit`.

**Comment by mfiano** [comment]
Oops, retesting.

**Comment by mfiano** [comment]
Ok, it's starting to make sense to me. I got a debugger with information about evil-mode attempting to record a macro, which shares the `q` binding that sly-db-mode also has for quitting. I think it might be some kind of race condition or something :thinking:

**Comment by equwal** [comment]
> Ok, it's starting to make sense to me. I got a debugger with information about evil-mode attempting to record a macro, which shares the `q` binding that sly-db-mode also has for quitting. I think it might be some kind of race condition or something thinking

Not sure how helpful this might be:
`(add-hook 'sly-db-hook 'evil-emacs-state)`

**Comment by mfiano** [comment]
Thanks for the help. I just set `(evil-set-initial-state 'sly-db-mode 'motion)` and redefined all my custom mode mappings to use motion state instead. I am going to consider this issue solved for now. Thanks!

**Comment by equwal** [comment]
> Thanks for the help. I just set `(evil-set-initial-state 'sly-db-mode 'motion)` and redefined all my custom mode mappings to use motion state instead. I am going to consider this issue solved for now. Thanks!

I'd appreciate seeing that code, maybe putting it on `gist.github.com`.

**Comment by mfiano** [comment]
@equwal https://github.com/mfiano/dotfiles/blob/master/dot_emacs.d/config/packages.el#L769

**Comment by mfiano** [comment]
I haven't pushed yet, but i just changed `n` to `m` and modified L756

**Comment by mfiano** [comment]
@equwal While I archived it and no longer maintain it, people say my mfiano/common-lisp-sly layer works great.

**Comment by equwal** [comment]
> @equwal While I archived it and no longer maintain it, people say my mfiano/common-lisp-sly layer works great.

Thanks, I hadn't seen that (https://github.com/mfiano/common-lisp-sly) yet. I see a couple forks with fixes in them.

> I haven't pushed yet, but i just changed `n` to `m` and modified L756

https://github.com/mfiano/dotfiles/blob/master/dot_emacs.d/config/packages.el#L756

**Comment by mfiano** [comment]
I was told the init error is no longer an issue, and the fork with a "fix" for that is simply wrong. `sly` is not a layer, it's a package, and the author didn't know what they were doing there. Regardless, I prefer to roll my own Emacs config, and don't have a Spacemacs install handy anymore to maintain that. So if you find any issues, you're on your own unfortunately.
