### ISSUE TITLE
Document or explain here how to disable the new mrepl completion menu

### ISSUE THREAD

**Issue by mfiano** [joaotavora/sly#295]
I haven't updated Sly in a good 6 months, but did so this week in an unsuccessful attempt to solve #294. In doing so, I noticed that the comma ido menu in the mrepl now uses ivy for completion with my existing config unaltered, and it has a few issues. I do like ivy everywhere else, but because of the issues, I would like to learn how to go back to ido completion.

As a side note, the issue is, if I were to say issue `,res` to highlight the `restart lisp` option and hit return, it restarts it, however, upon pressing `,` again to bring up the menu, I now have a `res` option available to select, and i can no longer abbreviate it or an error about a non-existent command is shown. At the end of the day I have a few abbreviated non-commands appearing as candidates, and it makes issuing REPL commands slow and error-prone.

**Comment by joaotavora** [comment]
@mfiano, I believe you might be seeing this the other way around.  I mean, I simplified SLY so that it would work with whichever completion framework the user has globally applied to his Emacs. In your case it's Ivy.  But Ivy apparently has trouble flex-matching or substring-matching.  

I suggest you:
1. Ask the Ivy developer to fix those bugs
2. Ditch Ivy, compile an Emacs from master, and turn on `fido-mode` (then report bugs to Emacs bug tracker).
3. "mode"-locally set `completing-read-function` to `ido-completing-read` in the REPL buffers, by using `sly-mrepl-mode-hook`.  Haven't tried it but it should work.

**Comment by equwal** [comment]
> @mfiano, I believe you might be seeing this the other way around. I mean, I simplified SLY so that it would work with whichever completion framework the user has globally applied to his Emacs. In your case it's Ivy. But Ivy apparently has trouble flex-matching or substring-matching.
> 
> I suggest you:
> 
>     1. Ask the Ivy developer to fix those bugs
> 
>     2. Ditch Ivy, compile an Emacs from master, and turn on `fido-mode` (then report bugs to Emacs bug tracker).
> 
>     3. "mode"-locally set `completing-read-function` to `ido-completing-read` in the REPL buffers, by using `sly-mrepl-mode-hook`.  Haven't tried it but it should work.

Actually, it is a bug in sly (not ivy) though ivy might be the only one that behaves badly when given bogus arguments.

I was able to fix the issue in #296, and opted to instead include the previous completion in the prompt when called twice.

**Comment by equwal** [comment]
This issue can probably be closed, since the fix is here: https://github.com/abo-abo/swiper/pull/2367

**Comment by equwal** [comment]
> I would like to learn how to go back to ido completion.

Need to change completing-read function when `sly-mrepl-shortcut` is run, then reset it to what is was afterward
`(setq completing-read-function 'ido-completing-read) ;Setting to NIL also works.`

**Comment by joaotavora** [comment]
This is very confusing @equwal .  First you say there's a bug in Sly, which is giving `completing-read-function`s bogus arguments, but only Ivy behaves badly.  Then you say this can be closed.

Which is it? We need to slow down, I think.

**Comment by equwal** [comment]
> This is very confusing @equwal . First you say there's a bug in Sly, which is giving `completing-read-function`s bogus arguments, but only Ivy behaves badly. Then you say this can be closed.
> 
> Which is it? We need to slow down, I think.

My mistake.
- I was wrong, there is not a bug in sly. The bug is definitely in ivy, and the pull request there fixes the problem.
- The pull request here merely worked around the problem with ivy, but will be obsoleted by my pull request there (https://github.com/abo-abo/swiper/pull/2367).

**Comment by mfiano** [comment]
Thanks to you both for looking into this issue! I am glad a fix is in the pipeline. Now if anyone can help me narrow down #294 I'd be bug free in my daily workflow :)

**Comment by mfiano** [comment]
The PR was merged into swiper, and unfortunately, the issue still remains.

**Comment by joaotavora** [comment]
@mfiano, I don't know what swiper is, and I don't have time to try it. Can you explain the bug in terms of swiperless behavior?  Use tools in Emacs, bleeding edge Emacs 27 if you want.

**Comment by mfiano** [comment]
Swiper is the project where the ivy completion system lives. The issue is that when using the comma commands in sly-mrepl, if I type part of a command to complete to it, execute it, and then invoke the comma menu again, i have the partially completed command from last time in the list of candidates, and selecting it errors because it's not a command. For the time being I have reverted to `ido-completing-read` until it is resolved.

**Comment by mfiano** [comment]
Update: This is not an issue with ivy. I am experiencing the same issue with ido completion. My configuration hasn't changed, and this only started occuring after a package update, so I'm suspecting Sly at the moment until I can dig deeper.

**Comment by joaotavora** [comment]
Well, I can't know from this description where the problem in SLY is.  SLY works OK with bare  `Emacs -Q` and `Emacs -Q` + `icomplete-mode`, for example. According to reports, it also works with `Helm`, and I believe a co-worker of mine uses `Ivy` (not sure if same as swiper), but maybe he doesn't hit that problem so often.

**Comment by joaotavora** [comment]
@mfiano, be sure to provide an idiot-proof reproduction recipe from `Emacs -Q`!

**Comment by mfiano** [comment]
I'm trying. One thing I noticed is the partial candidates persist across Emacs restarts. I'm checking any cached files at the moment.

**Comment by joaotavora** [comment]
> One thing I noticed is the partial candidates persist across Emacs restarts.

`Emacs -Q` restarts, too?

**Comment by mfiano** [comment]
So with ido completion active, I tried executing one of the partial candidates and got an error, but now it's removed from the comma menu, and I cannot get it to come back. So however Sly is generating this list of commands might be not regenerating it and using some cached copy that persisted from when using ivy.

**Comment by joaotavora** [comment]
If possible, try to avoid the package system, too. Use a git checkout of Sly, if you can.

**Comment by mfiano** [comment]
All my packages are using git. I do not use package.el at all.

**Comment by joaotavora** [comment]
> So however Sly is generating this list of commands might be not regenerating it and using some cached copy that persisted from when using ivy.

Most likely ivy is storing an invalid entry into the history.  And once it's in the history, if messes it up for other completions systems.  But this is just a guess.

So If I gather correctly you _cannot_ reproduce it from `emacs -Q`, right?

**Comment by mfiano** [comment]
I haven't tried, but I *cannot* reproduce it *without* `emacs -Q` now that the partial candidate has been removed upon attempting to execute it while using ido.

**Comment by joaotavora** [comment]
> I haven't tried, but I cannot reproduce it without emacs -Q

Talk about multiple negation.  I can't understand this.

**Comment by mfiano** [comment]
So issue is ivy's fault I guess. Persistent issue with ido was due to some history caching probably. I think we can close this. Just be aware sly-mrepl/ivy are not a good combination right now, probably at no fault of Sly's.

**Comment by mfiano** [comment]
I'm sorry if that was confusing. I just meant I did not try Emacs -Q because I can't reproduce it with my custom config. It was only an issue until I actually tried executing one of the partial candidates, at which point the invalid entries were permanently removed.

**Comment by joaotavora** [comment]
OK.  I think I understand. Well be sure to show this to Ivy's developer so we can have his opinion.

**Comment by equwal** [comment]
https://github.com/abo-abo/swiper/issues/2369

**Comment by joaotavora** [comment]
> I think this issue may show his view:
abo-abo/swiper#2369

Well, it doesn't make sense to me. The way @abo-abo wants the rewrite the code doesn't produce the same effect, i.e. that the most recent chosen completion be the default for the next completion.  Now, I have no idea what Ivy does, but it seems to record an incomplete completion into the history variable, which is bizarre, or at least unlike what Emacs's own completion mechanism do. So, ¯\_(ツ)_/¯
