### ISSUE TITLE
",test-system" comma-command?

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#305]
I could be missing something, but SLIME has a `,test-system` comma-command and it seems that SLY does not.
Is there a good reason for this?  How do you people test systems with SLY?

**Comment by joaotavora** [comment]
What's "testing a system"?  In the ASDF-sense, it is something that I, personally, avoid.  I avoid every ASDF feature except the most basic ones.

Anyway, one possible reason you are seeing that in SLIME might be having the `slime-asdf` contrib installed.  I don't know if a `sly-asdf` contrib exists, but one could be created, and that contrib would add the `test-system` comma command.  Until such a thing exists, check the ASDF manual (if you can somehow read it :laughing:  ) how to test a system from a command in the REPL.

**Comment by Ambrevar** [comment]
Testing a system with ASDF is trivial:

```
(asdf:test-system :foo)
```

The benefit of the comma-version of the command is that we get automatic
completion from Emacs.

sly-asdf exists but it does not provide `,test-system`.

**Comment by mmgeorge** [comment]
@Ambrevar, I was planning on adding this to `sly-asdf` (https://github.com/mmgeorge/sly-asdf/issues/13) just been dragging my feet a bit. Should be simple, I can take a look tomorrow

**Comment by joaotavora** [comment]
> The benefit of the comma-version of the command is that we get automatic
completion from Emacs.

@Ambrevar That's true, but then you already have: 

* automatic completion from the SLY REPL for every lisp symbol;
* `C-r` reverse i-search in the REPL

so maybe that's why I don't miss these kinds features so much.

**Comment by Ambrevar** [comment]
@joaotavora The completion on `(asdf:test-system |)` (with | being the
point) is not very useful :p

@mmgeorge That'd be great, thanks!

**Comment by joaotavora** [comment]
> The completion on `(asdf:test-system |)` (with | being the
point) is not very useful :p

Oh, so you want to complete on "testable systems" only. Well then you do need a special command for that. Sure, I agree it's better. The way you could avoid that is if they were symbols in a specific "testable systems" package (which would be the way I would design the system). Anyway, good luck!
