### ISSUE TITLE
Sly REPL doesn't take well to torture

### ISSUE THREAD

**Issue by Kazimazi** [joaotavora/sly#313]
When I make a looping read-line in sly after a few iterations (by holding down the enter key) starts hanging with the message `[sly] REPL is busy`.
The lisp code I ran in sly repl:
```
(defun repl-loop ()
  (princ "blabla")
  (fresh-line)
  (read-line)
  (repl-loop))
(repl-loop)
```
The issue didn't occur when I ran sbcl in a terminal.
My setup:
```
$ emacs --version
GNU Emacs 28.0.50

$ sbcl --version
SBCL 1.5.6.nixos
```
Please tell if I could provide more information on the topic.

**Comment by joaotavora** [comment]
Well, I make a REPL really as the name says it should be done:

```
(loop (print (eval (read))))
```

works fine.  By the way your function isn't a REPL: there's no `eval` in there.  And `READ-LINE`  isn't `READ`.  And I can't reproduce your problem, even if I hold down enter for a long time.

That said, remember that in SBCL's prompt you're talking directly to the process via stdin/stdout, wheras is SLY's case you're going quite a complicated route.  I took great efforts to make that route _look_ like you're talking with stdin/stdout, but it's not, so if you abuse it with holding down enter, it might break down.

**Comment by Kazimazi** [comment]
Yeah, right it's rather a read line loop. Anyway, I did some more torture to sly, when I'm holding enter in an empty line it works fine for me too, the hanging issue happens after (read).
Here is [video](https://streamable.com/4i9drq).
I'm not sure if I'm just seeing things into it, but my cave man debugging method tells that 2 consecutive `[sly] Listener waiting for input to read` in the messages causes the hang every time.

**Comment by joaotavora** [comment]
No, you're probably not seeing stuff into it, there does appear to be some desynch there, it wouldn't surprise me.  There are other mysterious issues with networking code in Emacs.  If you can debug it and/or try to reproduce it with Emacs 27 and Emacs 26.3 it'd be great.  Otherwise I'll keep it open with a low priority.

**Comment by Kazimazi** [comment]
Same happens with Emacs 26.3.

**Comment by joaotavora** [comment]
I've been reproducing this now and again, and I've come up with a half-decent workaround which is to "clear the REPL". Use `M-x sly-mrepl-clear-repl` or just the comma shortcut and select "clear REPL".  For the latter to work, you might have to move your point (the cursor) out of the place where SLY expects you to type things to read.  This isn't ideal as you lose your previous input, but at least you get your REPL back.

**Comment by joaotavora** [comment]
> This isn't ideal as you lose your previous input, but at least you get your REPL back.

Making a new repl with `M-x sly-mrepl-new` would probably also work.

**Comment by joaotavora** [comment]
OK.  the easiest way to reproduce this is just to type `(read)` and then hold down enter.

**Comment by joaotavora** [comment]
I now know exactly where the problem is:  it's the `(sly-mrepl--accept-process-output)` line in 
```lisp
(sly-define-channel-method listener :set-read-mode (mode)
  (with-current-buffer (sly-channel-get self 'buffer)
    (sly-mrepl--accept-process-output)
    (let ((inhibit-read-only t))
      (cl-ecase mode
```
in `contrib/sly-mrepl.el`.  That line is designed to let output come in just before we set a flag making the repl go into the protected "read mode".  But since it eventually calls `accept-process-output` this can sometime slead to another recursive call to the channel method, which will confuse the order of the flag setting, leaving it in an invalid state.

This diff will fix it, but it will introduce formatting problems, too:
```diff
diff --git a/contrib/sly-mrepl.el b/contrib/sly-mrepl.el
index f44443a7..7f51db3b 100644
--- a/contrib/sly-mrepl.el
+++ b/contrib/sly-mrepl.el
@@ -214,21 +214,20 @@ for output printed to the REPL (not for evaluation results)")
 
 (sly-define-channel-method listener :set-read-mode (mode)
   (with-current-buffer (sly-channel-get self 'buffer)
-    (sly-mrepl--accept-process-output)
     (let ((inhibit-read-only t))
       (cl-ecase mode
-        (:read (setq sly-mrepl--read-mark (point))
-               (add-text-properties (1- (point)) (point)
-                                    `(rear-nonsticky t))
-               (sly-message "Listener waiting for input to read"))
+        (:read
+         (sly-mrepl--accept-process-output)
+         (setq sly-mrepl--read-mark (point))
+         (add-text-properties (1- (point)) (point)
+                              `(rear-nonsticky t))
+         (sly-message "Listener waiting for input to read"))
         (:finished-reading
          (if sly-mrepl--read-mark
              (add-text-properties (1- sly-mrepl--read-mark) (point)
                                   `(face bold read-only t))
            (sly-warning "Expected `sly-mrepl--read-mark' to be set!"))
          (setq sly-mrepl--read-mark nil)
-         (when sly-mrepl--pending-output
-           (sly-mrepl--insert-output "\n"))
          (sly-message "Listener waiting for sexps to eval"))))))
 
 (sly-define-channel-method listener :prompt (package prompt
```
