### ISSUE TITLE
sly-apropos-all example in manual doesn't work

### ISSUE THREAD

**Issue by gcentauri** [joaotavora/sly#314]
Hello! Thanks for making such a cool package! I'm excited to learn more about it and Common Lisp.

I was working through the manual and in section 3, there's an example for using `sly-apropos-all` to look up the flex completions functions. it says you can just type "slyflex" and hit enter, but when I do that I get "No apropos matches for 'slyflex'".

it also seems like some of the functions have changed since the info was written. i'd be happy to contribute a pr to update the documentation, but someone more familiar with it might do a better job :)

thanks again!

**Comment by joaotavora** [comment]
Indeed the documentation wrong on this bit.  There was briefly an apropos matcher that was "flexy" itself (meaning you could match `foobar` just by typing `fb`.  It never worked super-well, so I reverted back to the regexp matcher, so now you have to type `f.*b` to get `foobar.  However, the documentation wasn't update).  So I'd really appreciate a docfix, or even better examples, or better phrasing for examples.  Every time I re-read stuff there I get feel embarassed about something incomprehensible I wrote.

Another way to fix this is to bring back that flex apropos matcher. I don't remember what the problems were anymore.

**Comment by gcentauri** [comment]
Well since I'm reading through the manual I'm happy to help. I assume there is one "source" document that the different documentation files are built from? is it the `sly.texi` file? now that i'm looking at the Makefile it seems like the answer is yes :)

**Comment by joaotavora** [comment]
yes, it is  `sly.texi`

**Comment by joaotavora** [comment]
This is fixed now.  Thanks!
