### ISSUE TITLE
Image links for info docs are broken

### ISSUE THREAD

**Issue by gcentauri** [joaotavora/sly#316]
I noticed when trying to read the docs in info that the image links were broken. I thought it might be an issue with the package manager I'm using `straight.el` but when I reported it there https://github.com/raxod502/straight.el/issues/514 the maintainer hinted that its probably the MELPA recipe.

I'm pretty new to elisp packaging, but another task I'd be happy to try and resolve. I'll see what I can find out when I get time :)

**Comment by joaotavora** [comment]
To read the docs in `info`, you must be using a github clone of SLY.  It _should_ work if your info browser (such as the one in Emacs) supports images.  If you can somehow make it work for the MELPA recipe, that's great, too.

**Comment by gcentauri** [comment]
`straight.el` does make a github clone. i'm not sure how it works exactly, but it clones the package and then extracts it to a build directory for use with Emacs. all i had to do to make it work was copy over the images directory, so it seems like it should be possible. I'll dig into it. the maintainer of `straight.el` seems to have seen this before, so I'm guessing it should be possible. its a minor bug, but i thought i may as well track it as i'm going through the docs.

**Comment by joaotavora** [comment]
Let me just state that I've had problems with `straight.el` related installation before.  It seems to forego the `package.el` system completely (or did so).  Anyway, I don't know it, and I don't "support" it.  I only support `package.el` (which is used by MELPA and GNU Elpa) and git installations.

So this "bug" is only, as far as I know, related to MELPA packaging (because SLY is _only_ in MELPA).

**Comment by gcentauri** [comment]
Ok, that is good to know. It does forego `package.el` completely. Technically `straight.el` does a git installation, utilizing the MELPA recipe afaik. I will test against a normal install with MELPA and `package.el` to see if it is possible to get the info docs working. I'm pretty new to `straight.el` as well, but one thing I like about it is how it handles installing info docs for elisp packages.

**Comment by joaotavora** [comment]
> I like about it is how it handles installing info docs for elisp packages.

Well, it does seem to have messed up here (maybe).

For the record, I don't use `package.el` a lot  I git download foo to a `~/Source/Emacs/<foo>` and every subdir under `~/Source/Emacs` is in `load-path`.  Then I require `foo` or `foo-autoloads` if it exists.  If a package has a lot of non-GNU dependencies, that's usually a bad sign for me and I tend to stay away from those, or use `package.el`.  If I remember correctly `straight.el` was so straight that it ignored some dependencies of another project I maintain `http://github.com/joaotavora/eglot`

**Comment by gcentauri** [comment]
:) okay. this is something that is very easy to handle myself, so its fine it you want to ignore it. in this case i think the issue with `straight.el` is that it builds the package into a `build/sly` directory that is put in the load path (rather than the repo directory) using the MELPA recipe, which does not include `docs/images`. perhaps it is not appropriate to include that in the MELPA recipe, I'm not sure.

**Comment by joaotavora** [comment]
> perhaps it is not appropriate to include that in the MELPA recipe,

Yes, I think it goes against (reasonable) MELPA policy.  But if you want to ask on my behalf, I don't mind :-)  I don't have a lot of time do initiate this dialogue now. 

I'm closing this issue.  If you think I should reopen it, please do tell.

**Comment by gcentauri** [comment]
Nope, thank you for your time. I would rather be helpful than create unnecessary work. I can ask on MELPA if it is reasonable or not, I have recently started maintaining an elisp package so the more I know the better.

Thanks again for SLY!

**Comment by raxod502** [comment]
@joaotavora Yes, although you are correct that `straight.el` does things differently than `package.el`, the _packaging format_ is actually completely compatible. The behavior when installing with `straight.el` is much more similar to installing with `package.el` than it is to installing manually from the Git repo (although the _development experience_ is the same as installing from the Git repo). When I received the bug report against `straight.el`, the first thing I did was install SLY using `package.el` -- and the images are also broken there.

The way to fix this would be to add the images to the MELPA recipe, but as you said that may or may not be considered acceptable. I didn't find any policy discussions from a quick search of the issue tracker.

**Comment by joaotavora** [comment]
@raxod502 I don't remember saying that `straight.el` was responsible for this issue and I never encouraged the reporter to open an issue there.  I was merely replying to this:

> Technically straight.el does a git installation

So if _that_ was true, if it _did_ do a git installation, then it would have failed, because the git installation doesn't have this problem. If you say it's not true, that's great. 

Now, [one](https://github.com/joaotavora/eglot/issues/28) or [two](https://github.com/joaotavora/eglot/issues/231) reports  lead me to believe `straight.el` ignores GNU Elpa dependencies, a violation of the `package.el` premise.  Is that really true? I don't know, I never tried it first hand, I admit. If it is, you should fix it because such reports are a waste of other dev's time. If you have already or it's not true, then great! I'm just saying I don't support it (as I don't support `use-package`).  I want to support only Emacs, don't have time for more.

**Comment by raxod502** [comment]
> Is that really true?

The first bug report you linked was closed in mid 2018. The second one was never reported to me, but I just checked and Flymake is cloned as a dependency when you install eglot.

Obviously `straight.el` does not ignore dependencies. It would not be much use as a package manager if it did.

> I don't support it

You shouldn't _have_ to support it explicitly, as the behavior of packages should not change depending on what package manager is used to install them. But, as always, patience and charitability are appreciated.

Anyway, thanks for your thoughts :)

**Comment by joaotavora** [comment]
> The first bug report you linked was closed in mid 2018. The second one was never reported to me,

Ah great, so it was a bug and you fixed it.  Great.  I think the second one was basically the same, as Flymake is another :core: package.

> You shouldn't have to support it explicitly, as the behavior of packages should not change depending on what package manager is used to install them. 

I agree.  But people come to me with "I used `straight.el`" and that by itself brings _Fear Uncertainty Doubt_.  It will bring a bit less though.

>  It would not be much use as a package manager if it did.

My thoughts exactly! Actually I think I like the concept of `straight.el`, maybe I'll try it some day. It's just that that bug reaaally scared me away from it :-)

> But, as always, patience and charitability are appreciated.

You're right.  Sorry if I sometimes have little of those to spare.

**Comment by gcentauri** [comment]
FWIW - I did open another issue on MELPA to ask about including the required files for the Info docs plus images https://github.com/melpa/melpa/issues/6870

I appreciate both of your time and effort creating excellent packages for the greatest editor. I'm hoping opening issues doesn't add to the burden of being a free software maintainer. This one was so minor and easily solved manually on my own, so I apologize if it caused any stress. Take care, both of you!

**Comment by raxod502** [comment]
@joaotavora 

> that by itself brings _Fear Uncertainty Doubt_. It will bring a bit less though.

Glad to hear it!

> Actually I think I like the concept of `straight.el`

:heart: 

> Sorry if I sometimes have little of those to spare.

No worries, thanks for being helpful!

---

Anyways, https://github.com/melpa/melpa/pull/6879 should fix the problem for not only `package.el` but also `straight.el` :)
