### ISSUE TITLE
REPL randomly being marked read-only during line input

### ISSUE THREAD

**Issue by HarryHenryGebel** [joaotavora/sly#319]
I don't have much recent (last 20 years) experience in Emacs, so I'm not sure how all the parts of SLY and Emacs fit together and don't know exactly how to explain this correctly but I will do my best, sorry. I am using SLY and SBCL on Manjaro Linux using the standard SBCL and Emacs packages from the distribution and SLY installed with package-install from Melpa.

I'm working my way through _Practical Common Lisp_. In chapter 3 it is going over line input amongst other things involved in making a simple CD database. While collecting various inputs using the `read-line` function the mrepl buffer occasionally stops accepting input, whenever I press a key the terminal beeps and the message 'Text is read-only' appears in the echo area. The only way to make the mrepl responsive again is to type 'Ctrl-C Ctrl-C', after which the (?SBCL or SLY? not the Emacs debugger in any case) debugger comes up and I can quit the debugger and resume work in the mrepl with the function having been aborted.

I have tried looking through all of Emacs's various buffers and I cannot see any error messages or warnings in any of them while the buffer is read-only. After I interrupt the function and quit the debugger the message "Warning (sly): Expected \`sly-mrepl--read-mark' to be set!" appears in the `*Warnings*` buffer. I don't know if it is just a message that appears whenever the debugger is quit, or if it is something caused by the bug whose issuance is delayed until the mrepl is again accepting input. It seems to happen randomly and with the identical likelihood to all calls to `read-line` and to be unaffected by previous input; after resuming control of the mrepl and rerunning the function to initiate input it will sometimes allow identical input without any problems or may happen to a different `read-line` call in the same sequence.

Here is some copy-pasted text from the mrepl buffer, the `add-cds` function initiates the input sequence but all the actual calls to `read-line` are in a function called `prompt-read`. Whenever the text "; Evaluation aborted on T" appears it is caused by me encountering this issue. Sorry for the random input towards the end, I was trying to generate enough some context. The same thing happens when using real input.

```
CL-USER> (add-cds)
Title: Weird Al Yankovich
Artist: 
Weird Al Yankovich
Rating: 
10

Ripped [y/n] (y or n) 
y

Another [y/n] (y or n) 
; Evaluation aborted on T
CL-USER> (add-cds)
Title: eoau eto uaoeu
Artist: 
eoauthaeou 
Rating: 
oeeunth 

Ripped [y/n] (y or n) 
y

Another [y/n] (y or n) 
eoutn

Please type "y" for yes or "n" for no.
Another [y/n] (y or n) 
eouanth euto

Please type "y" for yes or "n" for no.
Another [y/n] (y or n) 
y
Title: 
eotunh
Artist: 
; Evaluation aborted on T
CL-USER> (add-cds)
Title: eotunh 
Artist: 
eaoun htneou 
Rating: 
; Evaluation aborted on T
```
This is the `prompt-read` function that contains the `read-line` function that is always being called when this issue appears. I've tried using `t` instead of `*query-io*` as the stream since I wasn't (and still aren't) sure if this was maybe some strange interaction between SLY and SBCL but got the same results either way.

```
(defun prompt-read (prompt)
  (format *query-io* "~a: " prompt)
  (force-output *query-io*)
  (read-line *query-io*))
```

**Comment by joaotavora** [comment]
> (?SBCL or SLY? not the Emacs debugger in any case) debugger 

Exactly, it's the Lisp debugger, in this case SLY's.

OK, I'll have a look at this.  It might be related to #313 , though this is not exactly torture.

**Comment by joaotavora** [comment]
I need your version of Emacs.

**Comment by HarryFromMarydelDE** [comment]
Hi, thanks for looking at it for me, this is the output from `emacs-version`.

> GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-29

**Comment by HarryFromMarydelDE** [comment]
Also, SBCL is version 2.0.3 if that may be making any difference.

**Comment by joaotavora** [comment]
This may be connected with #313

**Comment by joaotavora** [comment]
I believe I've fixed this.  Please have a  look and report back here on in #313 if it doesn't work, in which case I'll reopen.
