### ISSUE TITLE
eldoc error: (error No current SLY connection.) for sly-autodoc

### ISSUE THREAD

**Issue by Zulu-Inuoe** [joaotavora/sly#325]
Maybe this is a Feature, but when sly is disconnected, I often have these error messages when navigating a lisp file.
It's particularly annoying when I've toggle'd Emacs' `debug-on-error` because I am diagnosing something else.

I believe it would be best for `sly-autodoc` to simply yield if sly is not currently connected to a lisp, rather than error.

Here's a backtrace:
```
Debugger entered--Lisp error: (error "No current SLY connection.")
  signal(error ("No current SLY connection."))
  error("No current SLY connection.")
  sly-connection()
  sly-autodoc()
  eldoc-print-current-symbol-info()
  #f(compiled-function () #<bytecode 0x1000dcc41>)()
  apply(#f(compiled-function () #<bytecode 0x1000dcc41>) nil)
  timer-event-handler([t 0 0 500000 nil #f(compiled-function () #<bytecode 0x1000dcc41>) nil idle 0])
```

**Comment by joaotavora** [comment]
ACK. I'll see what I can do.
