### ISSUE TITLE
Add optional support for ANSI colors

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#332]
One recurring annoyance is using `prove` with SLY: by default, it tries to use ANSI colors, which results in a lot of garbage being displayed in SLY:

```lisp
[0m
[31m× 1 of 2 tests failed[0m [90m(116ms)[0m
```

Prove is an archived project, so it won't receive any update to fix this:
https://github.com/fukamachi/prove#colorize-test-reports-on-slime

I found out that Emacs offers an easy solution:

```
  (defun sly-colorize-buffer (str)
      (ansi-color-apply str))
  (add-hook 'sly-mrepl-output-filter-functions 'sly-colorize-buffer)
```

What about adding this by default, or maybe as an option?

**Comment by PuercoPop** [comment]
@Ambrevar You don't need any support from Sly. By virtue of using comint mode you can use xterm-color to replace the characters with the appropriate colors. ej:

```elisp
(use-package xterm-color
  :ensure t
  :after (compile)
  :init
  (progn
    (add-hook 'comint-preoutput-filter-functions 'xterm-color-filter t)
    (setq comint-output-filter-functions
          (remove 'ansi-color-process-output comint-output-filter-functions))
    (add-hook 'compilation-start-hook
          (lambda (proc)
            (when (eq (process-filter proc) 'compilation-filter)
              (set-process-filter proc
                                  (lambda (proc string)
                                    (funcall 'compilation-filter proc
                                             (xterm-color-filter string)))))))))
```

Before I learned about xterm-color, with the help of Joao, I ported the SLIME contrib to SLY: https://github.com/PuercoPop/sly-repl-ansi-color

**Comment by joaotavora** [comment]
@PuercoPop, @Ambrevar isn't it much easier to:

```lisp
(add-hook 'sly-mrepl-mode-hook 
  (lambda ()
    (add-hook 'comint-preoutput-filter-functions 'ansi-color-apply)))
```

Instead of messing with compilation and so on and so forth?

(EDIT: I'm responding to a solution you since deleted)

**Comment by PuercoPop** [comment]
> (EDIT: I'm responding to a solution you since deleted)

Yeah sorry, I deleted because I realized most of it was unrelated to comint (just woke up). The relevant part was `(add-hook 'comint-preoutput-filter-functions 'xterm-color-filter t)` which is similar to what you are suggesting.

**Comment by joaotavora** [comment]
> eah sorry, I deleted because I realized most of it was unrelated to comint (just woke up). The relevant part was (add-hook 'comint-preoutput-filter-functions 'xterm-color-filter t) which is similar to what you are suggesting.

No probblem.  I also realized I made a mistake. The `nil t` final args to `add-hook` are essencial so that the hook is  only in effect in the mrepl buffer.

**Comment by Ambrevar** [comment]
@joaotavora Yes, I think your solution is ideal.
@PuercoPop Is there a particular benefit in using the Xterm package for this?

**Comment by Ambrevar** [comment]
@joaotavora However, you should define the function, lambdas are frown upon in hooks as they are blackboxes that are hard to remove after the fact.

**Comment by joaotavora** [comment]
> @joaotavora However, you should define the function, lambdas are frown upon in hooks as they are blackboxes that are hard to remove after the fact.

Yes, very true.

**Comment by PuercoPop** [comment]
@Ambrevar xterm-color supports more colors (xterm-256). Although for rove it doesn't matter

**Comment by Ambrevar** [comment]
@joaotavora Did you document this or add an option somewhere?

**Comment by joaotavora** [comment]
> @joaotavora Did you document this or add an option somewhere?

No.  I got the impression that you were happy with the `add-hook` solution.  You think something should be added to the manual?

**Comment by Ambrevar** [comment]
Yes, I think it'd be nice to have the code snippet you shared in the
manual (with a named function instead of the lambda).

Thanks!
