### ISSUE TITLE
sly-button-search: last-command is not always a symbol

### ISSUE THREAD

**Issue by grigorievich** [joaotavora/sly#336]
Hi!

SLY 1.0.0-beta-3

- ```(define-key lisp-mode-map (kbd "C-<f8>") (lambda () (interactive)))```
- ```C-<f8>```
- ```(sly-next-note 1)```

```
Debugger entered--Lisp error: (wrong-type-argument symbolp (lambda nil (interactive)))
  sly-button-search(1 identity)
  sly-next-note(1)
  eval((sly-next-note 1) nil)
  eval-expression((sly-next-note 1) nil nil 127)
  funcall-interactively(eval-expression (sly-next-note 1) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

A possible (not so elegant) fix in ```sly-button-search```:

```(not (get last-command 'sly-button-navigation-command))```
-> 
```(or (not (symbolp last-command)) (not (get last-command 'sly-button-navigation-command)))```

**Comment by joaotavora** [comment]
It's not so inelegant either, and I don't see anything more elegant at th emoement.  Maybe you can make a `sly--button-navigation-command-p` to wrap it, but I don't think it's strictly necessary.

Make a pull request for this, I will merge it.
