### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by nicklevine** [joaotavora/sly#346]
I get `'sly-eval-async' errored: (void-function t) `on SLY startup. Tracked this down through my 1600 line .emacs to whether or not I kept` '(inhibit-startup-screen t)` in my `custom-set-variables`. Any thoughts?

**Comment by joaotavora** [comment]
Hi @nicklevine , thanks for reporting this.

>  Any thoughts?

Only that this is indeed very odd.  My first request is that you try the same after `M-x toggle-debug-on-error` so that we can hopefully get a backtrace.

Also, I'd ask what Emacs version you're running and how you installed SLY. The recommended way is to use either `M-x package-install` after setting up MELPA as described in the README or, alternatively, add somewhere in your 1600 line `.emacs`:

```
(add-to-list 'load-path "/path/to/a/recent/git-clone-of-sly")
(require 'sly-autoloads)
```

That's it. `M-x sly` and `M-x sly-connect` should work.

**Comment by iwpiv** [comment]
I get the same error on startup, and here is my stack trace:

```
Debugger entered--Lisp error: (void-function t)
  t(#("; \n; \n;       Let the hacking commence!\n;         ..." 0 237 (face sly-mrepl-output-face font-lock-face sly-mrepl-output-face)))
  #f(compiled-function (fn) #<bytecode 0xfa1769>)(t)
  mapc(#f(compiled-function (fn) #<bytecode 0xfa1769>) (shell-filter-ctrl-a-ctrl-b t))
  sly-mrepl--insert-output("; \n; \n;       Let the hacking commence!\n;         ..." sly-mrepl-output-face)
  sly-mrepl--insert-note("\n\n      Let the hacking commence!\n            .\n  ..." sly-mrepl-output-face)
  sly-mrepl-new(#<process sly-1>)
  sly-mrepl--find-create(#<process sly-1>)
  sly-mrepl(pop-to-buffer)
  sly-mrepl-on-connection()
  run-hooks(sly-connected-hook)
  sly-set-connection-info(#<process sly-1> (:pid 14302 :style :spawn :encoding (:coding-systems ("utf-8-unix" "iso-latin-1-unix")) :lisp-implementation (:type "SBCL" :name "sbcl" :version "2.0.1-1.fc32" :program "/usr/bin/sbcl") :machine (:instance "awa" :type "X86-64" :version "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz") :features (:slynk :sb-bsd-sockets-addrinfo :asdf3\.3 :asdf3\.2 :asdf3\.1 :asdf3 :asdf2 :asdf :os-unix :non-base-chars-exist-p :asdf-unicode :x86-64 :64-bit :ansi-cl :common-lisp :elf :gencgc :ieee-floating-point :linux :little-endian :package-local-nicknames :sb-core-compression :sb-ldb :sb-package-locks :sb-thread :sb-unicode :sbcl :unix) :modules ("SLYNK/COMPLETION" "SB-CLTL2" "SB-POSIX" "SB-INTROSPECT" "SB-BSD-SOCKETS" "ASDF" "asdf" "UIOP" "uiop") :package (:name "COMMON-LISP-USER" :prompt "CL-USER") :version "1.0.0-beta-3"))
  apply(sly-set-connection-info (#<process sly-1> (:pid 14302 :style :spawn :encoding (:coding-systems ("utf-8-unix" "iso-latin-1-unix")) :lisp-implementation (:type "SBCL" :name "sbcl" :version "2.0.1-1.fc32" :program "/usr/bin/sbcl") :machine (:instance "awa" :type "X86-64" :version "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz") :features (:slynk :sb-bsd-sockets-addrinfo :asdf3\.3 :asdf3\.2 :asdf3\.1 :asdf3 :asdf2 :asdf :os-unix :non-base-chars-exist-p :asdf-unicode :x86-64 :64-bit :ansi-cl :common-lisp :elf :gencgc :ieee-floating-point :linux :little-endian :package-local-nicknames :sb-core-compression :sb-ldb :sb-package-locks :sb-thread :sb-unicode :sbcl :unix) :modules ("SLYNK/COMPLETION" "SB-CLTL2" "SB-POSIX" "SB-INTROSPECT" "SB-BSD-SOCKETS" "ASDF" "asdf" "UIOP" "uiop") :package (:name "COMMON-LISP-USER" :prompt "CL-USER") :version "1.0.0-beta-3")))
  #f(compiled-function (&rest more) #<bytecode 0x1310d39>)((:pid 14302 :style :spawn :encoding (:coding-systems ("utf-8-unix" "iso-latin-1-unix")) :lisp-implementation (:type "SBCL" :name "sbcl" :version "2.0.1-1.fc32" :program "/usr/bin/sbcl") :machine (:instance "awa" :type "X86-64" :version "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz") :features (:slynk :sb-bsd-sockets-addrinfo :asdf3\.3 :asdf3\.2 :asdf3\.1 :asdf3 :asdf2 :asdf :os-unix :non-base-chars-exist-p :asdf-unicode :x86-64 :64-bit :ansi-cl :common-lisp :elf :gencgc :ieee-floating-point :linux :little-endian :package-local-nicknames :sb-core-compression :sb-ldb :sb-package-locks :sb-thread :sb-unicode :sbcl :unix) :modules ("SLYNK/COMPLETION" "SB-CLTL2" "SB-POSIX" "SB-INTROSPECT" "SB-BSD-SOCKETS" "ASDF" "asdf" "UIOP" "uiop") :package (:name "COMMON-LISP-USER" :prompt "CL-USER") :version "1.0.0-beta-3"))
  #f(compiled-function () #<bytecode 0x13f5d19>)()
  funcall(#f(compiled-function () #<bytecode 0x13f5d19>))
  (let ((sly-ignore-protocol-mismatches 'nil)) (funcall '#f(compiled-function () #<bytecode 0x13f5d19>)))
  eval((let ((sly-ignore-protocol-mismatches 'nil)) (funcall '#f(compiled-function () #<bytecode 0x13f5d19>))))
  #f(compiled-function (g12) #<bytecode 0x1310d95>)((:ok (:pid 14302 :style :spawn :encoding (:coding-systems ("utf-8-unix" "iso-latin-1-unix")) :lisp-implementation (:type "SBCL" :name "sbcl" :version "2.0.1-1.fc32" :program "/usr/bin/sbcl") :machine (:instance "awa" :type "X86-64" :version "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz") :features (:slynk :sb-bsd-sockets-addrinfo :asdf3\.3 :asdf3\.2 :asdf3\.1 :asdf3 :asdf2 :asdf :os-unix :non-base-chars-exist-p :asdf-unicode :x86-64 :64-bit :ansi-cl :common-lisp :elf :gencgc :ieee-floating-point :linux :little-endian :package-local-nicknames :sb-core-compression :sb-ldb :sb-package-locks :sb-thread :sb-unicode :sbcl :unix) :modules ("SLYNK/COMPLETION" "SB-CLTL2" "SB-POSIX" "SB-INTROSPECT" "SB-BSD-SOCKETS" "ASDF" "asdf" "UIOP" "uiop") :package (:name "COMMON-LISP-USER" :prompt "CL-USER") :version "1.0.0-beta-3")))
  sly-dispatch-event((:return (:ok (:pid 14302 :style :spawn :encoding (:coding-systems ("utf-8-unix" "iso-latin-1-unix")) :lisp-implementation (:type "SBCL" :name "sbcl" :version "2.0.1-1.fc32" :program "/usr/bin/sbcl") :machine (:instance "awa" :type "X86-64" :version "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz") :features (:slynk :sb-bsd-sockets-addrinfo :asdf3\.3 :asdf3\.2 :asdf3\.1 :asdf3 :asdf2 :asdf :os-unix :non-base-chars-exist-p :asdf-unicode :x86-64 :64-bit :ansi-cl :common-lisp :elf :gencgc :ieee-floating-point :linux :little-endian :package-local-nicknames :sb-core-compression :sb-ldb :sb-package-locks :sb-thread :sb-unicode :sbcl :unix) :modules ("SLYNK/COMPLETION" "SB-CLTL2" "SB-POSIX" "SB-INTROSPECT" "SB-BSD-SOCKETS" "ASDF" "asdf" "UIOP" "uiop") :package (:name "COMMON-LISP-USER" :prompt "CL-USER") :version "1.0.0-beta-3")) 1) #<process sly-1>)
  sly-process-available-input(#<process sly-1>)
  sly-net-filter(#<process sly-1> "00033C(:return (:ok (:pid 14302 :style :spawn :enc...")
```

- and interestingly enough, I only get the error when I run 'sly' command in an emacs server instance, not in a standalone emacs process.

- I installed sly with use-package, with no specific config for sly whatsoever.

my emacs version is: 27.1,
os: fedora 32,
sbcl version is: SBCL 2.0.1

**Comment by iwpiv** [comment]
I get the same error on startup, and here is my stack trace:

Debugger entered--Lisp error: (void-function t)
  t(#("; \n; \n;       Let the hacking commence!\n;         ..." 0 237 (face sly-mrepl-output-face font-lock-face sly-mrepl-output-face)))
  #f(compiled-function (fn) #<bytecode 0xfa1769>)(t)
  mapc(#f(compiled-function (fn) #<bytecode 0xfa1769>) (shell-filter-ctrl-a-ctrl-b t))
  sly-mrepl--insert-output("; \n; \n;       Let the hacking commence!\n;         ..." sly-mrepl-output-face)
  sly-mrepl--insert-note("\n\n      Let the hacking commence!\n            .\n  ..." sly-mrepl-output-face)
  sly-mrepl-new(#<process sly-1>)
  sly-mrepl--find-create(#<process sly-1>)
  sly-mrepl(pop-to-buffer)
  sly-mrepl-on-connection()
  run-hooks(sly-connected-hook)
  sly-set-connection-info(#<process sly-1> (:pid 14302 :style :spawn :encoding (:coding-systems ("utf-8-unix" "iso-latin-1-unix")) :lisp-implementation (:type "SBCL" :name "sbcl" :version "2.0.1-1.fc32" :program "/usr/bin/sbcl") :machine (:instance "user" :type "X86-64" :version "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz") :features (:slynk :sb-bsd-sockets-addrinfo :asdf3\.3 :asdf3\.2 :asdf3\.1 :asdf3 :asdf2 :asdf :os-unix :non-base-chars-exist-p :asdf-unicode :x86-64 :64-bit :ansi-cl :common-lisp :elf :gencgc :ieee-floating-point :linux :little-endian :package-local-nicknames :sb-core-compression :sb-ldb :sb-package-locks :sb-thread :sb-unicode :sbcl :unix) :modules ("SLYNK/COMPLETION" "SB-CLTL2" "SB-POSIX" "SB-INTROSPECT" "SB-BSD-SOCKETS" "ASDF" "asdf" "UIOP" "uiop") :package (:name "COMMON-LISP-USER" :prompt "CL-USER") :version "1.0.0-beta-3"))
  apply(sly-set-connection-info (#<process sly-1> (:pid 14302 :style :spawn :encoding (:coding-systems ("utf-8-unix" "iso-latin-1-unix")) :lisp-implementation (:type "SBCL" :name "sbcl" :version "2.0.1-1.fc32" :program "/usr/bin/sbcl") :machine (:instance "user" :type "X86-64" :version "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz") :features (:slynk :sb-bsd-sockets-addrinfo :asdf3\.3 :asdf3\.2 :asdf3\.1 :asdf3 :asdf2 :asdf :os-unix :non-base-chars-exist-p :asdf-unicode :x86-64 :64-bit :ansi-cl :common-lisp :elf :gencgc :ieee-floating-point :linux :little-endian :package-local-nicknames :sb-core-compression :sb-ldb :sb-package-locks :sb-thread :sb-unicode :sbcl :unix) :modules ("SLYNK/COMPLETION" "SB-CLTL2" "SB-POSIX" "SB-INTROSPECT" "SB-BSD-SOCKETS" "ASDF" "asdf" "UIOP" "uiop") :package (:name "COMMON-LISP-USER" :prompt "CL-USER") :version "1.0.0-beta-3")))
  #f(compiled-function (&rest more) #<bytecode 0x1310d39>)((:pid 14302 :style :spawn :encoding (:coding-systems ("utf-8-unix" "iso-latin-1-unix")) :lisp-implementation (:type "SBCL" :name "sbcl" :version "2.0.1-1.fc32" :program "/usr/bin/sbcl") :machine (:instance "user" :type "X86-64" :version "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz") :features (:slynk :sb-bsd-sockets-addrinfo :asdf3\.3 :asdf3\.2 :asdf3\.1 :asdf3 :asdf2 :asdf :os-unix :non-base-chars-exist-p :asdf-unicode :x86-64 :64-bit :ansi-cl :common-lisp :elf :gencgc :ieee-floating-point :linux :little-endian :package-local-nicknames :sb-core-compression :sb-ldb :sb-package-locks :sb-thread :sb-unicode :sbcl :unix) :modules ("SLYNK/COMPLETION" "SB-CLTL2" "SB-POSIX" "SB-INTROSPECT" "SB-BSD-SOCKETS" "ASDF" "asdf" "UIOP" "uiop") :package (:name "COMMON-LISP-USER" :prompt "CL-USER") :version "1.0.0-beta-3"))
  #f(compiled-function () #<bytecode 0x13f5d19>)()
  funcall(#f(compiled-function () #<bytecode 0x13f5d19>))
  (let ((sly-ignore-protocol-mismatches 'nil)) (funcall '#f(compiled-function () #<bytecode 0x13f5d19>)))
  eval((let ((sly-ignore-protocol-mismatches 'nil)) (funcall '#f(compiled-function () #<bytecode 0x13f5d19>))))
  #f(compiled-function (g12) #<bytecode 0x1310d95>)((:ok (:pid 14302 :style :spawn :encoding (:coding-systems ("utf-8-unix" "iso-latin-1-unix")) :lisp-implementation (:type "SBCL" :name "sbcl" :version "2.0.1-1.fc32" :program "/usr/bin/sbcl") :machine (:instance "user" :type "X86-64" :version "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz") :features (:slynk :sb-bsd-sockets-addrinfo :asdf3\.3 :asdf3\.2 :asdf3\.1 :asdf3 :asdf2 :asdf :os-unix :non-base-chars-exist-p :asdf-unicode :x86-64 :64-bit :ansi-cl :common-lisp :elf :gencgc :ieee-floating-point :linux :little-endian :package-local-nicknames :sb-core-compression :sb-ldb :sb-package-locks :sb-thread :sb-unicode :sbcl :unix) :modules ("SLYNK/COMPLETION" "SB-CLTL2" "SB-POSIX" "SB-INTROSPECT" "SB-BSD-SOCKETS" "ASDF" "asdf" "UIOP" "uiop") :package (:name "COMMON-LISP-USER" :prompt "CL-USER") :version "1.0.0-beta-3")))
  sly-dispatch-event((:return (:ok (:pid 14302 :style :spawn :encoding (:coding-systems ("utf-8-unix" "iso-latin-1-unix")) :lisp-implementation (:type "SBCL" :name "sbcl" :version "2.0.1-1.fc32" :program "/usr/bin/sbcl") :machine (:instance "user" :type "X86-64") :features (:slynk :sb-bsd-sockets-addrinfo :asdf3\.3 :asdf3\.2 :asdf3\.1 :asdf3 :asdf2 :asdf :os-unix :non-base-chars-exist-p :asdf-unicode :x86-64 :64-bit :ansi-cl :common-lisp :elf :gencgc :ieee-floating-point :linux :little-endian :package-local-nicknames :sb-core-compression :sb-ldb :sb-package-locks :sb-thread :sb-unicode :sbcl :unix) :modules ("SLYNK/COMPLETION" "SB-CLTL2" "SB-POSIX" "SB-INTROSPECT" "SB-BSD-SOCKETS" "ASDF" "asdf" "UIOP" "uiop") :package (:name "COMMON-LISP-USER" :prompt "CL-USER") :version "1.0.0-beta-3")) 1) #<process sly-1>)
  sly-process-available-input(#<process sly-1>)
  sly-net-filter(#<process sly-1> "00033C(:return (:ok (:pid 14302 :style :spawn :enc...")

and interestingly enough, I only get the error when I run 'sly' command in an emacs server instance, not in a standalone emacs process.

I installed sly with use-package, with no specific config for sly whatsoever.

my emacs version is: 27.1,
os: fedora 32,
sbcl version is: SBCL 2.0.1

**Comment by joaotavora** [comment]
Thanks.  This is interesting.  I think I tracked this down to a bug in `sly-mrepl--insert-output` it's using a `mapc` where it should be using `run-hook-wrapped`.  Can you try the commit above?

**Comment by joaotavora** [comment]
Context: there are some comments by user @iwpiv that contain a backtrace prompting to do this fix, but these comments keep reappering and .disappearing
