### ISSUE TITLE
Company with SLY backend freezes on exit (C-g)

### ISSUE THREAD

**Issue by markusaschl** [joaotavora/sly#350]
```
$ emacs --version
GNU Emacs 26.1
Copyright (C) 2018 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

```
$ sbcl --version
SBCL 1.4.16.debian
```

I'm using a relatively clean emacs config here, with only ```sly``` and ```company``` enabled.

Upon triggering the abort function (```company-abort```) with ```C-g``` emacs freezes.  After that I have to quit and start it again.

Company works in ```.el``` files just fine, just with ```.lisp``` files it hangs.

I tried inspecting and debugging it on my own, but I'm not getting anywhere.

## How to reproduce this error

1) Open a new ```.lisp``` file
2) Write ```(def```

The company popup should already appear. If not,

3) trigger it with ```M-x``` ```company-manual-begin```
4) Type ```C-g``` to hide the tooltip.
5) Emacs hangs.

Funnily enough, emacs never hangs if you close the tooltip with ```e-e-e```.

**Comment by joaotavora** [comment]
This is a know bug with Emacs 26.1. If you upgrade to 26.3 or later you shouldn't see it.

**Comment by markusaschl** [comment]
Oh, man. Thank you :D
