### ISSUE TITLE
Hiding the REPL after invoking `sly`

### ISSUE THREAD

**Issue by joshuahoeflich** [joaotavora/sly#355]
Hi everyone,

Is it possible to get the repl to open in the background after calling the `sly` function? Right now, a new buffer and window pops up and steals focus when I invoke `sly`, and I would like to prevent that from happening if possible.

Thank you for the awesome project.

**Comment by joshuahoeflich** [comment]
I found a solution! This snippet of code causes Emacs to behave the way I would like it to:

```
(add-to-list 'display-buffer-alist
             `(,(rx bos "*sly-mrepl for sbcl*" eos)
               (display-buffer-no-window)
               (allow-no-window . t)))
```

Closing the issue. Again, thank you for the wonderful package.

**Comment by joaotavora** [comment]
This is a good solution, yes.

**Comment by joaotavora** [comment]
In fact, I seem to remember discussing it here or elsewhere some time in the past.

**Comment by joaotavora** [comment]
https://github.com/joaotavora/sly/issues/97 seems related
