### ISSUE TITLE
Prompt customization

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#360]
Today I tried to scratch an itch I had for a while: customize the SLY REPL prompt!

Here you go, the following prefixes the prompt with the current directory:

```elisp
(defun ambrevar/sly-prepare-prompt (old-func &rest args)
  (let ((package (nth 0 args))
        (new-prompt (format "%s:%s"
                            (abbreviate-file-name default-directory)
                            (nth 1 args)))
        (error-level (nth 2 args))
        (condition (nth 3 args)))
    (funcall old-func package new-prompt error-level condition)))

(advice-add 'sly-mrepl--insert-prompt :around #'ambrevar/sly-prepare-prompt)
```

What about exposing a customizable prompt function to the user?
It would also be neat to be able to fully customize the face, e.g. color the current directory and the current package differently.

**Comment by joaotavora** [comment]
I'm open to a PR that offers a one-variable interface to this.  The variable could be a function that would return the (possibly propertized) string to be used as the prompt.  What to pass to this function? That's your part of the work :-)

**Comment by Ambrevar** [comment]
Thanks, I'll send a patch then!

**Comment by joaotavora** [comment]
I adjusted some tricky parts, added documentation to the manual and merged this.  Please test when you find the time.

**Comment by Ambrevar** [comment]
Thank you very much!

Sadly, propertization (e.g. colors) of the different parts of the prompt don't work as is.
This is because comint-mode does its own formatting of the prompt.

I've worked around these issues in the last 2 commits of #365:
https://github.com/joaotavora/sly/pull/365/commits/03d5ac8551d52f21f12377b11999329aa284d7de
https://github.com/joaotavora/sly/pull/365/commits/786973415bd8d92648215305a767037a884ce47d

**Comment by Ambrevar** [comment]
Sorry, just the last commit actually: https://github.com/joaotavora/sly/commit/786973415bd8d92648215305a767037a884ce47d

**Comment by joaotavora** [comment]
Yes, I saw it.  This is trickier and I have to get a better look at it.

**Comment by joaotavora** [comment]
Can you post your fancy prompt code here? (sorry if you you already did that)

**Comment by Ambrevar** [comment]
OK, thanks! :)

This commit is my best effort at making the least changes.
I've been using it ever since and haven't witnessed any glitch so far.

**Comment by joaotavora** [comment]
Please post your custom prompt function here if you can.  Then I can better address the problems.

**Comment by Ambrevar** [comment]
There you go:

```elisp
(cl-defun ambrevar/sly-new-prompt (_package
                                package-nickname
                                error-level
                                entry-idx
                                _condition)
  (concat
   "("
   (propertize (abbreviate-file-name default-directory) 'font-lock-face 'diff-added)
   ")\n"
   (propertize "<" 'font-lock-face 'sly-mrepl-prompt-face)
   (propertize (number-to-string entry-idx) 'font-lock-face 'sly-mode-line)
   (propertize ":" 'font-lock-face 'sly-mrepl-prompt-face)
   (propertize package-nickname 'font-lock-face 'sly-mode-line)
   (when (cl-plusp error-level)
     (concat (sly-make-action-button
              (format "[%d]" error-level)
              #'sly-db-pop-to-debugger-maybe)
             " "))
   (propertize "> " 'font-lock-face 'sly-mrepl-prompt-face)))
```
