### ISSUE TITLE
Automatic optimized core generation and loading

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#363]
The manual mentions a technique to speed up SLY loading with SBCL.  I tried to automate it and came up with the following:

```elisp
(defun dump-sbcl-core-for-sly ()
  (cl-flet ((read-bytes (path)
                        (with-temp-buffer
                          (insert-file-contents-literally path)
                          (buffer-substring-no-properties (point-min) (point-max))))
            (call-process-to-string (command &rest args)
                                    (with-temp-buffer
                                      (apply #'call-process command nil t nil args)
                                      (buffer-string))))
    (let* ((sbcl-core-dir (expand-file-name "sly/" user-emacs-directory))
           (sbcl-core (expand-file-name "sbcl.core-for-sly" sbcl-core-dir))
           (sbcl-core-version (expand-file-name "sbcl.version" sbcl-core-dir))
           (current-sbcl-version (cadr (split-string
                                        (call-process-to-string "sbcl" "--version")))))
      (when (or (not (file-exists-p sbcl-core-version))
                (version< (car (split-string (read-bytes sbcl-core-version)))
                          current-sbcl-version))
        (make-directory sbcl-core-dir :parents)
        (ignore-errors
          (call-process
           "sbcl" nil nil nil
           "--eval" "(mapc 'require '(sb-bsd-sockets sb-posix sb-introspect sb-cltl2 asdf))"
           "--eval" (format "(save-lisp-and-die %S)" sbcl-core)))
        (with-temp-file sbcl-core-version
          (insert current-sbcl-version)))
      (when (file-exists-p sbcl-core)
        sbcl-core))))

(with-eval-after-load 'sly-mrepl
    (let ((core (dump-sbcl-core-for-sly)))
      (setq sly-lisp-implementations
            `((sbcl ("sbcl"
                     ,@(if core
                           `("--core" ,core)
                         '())))
              (ccl ("ccl"))
              (ecl ("ecl"))))))
```

What do you think of including this helper function in SLY?

By the way, is `with-eval-after-load 'sly-mrepl` the right moment to set `sly-lisp-implementations`? I don't want to dump the core when Emacs starts, only when I actually start SLY.

**Comment by joaotavora** [comment]
> What do you think of including this helper function in SLY?

As far as I understand, that "faster loading" version of SBCL is just a sbcl code with some packages pre-loaded right?   So I wouldn't exactly think this benefit would be exclusive to SLY, right?  SLIME could benefit, and so could any other generalistic use of the produced core.  What about you suggest to the SBCL developers that they distribute this SBCL?

> By the way, is with-eval-after-load 'sly-mrepl the right moment to set sly-lisp-implementations? I don't want to dump the core when Emacs starts, only when I actually start SLY.

No it's not, but it's close.  Read your words: "when I actualy start SLY".  You start it with `sly` or `sly-connect` right?  Those are in the `sly` package, not the `sly-mrepl` package, right?  So the correct way is `with-eval-after-load 'sly`.

But I guess you'd want to dump that core only when, not only you start SLY, but you start `sly` and select `sbcl` from the list. You need another cache-checking indirection, like a script.  Alternatively, if sly-lisp-implementation supported function elements in the `cdr`s of the alists, you could also use that.  But I don't think it does.  If could though, I'd accept a PR for that.

**Comment by Ambrevar** [comment]
João Távora <notifications@github.com> writes:

> As far as I understand, that "faster loading" version of SBCL is just a sbcl code with some packages pre-loaded right?   So I wouldn't exactly think this benefit would be exclusive to SLY, right?  SLIME could benefit, and so could any other generalistic use of the produced core.  What about you suggest to the SBCL developers that they distribute this SBCL?

It would benefit both SLY and SLIME indeed.  Note that I didn't come up
with this trick, it's in the SLY manual, section "8.2 Loading Slynk faster".

I think SLIME has the same chapter for Swank.

I don't think SBCL would change its default packages though.  So this
can only be done by the user.

Or are you suggesting that SBCL distributes 2 cores?  Maybe that's
something we could ask.

> No it's not, but it's close.  Read your words: "when I actualy start SLY".  You start it with `sly` or `sly-connect` right?  Those are in the `sly` package, not the `sly-mrepl` package, right?  So the correct way is `with-eval-after-load 'sly`.

That's what I first tried but I had made a mistake in my config which
led me to use sly-mrepl instead.  It does not do the right thing, you
are right, `(with-eval-after-load 'sly ...)` is correct.

> But I guess you'd want to dump that core only when, not only you start SLY, but you start `sly` and select `sbcl` from the list. You need another cache-checking indirection, like a script.  Alternatively, if sly-lisp-implementation supported function elements in the `cdr`s of the alists, you could also use that.  But I don't think it does.  If could though, I'd accept a PR for that.

You are right but this is a rather minor optimization considering that
the core is rebuilt only on version change.

So should I send a patch with the above code (polished) and a
sly-lisp-implementation that accepts functions?

**Comment by joaotavora** [comment]
> Or are you suggesting that SBCL distributes 2 cores?  Maybe that's
something we could ask.

Yes, I was suggesting that.  But I personally don't see any benefit, so _I personally_ wouldn't ask.  
I'd say SBCL starts up quickly enough on modern machines at least.

> So should I send a patch with the above code (polished) and a
sly-lisp-implementation that accepts functions?

These are two separate things.  I think the yoru elisp code could replace or follow the section in the manual where this question is discussed, but it should not be in SLY's Elisp source.

I also think that the section in the manual (but I haven't looked) discusses pre-loading Slynk itself into the image.  That could indeed yield a noticeable benefit (though again, when things are compiled into fasls and ASDF finds them, I get pretty fast startups).

The second improvement to `sly-lisp-implementations` is only if you feel it's worth it. But yes, I am open to it. 

Both things can be grouped in the same commit though.

**Comment by Ambrevar** [comment]
João Távora <notifications@github.com> writes:

> Yes, I was suggesting that.  But I personally don't see any benefit, so _I personally_ wouldn't ask.  
> I'd say SBCL starts up quickly enough on modern machines at least.

The SBCL website is offline so I'll try again later.

> I also think that the section in the manual (but I haven't looked) discusses pre-loading Slynk itself into the image.  That could indeed yield a noticeable benefit (though again, when things are compiled into fasls and ASDF finds them, I get pretty fast startups).

Indeed, although I didn't manage to get this part to work.  It failed
because of the sly-macrostep contrib.  I haven't investigated this yet.

**Comment by Ambrevar** [comment]
I've asked the SBCL folks here: https://bugs.launchpad.net/sbcl/+bug/1904042

**Comment by joaotavora** [comment]
I see you got the usual very silly one-liner treatment. Oh well, I'll see
about your PR to the docs.

João

**Comment by Ambrevar** [comment]
lisp-repl-core-dumper is now mentioned in the docs, closing.
