### ISSUE TITLE
Backport slime-mdot-fu?

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#373]
Very useful SLIME contrib in my opinion, it makes M-. work on let-bound variables.

https://github.com/slime/slime/blob/master/contrib/slime-mdot-fu.el

Thoughts?

**Comment by joaotavora** [comment]
Make this into a separate contrib, use https://github.com/joaotavora/sly-hello-world as a template.

**Comment by Ambrevar** [comment]
Actually I'd like to insist on including this by default in SLY.

After all, SLY already includes many contrib by defaults unlike SLIME.
This one is, in my opinion, universally useful.  It just makes sense
that M-. would also work on local symbols (instead of doing nothing).

Second though? :)
