### ISSUE TITLE
Backport slime-browse-classes and slime-browse-xrefs?

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#374]
https://github.com/slime/slime/blob/master/contrib/slime-xref-browser.el

It's a bit limited for now though.  Maybe this one would rather belong to a SLY contrib.

Thoughts?

**Comment by joaotavora** [comment]
The great Rui Patrocínio! Worked with that guy, great guy.  Yeah, make this into a SLY contrib use https://github.com/joaotavora/sly-hello-world as a template.

**Comment by Ambrevar** [comment]
This is rather low priority for me, so if anyone else is interested,
feel free to pick up the task ;)
