### ISSUE TITLE
Make (all?) timers configurable (in particular: instant startup!)

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#378]
I just found out that if I set the `sly-attempt-connection` timer from 0.3 to 0.1, I get near-instant REPL startup (using an optimized core).  

It's a dealbreaker in my opinion for those among us who use SLY as their main shell ;)

So I suggest making this a defcustom.  I wonder if changing the default value to 0.2 or 0.1 wouldn't be better.

Another timer is in `sly-db-exit`.

We already has the `sly-threads-update-interval` timer defcustom.
So I suggest adding `sly-exit-update-interval` and `sly-connection-update-interval`.

Thoughts?

**Comment by joaotavora** [comment]
On windows or on slower machines, things involving processes take some time to settle down, and choosing too low a period makes for spammy *Messages*. So make it a defcustom if you want, but don't change the default value.  In `sly-db-exit` the timer is related to SBCL-specific stepping, which is an obsolete feature, so no point changing it.
