### ISSUE TITLE
Can different REPLs have different working directories?

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#382]
I was wondering one thing: if different REPLs (of the same Lisp connection) can be in different packages, would it be possible to also have them be in different working directories?  (The current working directory being what `(uiop:getcwd)` returns.)
Or is this a fundamental limitation of Common Lisp?

**Comment by Ambrevar** [comment]
Friendly ping! @joaotavora Any idea?

**Comment by joaotavora** [comment]
Yeah, this is a bug.  the `cd` comma-command (or `M-x sly-cd`) should just work independently.

**Comment by Ambrevar** [comment]
But `sly-cd` sets `*default-pathname-defaults*` which is a global.  How can we possibly `cd` per-mrepl then?
(For the same Lisp connection.)

**Comment by joaotavora** [comment]
What does "global" mean to you?  Is `*package*` "global"?

**Comment by Ambrevar** [comment]
Good point!  Then it must be doable!

Out of curiosity (and because it's too late at night for me to keep
looking at code), how does SLY achieve that? O.o

**Comment by Ambrevar** [comment]
Should be fixed with #379.

**Comment by joaotavora** [comment]
I pushed a commit that should fix this.  Caution, it's not much tested, so I'm kind of relying on you to find any quirks.  Thanks!

**Comment by Ambrevar** [comment]
I've been using this for a few weeks now, it's been working well for me so
far! :)

Thanks for the fix!
