### ISSUE TITLE
Makefile tweak

### ISSUE THREAD

**Issue by rpgoldman** [joaotavora/sly#383]
I use Aquamacs, so I wanted to be able to override the value of `EMACS` in the `Makefile`.  Here's a patch that makes this possible.

```
diff --git a/Makefile b/Makefile
index b9492780..856f8c52 100644
--- a/Makefile
+++ b/Makefile
@@ -4,8 +4,8 @@

 # Variables
 #
-EMACS=emacs
-LISP=sbcl
+EMACS=-emacs
+LISP=-sbcl

 LOAD_PATH=-L . -L contrib/
```

**Comment by joaotavora** [comment]
Okay! Wow, an Aquamacs user ;-)

**Comment by joaotavora** [comment]
Can you point me to the piece of (GNU?) Make documentation that allows this.  I've done something similar in the past, though not exactly with this syntax, and I can't find documentation for the `=-` operator you propose.  If you supply variables _after_ the `make` command like `make target EMACS=foo` it should work in the current version.

**Comment by rpgoldman** [comment]
Maybe I wanted `?=`. I think the ` =-` is a bash thing. I didn’t think overriding on the command line worked with just the equal sign.

But I may have used Apple’s make instead , by accident.

**Comment by joaotavora** [comment]
> Maybe I wanted ?=.

Yeah that sounds more familiar.

> I didn’t think overriding on the command line worked with just the equal sign.

It works if you supply them _after_ the make invocation, as arguments to the problem make.

If you want to override from the environment, you have to use a trick similar to `?=` (though I'm still not 100% sure on that).

> But I may have used Apple’s make instead , by accident.

I don't think there's a difference in behaviour in this regard, but I might be wrong.

**Comment by rpgoldman** [comment]
Ok. Closing, thanks!

**Comment by joaotavora** [comment]
I mean, we can still tweak the Makefile to allow for environment override if you want, I don't think it's a terrible idea :-) it's just I have to be sure of the compatible syntax, you understand.
