### ISSUE TITLE
Problems with recent Clasp build

### ISSUE THREAD

**Issue by mdbergmann** [joaotavora/sly#386]
I've made a new Clasp build but it seems it doesn't work with Sly.
Here is what I get from the interior-lisp process.
If some one can pin point what the problem might be I can have a look:

```
(cond ((ignore-errors (funcall 'require "asdf") (funcall (read-from-string "asdf:version-satisfies") (funcall (read-from-string "asdf:asdf-version")) "2.019")) (push (pathname "/Users/mbergmann/.emacs.d/plugi\
    ns/sly/slynk/") (symbol-value (read-from-string "asdf:*central-registry*"))) (funcall (read-from-string "asdf:load-system") :slynk) (funcall (read-from-string "slynk:start-server") "/var/folders/2z/831jl36d01\
    317d4pz3g2_j100000gn/T/sly.28475")) (t (progn (load "/Users/mbergmann/.emacs.d/plugins/sly/slynk/slynk-loader.lisp" :verbose t) (funcall (read-from-string "slynk-loader:init")) (funcall (read-from-string "sly\
    nk:start-server") "/var/folders/2z/831jl36d01317d4pz3g2_j100000gn/T/sly.28475"))))
  2
  3 Starting cclasp-boehm-0.4.2-3490-gaefa764ed-cst ... loading image...
  4 Top level in: #<PROCESS TOP-LEVEL @0x10ea7eb51 (Running)>.
  5 COMMON-LISP-USER> ; Compiling file parallel: /Users/mbergmann/.emacs.d/plugins/sly/slynk/slynk-gray.lisp
  6 ;   (IN-PACKAGE COMMON-LISP-USER::SLYNK-BACKEND)
  7 ;   NIL
  8 ; caught ERROR:
  9 ;   Read-time evaluation of expression (GRAY-PACKAGE-NAME) signaled SIMPLE-ERROR: GRAY-PACKAGE-NAME not implemented
 10 ;     at unknown location
 11 ;
 12
 13 Condition of type: READ-TIME-EVALUATION-ERROR
 14 Read-time evaluation of expression (SLYNK-BACKEND:GRAY-PACKAGE-NAME) signaled SIMPLE-ERROR: SLYNK-BACKEND:GRAY-PACKAGE-NAME not implemented
 15 Available restarts:
 16 (use :r1 to invoke restart 1, etc.)
 17
 18 1. (RECOVER) Use NIL in place of the missing object.
 19 2. (RETRY) Retry compiling #<CL-SOURCE-FILE "slynk" "slynk-gray">.
 20 3. (ACCEPT) Continue, treating compiling #<CL-SOURCE-FILE "slynk" "slynk-gray"> as having been successful.
 21 4. (RETRY) Retry ASDF operation.
 22 5. (CLEAR-CONFIGURATION-AND-RETRY) Retry ASDF operation after resetting the configuration.
 23 6. (RETRY) Retry ASDF operation.
 24 7. (CLEAR-CONFIGURATION-AND-RETRY) Retry ASDF operation after resetting the configuration.
 25 8. (RESTART-TOPLEVEL) Go back to Top-Level REPL.
 26
 27 l_%READER-ERROR^ECLECTOR.BASE^FN^^
```

**Comment by joaotavora** [comment]
I don't have clasp to try this out, in fact I never did, I just kept on cherry picking SLIME's commits to the clasp backend.  It think this patch should bring you closer to success, can you try it out?

```diff
diff --git a/slynk/slynk.asd b/slynk/slynk.asd
index 540a3ffb..e53586e7 100644
--- a/slynk/slynk.asd
+++ b/slynk/slynk.asd
@@ -50,6 +50,8 @@
                  (:file "lispworks")
                  #+sbcl
                  (:file "sbcl")
+                 #+clasp
+                 (:file "clasp")
                  #+scl
                  (:file "scl")
                  #+mkcl
```

Basically it makes SLY's ASDF loader also load the `clasp.lisp` backend file, which is pretty essential if you want to run SLY/clasp :-)

**Comment by mdbergmann** [comment]
Tried it.
It bails out with accessing `slynk::*log...` saying package SLYNK is not known.
So I commented out all accesses to SLYNK package. None of the other backends seems to have it.
Then it kind of starts, but the REPL never comes visible, in the inferior lisp process buffer there is an endless stream of stuff printed.
Needs some more looking I guess.

**Comment by joaotavora** [comment]
Manfred Bergmann <notifications@github.com> writes:

> Tried it.
> It bails out with accessing slynk::*log... saying package SLYNK is not known.
> So I commented out all accesses to SLYNK package. None of the other
> backends seems to have it.

Right, and they shouldn't.  The clasp backend is a mess.  I'm curious
how the file even loads in SLIME, which has the same violation.  I'm
guessing they create the SWANK package in advance.

> Then it kind of starts, but the REPL never comes visible, in the inferior lisp process buffer there is an endless stream
> of stuff printed.
> Needs some more looking I guess.
>
Clasp's backend implementation is changed frequently in the SLIME
source.

I think what you should do is just copy over SLIME's clasp.lisp file,
then do the following replacements:

   swank/ -> slynk-

   swank -> slynk

In this order.

If you know some Git, you can also cherry-pick the SLIME commits from
SLIME and fix the conflicts yourself.  That's what I do from time to
time, it's not an immensely difficult job, just a bit boring.

If I could get my hands on self-contained x86_64 bin build of clasp, I'd
help you, but building it myself is off the table: it's a mess of a
process.

João

**Comment by mdbergmann** [comment]
> I think what you should do is just copy over SLIME's clasp.lisp file,
then do the following replacements:

Yep, did that.
But it's the same result as previously. Something loops while doing output on the buffer.

> If I could get my hands on self-contained x86_64 bin build of clasp

Are you on Mac?

**Comment by joaotavora** [comment]
> Are you on Mac?

I can get a Mac yes.

**Comment by mdbergmann** [comment]
Here is a packaged up build. It's quite big, but yeah.
https://www.dropbox.com/s/spm8bf41m6idsjc/clasp_git_build.tar.xz?dl=0

After unpacking you can run `clasp/build/boehm/iclasp-boehm`.
The symlinks don't work as they still point to my install.

It is not completely self-contained. I had to install two dependencies via brew. But SBCL or any other also has some dependencies.

brew install bdw-gc
brew install boost

Let me know if you wanna use it or when you downloaded it so I can remove it again.

**Comment by joaotavora** [comment]
Thanks, I'm downloading it.

> but SBCL or any other also has some dependencies.

Not really true. They don't need dynamically loaded libs, generally, at least not exotic ones.  sbcl on Mac needs a system lib and libz, both in usr/lib.  Allegro Common Lisp is basically independent.

But I will install these dependencies if they are reasonable (boost is).

**Comment by mdbergmann** [comment]
> Not really true. 

Depends, yes. Something like Allegro or LispWorks certainly is.

**Comment by joaotavora** [comment]
Alright, I'm finished downloading, you can erase it.

**Comment by joaotavora** [comment]
Alright, I managed to do it without _that_ much of an hassle.  I have to commit something to SLY and then you can try the previous technique with the two substitutions:

```
swank/ slynk-
swank slynk
```

plus this other one:

```
slime sly
```

(i was missing the last one)

<img width="583" alt="image" src="https://user-images.githubusercontent.com/387011/101525709-8f250880-3983-11eb-9c2e-cd3c4e36f439.png">

**Comment by joaotavora** [comment]
To make this official, a task remains.  To properly cherry pick SLIME's commits that touch the `clasp.lisp` file into SLY, doing the substitutions in every commit.  (and using `git cherry-pick -x`, basically looking at the other commits for how to do it).  Then we can keep the Git history. 

If you'd like to volunteer for this task, that'd be great.  Otherwise I'll get to it in a few days.

**Comment by mdbergmann** [comment]
> Alright, I managed to do it without that much of an hassle.

That's great.

> To make this official, a task remains.

You mean cherry picking the changes from the clasp.lisp in Sly to what the state is in Slime?
I can do that.

**Comment by mdbergmann** [comment]
> otherwise I'd never enture to build that 2GB+ monster

Actually it isn't that much to endure. :)
There are some prerequisites, like installing llvm9 via brew.
But otherwise, it took 20 minutes to build on my 8 core Xeon.

**Comment by mdbergmann** [comment]
OK, I think I got it all cherry-picked.
Do you want me to comment-out or remove those debug lines with `slynk::*log...`.
I probably would just remove them.

**Comment by joaotavora** [comment]
> Do you want me to comment-out or remove those debug lines with slynk::*log....

Not sure.  At this point I'd like to look at the Git branch you produced. Before I potentially waste some of your effort on this.  Can you push that branch somewhere?

**Comment by mdbergmann** [comment]
It's here: https://github.com/mdbergmann/sly

**Comment by joaotavora** [comment]
It seems fine, almost perfect, Manfred (you forgot the -x to cherry-pick that gives one a slightly better context).  I'll take it from there and examine the commit messages and such. As you may understand, I like to keep as much similitude between SLY and SLIME here as I possibly can.

**Comment by mdbergmann** [comment]
Uhm, sorry. I missed the '-x' flag that you have written.
I can redo it, as a reminder on myself to pay attention.

**Comment by mdbergmann** [comment]
I found those in the 'messages' after a while, seems to originate from the repl.

error in process filter: sly-dispatch-event: Invalid rpc: Thread not found: 1
error in process filter: Invalid rpc: Thread not found: 1

**Comment by joaotavora** [comment]
You wouldn't need to re-do all of it no! The -x only adds something to the commit message, no need to go through the conflicts resolution again (assuming you resolved them correctly the first time around).  

So a `rebase --interactive`  adding these lines at the end of each commit message is all that's needed:

```
Cherry-picked-from: SLIME commit 12341251234125125
Co-authored-by: Mandred Bergman <your-email-here>
```

**Comment by joaotavora** [comment]
> I found those in the 'messages' after a while, seems to originate from the rep

Make a separate bug report about that, but first I'd focus on getting the cherry-pick of these commits.

**Comment by joaotavora** [comment]
And thanks a lot for your work.

**Comment by mdbergmann** [comment]
OK, done the rebase.

**Comment by joaotavora** [comment]
Alright, looks peachy :ok_hand:.  I still have to review so please don't delete that branch (or save it under some other name than `master`. ).  Thanks very much.

**Comment by mdbergmann** [comment]
No probs. I'll leave it at master for the time being.

**Comment by joaotavora** [comment]
I've updated SLY to the relevant commits in SLIME's version 2.26, which should include all this Clasp stuff.  Please try out the https://github.com/joaotavora/sly/tree/ongoing-slime-catchup branch when you can.

**Comment by mdbergmann** [comment]
Nope, doesn't work.

```
Condition of type: PACKAGE-DOES-NOT-EXIST
Package named "SLYNK" does not exist.
```

Did you do all the cherry-picks again for this branch?

**Comment by joaotavora** [comment]
> Did you do all the cherry-picks again for this branch?

Yes. I redid them since I found your cherry-picks to have reference to non-exiting SLIME commit SHAs.

I'm working on this as we speak, just pushed a new `ongoing-slime-catchup` branch.

**Comment by joaotavora** [comment]
...and a new one.  Now the `clasp.lisp` in my branch is the `ongoing-slime-catchup` very similar to the one in your `master` branch, so you _should_ in theory be good.

**Comment by mdbergmann** [comment]
> have reference to non-exiting SLIME commit SHAs.

Indeed. Not sure how that happened. I basically just did a copy&paste of this hash as was presented in the interactive rebase dialog. But those hashes seem to belong to nowhere, not my branch and not slime either. Piece of shit.

**Comment by joaotavora** [comment]
> Piece of shit.

No worries, it's quite confusing, sometimes.  But it does help in relating things.  I actually have the SLIME tree inmy local copy of the SLY repo. A lot of the history has diverged, but a lot is in common, so it's pretty useful to just paste that number (presuming it is correct) and type `git show` `git checkout <sha>`, etc.

**Comment by joaotavora** [comment]
Anyway, it was some work to bring it up-to-date with SLIME 2.26, but it's something I do every two years anyway, so yeah.

I did opt not to bring in the the Mezzano backend, so that's missing.  If someone could test these exotic backends (Mezzano, ABCL, Clisp, etc), much like you did with Clasp, it would be great.

**Comment by mdbergmann** [comment]
> I actually have the SLIME tree inmy local copy of the SLY repo.

I do, too. That's how I did the cherry-picking.

So, I've updated my local branch to c70ff317, but there are still uses of `slynk::` in there.

**Comment by joaotavora** [comment]
> So, I've updated my local branch to c70ff31, but there are still uses of slynk:: in there.

Right, and I'll take care of those.  But they should be commented out by the reader conditionals. I'm away from the mac where I did the Clasp experiments right now.

**Comment by joaotavora** [comment]
I've fixed the problem, and played around a bit with Clasp.  After fixing a detail in the REPL code, it seems to be behaving decently (though I suspect there's something seriously wrong with its weak pointers, ask be about it if you're interested).

**Comment by joaotavora** [comment]
Also, I've released 1.0.42 the first non-beta version of SLY :-)

**Comment by mdbergmann** [comment]
> I've released 1.0.42 the first non-beta version of SLY

concratulations. :)

> ask be about it if you're interested

I think I am.

**Comment by drmeister** [comment]
Hi folks - I'm Christian Schafmeister, lead developer of Clasp.
I didn't realize you folks were doing so much work supporting clasp in sly.
I'd love to talk with someone about it.

**Comment by joaotavora** [comment]
Hello Christian. Thanks very much for reaching out.

We're not doing _that much work_, which is probably why it's likely still broken.  I'm mainly copying SLIME's `clasp.lisp` with small systematic changes. I even keep your authorship of the commits as I cherry-pick them and perform the simple edits.  This works great for other backends but for Clasp seems to be slightly more problematic.  

I tried debugging but I know next to nothing about how Clasp works and neither do I have much time.  (If I may risk a small criticism, if would help if the commit messages for each change you do to `clasp.lisp` contained an objective summary of the changes instead of grouping unrelated changes under a terse and cryptic headline that I'm sure makes sense to you).

Last I remember, I tried Manfred's CLASP build and had some success after a few tweaks to `clasp.lisp`, but had something break very soon because of a weak pointer that was gc'ed too early I think.  Or something like that.

If you could try it out in your system (SLY is very easy to setup, just like SLIME) with some of your Clasp builds (of which I suppose you have many and can make them easily), that could be the simplest way.

I'm more than happy to provide support for doing the latter.  Then we could really sync up SLIME and SLY's `clasp.lisp` (which, as I said is what I've been doing for Allegro/SBCL/CCL/others for some years, with great success, even in both directions.)

João

**Comment by drmeister** [comment]
Hi - I'd like to work with you to get clasp working well with sly.   
We have some problems with slime and sldb and I'm curious if they go away or change with sly.
I'll install sly and give it a go and get back to you.

Don't worry about criticism - it's a challenge for me to provide good git commit messages.
