### ISSUE TITLE
`eval-in-frame` from different window?

### ISSUE THREAD

**Issue by anlsh** [joaotavora/sly#391]
When I'm trying to evaluate expressions in debug frames, I've often been annoyed that I have to type my expressions into the minibuffer (where some of the minor modes / keybinds I like are disabled). A related annoyance is that larger output from `eval-in-frame` gets shunted off to another buffer/window which, depending on where emacs decides to drop it, might replace an important buffer on my screen.

Personally, I would really like the option to spawn some sort of "debug repl" buffer, which functioned more or less like an ordinary `sly-mrepl-mode` buffer except that all expressions happen to be evaluated in the spawning debug frame. Ideally the buffer would be automatically killed upon debug frame cleanup too.

Is there any scope in sly for a feature like this (perhaps even some option/command I've overlooked)?

**Comment by anlsh** [comment]
Maybe this is more suitable for github's new "discussions" feature? If we want I can close this issue and start a discussion instead

**Comment by joaotavora** [comment]
> Maybe this is more suitable for github's new "discussions" feature? If we want I can close this issue and start a discussion instead

Hehe, I was just thinking about that too. I don't know, whichever way you prefer.

**Comment by joaotavora** [comment]
yeah let's try that out there.  I'm preparing my reply anyway.

**Comment by joaotavora** [comment]
(I think it's better if _you_start the discussion, right?) Just paste your text, I've prepared my reply already.

**Comment by anlsh** [comment]
Done https://github.com/joaotavora/sly/discussions/393
