### ISSUE TITLE
Error when reinspecting value

### ISSUE THREAD

**Issue by Zulu-Inuoe** [joaotavora/sly#397]
Reproduction steps:

1. Invoke the sly inspector on a value
2. Press `q`
3. `C-x b` and switch back to the (still present) inspector
4. Reinspect the value
This causes the following error:
```lisp
The value
  NIL
is not of type
  SLYNK::ISTATE
   [Condition of type TYPE-ERROR]

Restarts:
 0: [*ABORT] Return to SLY's top level.
 1: [ABORT] abort thread (#<THREAD "slynk-worker" RUNNING {1004A9D3E3}>)

Backtrace:
 0: (SLYNK:INSPECTOR-REINSPECT)
 1: (SLYNK:EVAL-FOR-INSPECTOR NIL NIL SLYNK:INSPECTOR-REINSPECT)
 2: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SLYNK:EVAL-FOR-INSPECTOR NIL NIL (QUOTE SLYNK:INSPECTOR-REINSPECT)) #<NULL-LEXENV>)
 3: (EVAL (SLYNK:EVAL-FOR-INSPECTOR NIL NIL (QUOTE SLYNK:INSPECTOR-REINSPECT)))
 4: ((FLET SLYNK::EVAL-IT :IN SLYNK:EVAL-FOR-EMACS))
 5: ((LAMBDA NIL :IN SLYNK-NAMED-READTABLES::WRAP-IN-NAMED-READTABLE))
 6: (SLYNK:EVAL-FOR-EMACS (SLYNK:EVAL-FOR-INSPECTOR NIL NIL (QUOTE SLYNK:INSPECTOR-REINSPECT)) NIL 4344 :NAMED-READTABLE NIL)
 7: ((LAMBDA NIL :IN SLYNK::SPAWN-WORKER-THREAD))
 8: (SLYNK-SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION SLYNK:SLYNK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-WORKER-THREAD) {1004AB954B}>)
 9: ((FLET SLYNK-BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "c:/Users/Zulu/.emacs.d/elpa/sly-20201030.929/slynk/backend/sbcl.lisp") #<FUNCTION SLYNK:SLYNK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-WO..
10: (SLYNK-BACKEND:CALL-WITH-DEBUGGER-HOOK #<FUNCTION SLYNK:SLYNK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SLYNK::SPAWN-WORKER-THREAD) {1004AB954B}>)
11: ((LAMBDA NIL :IN SLYNK::SPAWN-WORKER-THREAD))
```

if `q` is removing some variables vital to the inspector, maybe it should kill the buffer, too

**Comment by joaotavora** [comment]
Confirmed. 

> if q is removing some variables vital to the inspector, maybe it should kill the buffer, too

Yep, it's one or the other.  Either it doesn't kill the variables, or it must kill the buffer.

**Comment by joaotavora** [comment]
This comes down to a one-character bug :-D
```diff
diff --git a/sly.el b/sly.el
index 1b965288..aa32a759 100644
--- a/sly.el
+++ b/sly.el
@@ -6716,7 +6716,7 @@ position of point in the current buffer."
   "Quit the inspector and kill the buffer.
 With optional RESET (true with prefix arg), also reset the
 inspector on the Lisp side."
-  (interactive "p")
+  (interactive "P")
   (when reset (sly-eval-async `(slynk:quit-inspector)))
   (quit-window))
```

**Comment by joaotavora** [comment]
I fixed this with the above change.  Other alternatives would be to `kill-buffer` when `reset` is non-nil.  And maybe to make reset default to `t`.  This might be useful if the user is trying hard not to leave noncollectable garbage lying around.

**Comment by Zulu-Inuoe** [comment]
Great, thanks!

I think the ability to pull up the inspector back up for a previous value is more valuable than worrying about the GC, so I don't think `reset` should default to `t` in that case.

If you wanted to be fancy about it, you could store a weak reference to the inspected object on quit, and if the user attempts to reinspect you can gracefully tell them "the value is no longer available" in cases where it's been gc'd. That gets you the best of both worlds, I think

**Comment by joaotavora** [comment]
> I think the ability to pull up the inspector back up for a previous value is more valuable than worrying about the GC, 

Hmmm, it's a tough call.  If possible IDE itself shouldn't ideally be responsible for any leftover global references that the user isn't aware of.  Or at least, the user should be able to cleanly get rid of them "naturally".

I think the correct approach here is to put the `slynk:quit-inspector` in that buffer's kill hook.  So that at least if the user wants to guarantee no dangling references he can kill all the SLY buffers.  A similar situation with the the REPL and the trace dialog (and maybe others).  But this is the subject of another issue/PR,  I guess.
