### ISSUE TITLE
Can we customize mrepl's default package?  Or simply not force it to cl-user?

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#399]
I've added the following sly-lisp-implementation:

```lisp
("sbcl" "--eval" "(in-package :alexandria)")
```

Running the above command in a shell works: `*package*` is indeed `#<PACKAGE "ALEXANDRIA">`.
However SLY reverts the package to CL-USER on startup.  I'd like to change this behaviour and have SLY let me choose the default package.

Browsing the source all I could find is this:

```lisp
(defclass mrepl (channel listener)
  ((remote-id   :initarg  :remote-id :accessor mrepl-remote-id)
   (mode        :initform :eval   :accessor mrepl-mode)
   (pending-errors :initform nil :accessor mrepl-pending-errors))
  (:documentation "A listener implemented in terms of a channel.")
  (:default-initargs
   :initial-env `((cl:*package* . ,(find-package :COMMON-LISP-USER))
                  (*) (**) (***)
                  (/) (//) (///)
                  (+) (++) (+++)
                  (*history* . ,(make-array 40 :fill-pointer 0
                                               :adjustable t)))))
```

So this environment seems to be hard-coded.
I can't seem to be able to customize it from `~/.slynk.lisp` because the `:slynk-repl` package is not known when the file is parsed.

Any idea how to fix this?

**Comment by joaotavora** [comment]
Wasn't there an issue for this?  @Ambrevar I'm sorry, but you open so many and I only have limited bandwidth (because job) and so I can't process things appropriately

**Comment by joaotavora** [comment]
Never mind, this is for package, not directory

**Comment by joaotavora** [comment]
OK, this is a feature request

**Comment by joaotavora** [comment]
Not really important in my view, but if you can make a simple implementation with no knobs (or at most one) and a decent default in under 30 lines or so, I'll look at it.  Maybe some good way to find the "main thread" and evaluate `*package*`  there?

**Comment by Ambrevar** [comment]
Understood.

Is there a reason for setting the package in initial-env anyways?  Why
not just remove it?  Seems to me that it would do the right thing: use
the Lisp implementation default, or the package commanded by the user.

**Comment by joaotavora** [comment]
```

**Comment by joaotavora** [comment]
```diff
diff --git a/contrib/slynk-mrepl.lisp b/contrib/slynk-mrepl.lisp
index 5bd08d47..fc8af0af 100644
--- a/contrib/slynk-mrepl.lisp
+++ b/contrib/slynk-mrepl.lisp
@@ -30,7 +30,7 @@
    (pending-errors :initform nil :accessor mrepl-pending-errors))
   (:documentation "A listener implemented in terms of a channel.")
   (:default-initargs
-   :initial-env `((cl:*package* . ,(find-package :COMMON-LISP-USER))
+   :initial-env `((cl:*package* . ,cl:*package*)
                   (*) (**) (***)
                   (/) (//) (///)
                   (+) (++) (+++)
```

Seems it does do something not completely stupid.  Please test for a while, and then we can merge it.

**Comment by Ambrevar** [comment]
Just tried it, seems to be working like a charm for now.
I'll report in the coming days if I hit any issue.

**Comment by Ambrevar** [comment]
No issues for a week!  Looks OK to merge :)
