### ISSUE TITLE
Don't append space after filename completion

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#404]
In IELM, completing against a filename does not append a space afterwards.
SLY does.

Indeed, you don't want to append a space (unlike the shell) because filenames in Lisp are always surrounded with double quotes.  Example

```
;; <TAB> is the position of the point where we press TAB.
(some-exp "./path/to/beginning-of-<TAB>")

;; In IELM, it expands to
(some-exp "./path/to/beginning-of-filename")

;; In SLY, it expands to
(some-exp "./path/to/beginning-of-filename ")
```

Took me ages to figure out why, until finally I found the right option in `ielm.el`:

```lisp
(set (make-local-variable 'comint-completion-addsuffix) '("/" . ""))
```

**Comment by Ambrevar** [comment]
@joaotavora What do you think?  It's a trivial fix, so I guess this can be safely merged as is.

**Comment by joaotavora** [comment]
I can't do the fix unless I understand the problem.  I can't reproduce your situation.  So I need an `Emacs -Q` reproduction recipe, as usual.  Sorry.

**Comment by Ambrevar** [comment]
No problem.

In a shell:

$ touch ~/foo

Then from vanilla Emacs:

- `M-x sly RET`
- `,cd RET ~/ RET`
- `"./fo<TAB>`

Result:

```
"./foo 
```
(note the trailing space)

Expected:
```
"./foo
```
(no trailing space)

The problem only occurs when completing against files, not directories.

**Comment by joaotavora** [comment]
OK.  Reproduced and fixed

**Comment by Ambrevar** [comment]
Thanks a lot!
