### ISSUE TITLE
Make sly-xref--show-results customizable

### ISSUE THREAD

**Issue by Ambrevar** [joaotavora/sly#408]
In helm-sly I advice-override sly-xref--show-results to customize how the results are presented.
Weirdly enough, the advice is ignored once in a while and the default function is used instead.

Any idea why?

Anyways, advising is rarely a good idea, but I don't think there is an entry point to customize how to present the Xref results other than this.

Could we make it customizable by adding a defcustom for this function?

**Comment by joaotavora** [comment]
> Could we make it customizable by adding a defcustom for this function?

No, I don't think that's a good iedea.  I'd rather tear apart `sly-xref` stuff completely and make it use Emacs's `xref.el`.  Now that's a project.  Less code, more functionality.  And I guess you can add the Helm goodies there with a proper API.

**Comment by Ambrevar** [comment]
Fair enough.  I had brought up this idea to Emacs upstream, there is a discussion on the mailing list, hopefully someone will pick it up! :)
