### ISSUE TITLE
REPL print buffer issue

### ISSUE THREAD

**Issue by mustiboost** [joaotavora/sly#431]
Given the test code: 

```lisp
(dotimes (x 10)
	       (sleep 1) (format t "~a " x))
```
sly REPL waits for 10 seconds and then prints out 

```shell
0 1 2 3 4 5 6 7 8 9
```
all at once, instead of one by one every second as it should.

**Comment by joaotavora** [comment]
So will any "normal" Lisp REPL, as far as I know.  The output buffer flushes on newlines or explicit `force-output`:

Try:
```
(dotimes (x 10)
	       (sleep 1) (format t "~a~%" x))
```

Closing, but we can keep discussing if you want.

**Comment by mustiboost** [comment]
Try it in slime, or write the equivalent code in elisp (ielm), or try it even in slima on atom (which obviously uses slime), the numbers appear as they should on the same line 1 second apart on all of those. Yes, on the sbcl repl you start in the command line it's different and all the numbers appear at once after 10 seconds.  However, most people do not use just sbcl or any other "inferior lisp" on the command line.  I think even without a next line character, the numbers should show up 1 second apart. That makes the most sense. I don't know, it's your call, I thought I'd mention it as a possible "bug" as slime, slima, and ielm don't have this issue. But I guess you could call it a "feature enhancement suggestion." :) (It does not seem like a big deal in this example, but who knows where else this "issue" may crop up, in contexts that are much more critical).

**Comment by joaotavora** [comment]
`ielm` is for a completely different language.  There might be some options to do per-byte flushing, or have a flushing timer, but that's generally inefficient (and mostly useless, except for stderr, which is unbuffered by default on libc I think).  This probably explains why some lisps take the flush-on-newlines approach.

I'll look at some options to control this in SLY, I think there are some.

PS: it's hard to read your text if you edit it.  If you want to add something, just make a new entry.  Also, https://github.com/joaotavora/sly/discussions might be a better place for this.

**Comment by mustiboost** [comment]
Got it, thanks!  I thought I can add some more comments quickly enough for it to not cause any confusion. Sorry about that. I only opened up a "bug" report because I really thought it was a bug. I'll start a new topic in discussions then. (Also, I mentioned `ielm` only because it's another lisp repl on emacs, which may or may not be using similar io, no clue.)
