### ISSUE TITLE
Problem with Sly in fennel (because of lisp-mode?)

### ISSUE THREAD

**Issue by xgqt** [joaotavora/sly#442]
(the same issue reposted in fennel-mode upstream: https://gitlab.com/technomancy/fennel-mode/-/issues/11#note_553979273)

I have a problem with company breaking in fennel-mode.

It's probably because of sly mode. I wonder if it breaks with Slime too. (apparently it does)

Any idea how to solve this?

![image](https://user-images.githubusercontent.com/47485207/115085375-f63a6700-9ef9-11eb-84fc-5922053ff705.png)

**Comment by joaotavora** [comment]
> Any idea how to solve this?

Ask the fennel-mode maintainer to not inherit from `lisp-mode`, which is for common lisp programs.  Or ask him to use a similar hack for SLY that he did from SLIME.

**Comment by xgqt** [comment]
> use lisp-data-mode and/or a make a major mode that uses the lisp-mode features you're interested in, much like clojure-mode. As with inheritance in general, only inherit from lisp-mode if you can guarantee the "is a" relationship.

Thanks for clearing this up.

**Comment by joaotavora** [comment]
no prob 👍
