### ISSUE TITLE
Change from manual completions buffer to automatic company-style tooltips at point?

### ISSUE THREAD

**Issue by nathanvy** [joaotavora/sly#443]
Hi,

Is it possible to achieve more "company-style" completion behaviour?

Current behaviour:  When working with lisp, stop typing half-way through a symbol and nothing happens.  Completion only works if you press C-c TAB (in the buffer) or just TAB in the REPL. 

Desired behaviour:  When working with e.g. python or C#, if I stop typing half-way through a symbol, company-mode automatically pops up a tooltip after a short delay with suggested completions.

Can I achieve the latter in sly?

**Comment by joaotavora** [comment]
Just install company and it should work. If it doesn't, it's likely because you've sei it up with some non-default settings.  Do you know what a minimal reproduction recipe is? If so, try and provide one here so I can help you, otherwise I'll try to show you later how company can be easily set up with sly.

**Comment by nathanvy** [comment]
I have company installed and set to global company mode.  Here is my config:  https://github.com/nathanvy/dotemacs/blob/master/init.org

You can see I haven't fiddled with the settings.

**Comment by joaotavora** [comment]
![Peek 2021-04-22 15-49](https://user-images.githubusercontent.com/387011/115735483-6c1f5200-a382-11eb-829e-c38fdbd2acbd.gif)

> You can see I haven't fiddled with the settings.
> For simplicity's sake I've copy-pasted the relevant sections below:

Thanks, but that's not what a minimal reproduction recipe is.  That's just a file that works for you. (or rather it doesn't work fully, but who knows why). A recipe is the set instructions for making a cake, along with where to get all the ingredients.  A minimal recipe needs very little ingredients to make a cake. So showing me that org file with lots of dependencies isn't going to make the cake for me.  The "cake" in this case being the problem 

There's something in your configuration that's preventing your setup from working as simply as I do here, where you can see ALL the configuration (becasue the `-Q` switch switches off all configuration).

**Comment by joaotavora** [comment]
(please don't make wholesale edits to your posts, it's confusing for whoever is following this)

**Comment by rprimus** [comment]
Sat Apr 24 09:25:03 BST 2021

```elisp
(use-package company
:hook (init-mode-hook . global-company-mode)
:mode "company-mode")
```

@nathanvy The problem is the `hook` line above: `-hook` is automatically added by the `use-package` macro.

The correct code would be:

```elisp
(use-package company
:hook (init-mode . global-company-mode)
:mode "company-mode")
```

Ref:
https://github.com/jwiegley/use-package/blame/a7422fb8ab1baee19adb2717b5b47b9c3812a84c/README.md#L342

> When using :hook omit the "-hook" suffix if you specify the hook explicitly, as this is appended by default.

**Comment by rprimus** [comment]
Sat Apr 24 09:38:55 BST 2021

## Additional  correction to previous:

There is no `init-mode-hook`.  The correct hook is `after-init-hook`, so the correct `use-package` stanza should be:

```elisp
(use-package company
:hook (after-init . global-company-mode)
:mode "company-mode")
```

**Comment by joaotavora** [comment]
aside/rant:  I personally think `use-package` 's opaque semantics (like those of many macros) are a cancer on the error-reporting scene.  What's worse is people seem to think it's the correct, recommended, or default way to configure packages.  It's not!  All that's needed in this case is:

```
(package-initialize)
(global-company-mode)
``` 

no `after-init` or `hook` thingamagigs. Yout don't need any hooks, but if you want to use hooks, use `add-hook` like the common mortal, makes life easier for the rest of us.
