### ISSUE TITLE
Repl output buffering bug

### ISSUE THREAD

**Issue by djeis97** [joaotavora/sly#456]
I can, somewhat consistently, confuse the repl output handling if I read and print quickly enough. e.g. `(princ (read-line))`. I get the return value back, but the printed output is hidden until something else prints.

![REPL output weirdness example](https://user-images.githubusercontent.com/2872315/125119104-9994b580-e0be-11eb-8ef4-1ae0a568da8f.png)

From what I can tell, this seems to trace back to a combination of `:set-read-mode` not flushing the output buffer on `:finished-reading` and socket weirdness. My guess is, emacs is processing the output from the dedicated output stream before it's responding to the set mode command. I can see in https://github.com/joaotavora/sly/commit/c90ce13c424e3429994b2efde8aa17428f16a8aa#diff-d711e81da282d4b3d7798e5d3641dad65d40f5ce19eee58ff5e75b7ef6db48afL230-L231 that there used to be handling in that method to flush the output buffer here but it was removed. However, I don't see any specific mention of why in the commit message. Perhaps this needs to be added again?

**Comment by joaotavora** [comment]
Thanks. What  platform, lisp, emacs, etc are you on?

**Comment by joaotavora** [comment]
reproduced

**Comment by joaotavora** [comment]
You analysis seems very accurate.

> Perhaps this needs to be added again?

Indeed, I can't remember why I took it out.  Perhaps I should be even _more_ verbose in my commit messages :sweat: .

Something tells me I took it out because of problematic newline handling, but I might be misremembering.  I'll add it back soon and you can test.

**Comment by djeis97** [comment]
When I was tinkering (before I went through the commit history) I actually added `(sly-mrepl--insert-output "")` and that seemed to fix it for me.

**Comment by joaotavora** [comment]
I think it needs to have the `"\n"` as an argument.  Otherwise a REPL inside a REPL won't work.  I.e. `(loop (princ (eval (read)))` should work correctly.  That is one of my first tests.  I don't understand why I didn't try it.

**Comment by djeis97** [comment]
Sorry about the emacs config/version/etc- my day-to-day is pretty messy and I was intending to try and reproduce in a cleaner environment before I reported on that.

**Comment by joaotavora** [comment]
So I fixed it according to your suggestion after some minor tests.  I'm not 100% confident that I haven't broken anything, this is always tricky stuff.

> Sorry about the emacs config/version/etc- my day-to-day is pretty messy 

Don't worry, I can say exactly the same ;-)

**Comment by djeis97** [comment]
Awesome, I'll test it out in a few hours.
