### ISSUE TITLE
faulty indentation after (ql:quickload :something)

### ISSUE THREAD

**Issue by danikino** [joaotavora/sly#459]
![Screenshot from 2021-07-20 03-02-11](https://user-images.githubusercontent.com/10066157/126269902-ca0378e7-c4f6-40a7-9433-957a422b86cb.png)
Hello, thanks for sly my favorite way to study common lisp.
As can be seen in the image after importing a module with ql:quickload
the indentation (that was working before) is lost.
What can be done to recover it ?
I'm working with emacs 28.0.50 with sbcl 2.1.6 on Ubuntu 20.04
Best to you .

**Comment by mdbergmann** [comment]
I can't replicate this exactly. This simple example works fine here.

But I have a similar symptom.
After starting plain SLY all works ok. Completion works and intendation in repl.
After I load `(asdf:load-system :cl-gserver/tests)` (one of the stuff I'm working on regularly) indentation doesn't work anymore and completion only after hitting TAB key.

**Comment by joaotavora** [comment]
Reproduced. I think this bug was re-introduced recently.  The `ql:quickload` output is interfering with the syntax.  Parenthesis matching is failing as well.

**Comment by joaotavora** [comment]
Unfortunately, the bug isn't 100% reproducible.  But I do believe this is related to the fix for #457 somehow
