### ISSUE TITLE
 update-indentation-information should not error when *emacs-connection*

### ISSUE THREAD

**Issue by Yehouda** [joaotavora/sly#470]
Currently, doing:
```
(ql:quickload "SLYNK/INDENTATION")
(ql:quickload "softdrink")
```
Gives an error (on Lispworks):
```
Error: NIL fell through ETYPECASE expression inside SLYNK::SEND-TO-INDENTATION-CACHE.
Wanted one of (SLYNK::SINGLETHREADED-CONNECTION SLYNK::MULTITHREADED-CONNECTION).
```
because \*emacs-connection\* is nil. It would be better if either  update-indentation-information or SLYNK::SEND-TO-INDENTATION-CACHE check and do nothing if there is no connection yet. 

In slynk/slynk.lisp.

The top frames on the stack are:
````
Call to ERROR
Call to SLYNK:UPDATE-INDENTATION-INFORMATION
Call to (SETF TRIVIAL-INDENT:INDENTATION)
```

**Comment by Yehouda** [comment]
There really isn't a "use case". We just run tests where we quickload "all" the systems in quicklisp (and when we can find them run their tests). As it happen "slynk/documentation" and "softdrink"  happen to be in the batch of systems. I "fixed" it by moving "softdrink" to another batch. 

I don't do any work on github, I just load things from quicklisp and rn them (and if they break check why).

**Comment by joaotavora** [comment]
OK, but what is your theory on why `softdrink` caused the error?  Can you perhaps post some more of that backtrace?  Thanks.
