### ISSUE TITLE
sly won't start with SBCL sbcl-sbcl-2.2.1-98-gaa92707b8-win-x86

### ISSUE THREAD

**Issue by roboticarm2000** [joaotavora/sly#501]
When starting sly in emacs I get the following error from the `*sly-started inferior-lisp for sbcl.exe*` buffer:

(cond ((ignore-errors (funcall 'require "asdf") (funcall (read-from-string "asdf:version-satisfies") (funcall (read-from-string "asdf:asdf-version")) "2.019")) (push (pathname "c:/Users/username/AppData/Roaming/.emacs.d/elpa/sly-20220131.1646/slynk/") (symbol-value (read-from-string "asdf:*central-registry*"))) (funcall (read-from-string "asdf:load-system") :slynk) (funcall (read-from-string "slynk:start-server") "c:/Users/username/AppData/Local/Temp/sly.8608")) (t (progn (load "c:/Users/username/AppData/Roaming/.emacs.d/elpa/sly-20220131.1646/slynk/slynk-loader.lisp" :verbose t) (funcall (read-from-string "slynk-loader:init")) (funcall (read-from-string "slynk:start-server") "c:/Users/username/AppData/Local/Temp/sly.8608"))))

* ; compiling file "c:/Users/username/AppData/Roaming/.emacs.d/elpa/sly-20220131.1646/slynk/backend/sbcl.lisp" (written 11 FEB 2022 09:48:57 PM):

; file: c:/Users/username/AppData/Roaming/.emacs.d/elpa/sly-20220131.1646/slynk/backend/sbcl.lisp
; in: DEFUN INPUT-READY-P
;     (SB-BSD-SOCKETS-INTERNAL::FD->HANDLE (SB-SYS:FD-STREAM-FD STREAM))
; 
; caught WARNING:
;   The function SB-BSD-SOCKETS-INTERNAL::FD->HANDLE has been deprecated as of SBCL version 1.2.10.
;   
;   In future SBCL versions SB-BSD-SOCKETS-INTERNAL::FD->HANDLE will signal a
;   runtime error.
;   See also:
;     The SBCL Manual, Node "Deprecation Conditions"

; in: DEFVAR *MAILBOXES*
;     (LIST)
; 
; note: deleting unreachable code

; wrote C:/Users/username/AppData/Local/cache/common-lisp/sbcl-sbcl-2.2.1-98-gaa92707b8-win-x86/c/Users/username/AppData/Roaming/.emacs.d/elpa/sly-20220131.1646/slynk/backend/sbcl-tmp7LQ0A0VI.fasl
; compilation finished in 0:00:03.088

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {23A80001}>:
  COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "slynk" "backend" "sbcl">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "slynk" "backend" "sbcl">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "slynk" "backend" "sbcl">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4:                                 Retry ASDF operation.
  5:                                 Retry ASDF operation after resetting the
                                     configuration.
  6: [ABORT                        ] Exit debugger, returning to top level.

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "slynk" "backend" "sbcl">)))
   source: (ERROR 'COMPILE-FILE-ERROR :CONTEXT-FORMAT CONTEXT-FORMAT
                  :CONTEXT-ARGUMENTS CONTEXT-ARGUMENTS)
0] 

This didn't happen with previous versions of SBCL.   

emacs version Emacs 27.2 (build 1, i686-w64-mingw32) of 2021-03-2
sbcl version sbcl-2.2.1-98-gaa92707b8-win-x86

**Comment by joaotavora** [comment]
Damn ASDF doesn't actually say what the error was. I'll try to look at this
in a windows computer, but u don't have that handy at the moment. In the
meantime, do the usual sanity checks like deleting the ASDF cache.

João

**Comment by roboticarm2000** [comment]
If it helps, I switch the inferior-lisp-program to sbcl 2.1.0 and got this error instead:

(cond ((ignore-errors (funcall 'require "asdf") (funcall (read-from-string "asdf:version-satisfies") (funcall (read-from-string "asdf:asdf-version")) "2.019")) (push (pathname "c:/Users/username/AppData/Roaming/.emacs.d/elpa/sly-20220131.1646/slynk/") (symbol-value (read-from-string "asdf:*central-registry*"))) (funcall (read-from-string "asdf:load-system") :slynk) (funcall (read-from-string "slynk:start-server") "c:/Users/username/AppData/Local/Temp/sly.9852")) (t (progn (load "c:/Users/username/AppData/Roaming/.emacs.d/elpa/sly-20220131.1646/slynk/slynk-loader.lisp" :verbose t) (funcall (read-from-string "slynk-loader:init")) (funcall (read-from-string "slynk:start-server") "c:/Users/username/AppData/Local/Temp/sly.9852"))))

This is SBCL 2.1.0, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* ; compiling file "c:/Users/username/AppData/Roaming/.emacs.d/elpa/sly-20220131.1646/slynk/backend/sbcl.lisp" (written 11 FEB 2022 10:09:58 PM):
; processing (DEFPACKAGE SLYNK-SBCL ...)
; processing (IN-PACKAGE SLYNK-SBCL)
; processing (REQUIRE (QUOTE SB-BSD-SOCKETS))
; processing (REQUIRE (QUOTE SB-INTROSPECT))
; processing (REQUIRE (QUOTE SB-POSIX))
; processing (REQUIRE (QUOTE SB-CLTL2))
; processing (DECLAIM (OPTIMIZE # ...))
; processing (DEFUN SBCL-WITH-NEW-STEPPER-P ...)
; processing (DEFUN SBCL-WITH-WEAK-HASH-TABLES ...)
; processing (DEFUN SBCL-WITH-XREF-P ...)
; processing (DEFUN SBCL-WITH-RESTART-FRAME ...)
; processing (DEFUN SBCL-WITH-SETF-INVERSE-META-INFO ...)
; processing (IMPORT-SLYNK-MOP-SYMBOLS :SB-MOP ...)
; processing (DEFUN SLYNK-MOP:SLOT-DEFINITION-DOCUMENTATION ...)
; processing (DEFIMPLEMENTATION GRAY-PACKAGE-NAME ...)
; processing (DEFMETHOD SB-GRAY:STREAM-LINE-LENGTH ...)
; processing (DEFIMPLEMENTATION LISP-IMPLEMENTATION-TYPE-NAME ...)
; processing (DECLAIM (FTYPE # ...))
; processing (DEFIMPLEMENTATION GETPID ...)
; processing (DEFIMPLEMENTATION STRING-TO-UTF8 ...)
; processing (DEFIMPLEMENTATION UTF8-TO-STRING ...)
; processing (DEFIMPLEMENTATION PREFERRED-COMMUNICATION-STYLE ...)
; processing (DEFUN RESOLVE-HOSTNAME ...)
; processing (DEFIMPLEMENTATION CREATE-SOCKET ...)
; processing (DEFIMPLEMENTATION LOCAL-PORT ...)
; processing (DEFIMPLEMENTATION CLOSE-SOCKET ...)
; processing (DEFIMPLEMENTATION ACCEPT-CONNECTION ...)
; processing (DEFIMPLEMENTATION ADD-FD-HANDLER ...)
; processing (DEFIMPLEMENTATION REMOVE-FD-HANDLERS ...)
; processing (DEFIMPLEMENTATION SOCKET-FD ...)
; processing (DEFIMPLEMENTATION COMMAND-LINE-ARGS ...)
; processing (DEFIMPLEMENTATION DUP ...)
; processing (DEFVAR *WAIT-FOR-INPUT-CALLED*)
; processing (DEFIMPLEMENTATION WAIT-FOR-INPUT ...)
; processing (DEFUN FD-STREAM-INPUT-BUFFER-EMPTY-P ...)
; processing (DEFUN INPUT-READY-P ...)
; file: c:/Users/username/AppData/Roaming/.emacs.d/elpa/sly-20220131.1646/slynk/backend/sbcl.lisp
; in: DEFUN INPUT-READY-P
;     (SB-BSD-SOCKETS-INTERNAL::FD->HANDLE (SB-SYS:FD-STREAM-FD STREAM))
; 
; caught WARNING:
;   The function SB-BSD-SOCKETS-INTERNAL::FD->HANDLE has been deprecated as of SBCL version 1.2.10.
;   
;   In future SBCL versions SB-BSD-SOCKETS-INTERNAL::FD->HANDLE will signal a
;   runtime error.
;   See also:
;     The SBCL Manual, Node "Deprecation Conditions"

; processing (SB-ALIEN:DEFINE-ALIEN-ROUTINE ("WSACreateEvent" WSA-CREATE-EVENT) ...)
; processing (SB-ALIEN:DEFINE-ALIEN-ROUTINE ("WSACloseEvent" WSA-CLOSE-EVENT) ...)
; processing (DEFCONSTANT +FD-READ+ ...)
; processing (DEFCONSTANT +FD-CLOSE+ ...)
; processing (SB-ALIEN:DEFINE-ALIEN-ROUTINE ("WSAEventSelect" WSA-EVENT-SELECT) ...)
; processing (SB-ALIEN:LOAD-SHARED-OBJECT "kernel32.dll")
; processing (SB-ALIEN:DEFINE-ALIEN-ROUTINE ("WaitForSingleObjectEx" WAIT-FOR-SINGLE-OBJECT-EX) ...)
; processing (DEFUN HANDLE-LISTEN ...)
; processing (DEFVAR *EXTERNAL-FORMAT-TO-CODING-SYSTEM* ...)
; processing (DEFVAR *PHYSICAL-PATHNAME-HOST* ...)
; processing (DEFIMPLEMENTATION FILENAME-TO-PATHNAME ...)
; processing (DEFIMPLEMENTATION FIND-EXTERNAL-FORMAT ...)
; processing (DEFIMPLEMENTATION SET-DEFAULT-DIRECTORY ...)
; processing (DEFUN MAKE-SOCKET-IO-STREAM ...)
; processing (DEFUN ACCEPT ...)
; processing (DEFUN FEATURE-IN-LIST-P ...)
; processing (DEFUN SHEBANG-READER ...)
; processing (DEFVAR *SHEBANG-READTABLE* ...)
; processing (DEFUN SHEBANG-READTABLE ...)
; processing (DEFUN SBCL-PACKAGE-P ...)
; processing (DEFUN SBCL-SOURCE-FILE-P ...)
; processing (DEFUN GUESS-READTABLE-FOR-FILENAME ...)
; processing (DEFVAR *DEBOOTSTRAP-PACKAGES* ...)
; processing (DEFUN CALL-WITH-DEBOOTSTRAPPING ...)
; processing (DEFMACRO WITH-DEBOOTSTRAPPING ...)
; processing (DEFIMPLEMENTATION CALL-WITH-SYNTAX-HOOKS ...)
; processing (DEFIMPLEMENTATION DEFAULT-READTABLE-ALIST ...)
; processing (DEFIMPLEMENTATION PACKAGE-LOCAL-NICKNAMES ...)
; processing (DEFUN SLYNK-VALUE ...)
; processing (DEFUN SBCL-VERSION>= ...)
; processing (DEFMACRO WITH-SBCL-VERSION>= ...)
; processing (DEFIMPLEMENTATION ARGLIST ...)
; processing (DEFIMPLEMENTATION FUNCTION-NAME ...)
; processing (DEFMETHOD DECLARATION-ARGLIST ...)
; processing (DEFMETHOD TYPE-SPECIFIER-ARGLIST ...)
; processing (DEFIMPLEMENTATION TYPE-SPECIFIER-P ...)
; processing (DEFVAR *BUFFER-NAME* ...)
; processing (DEFVAR *BUFFER-TMPFILE* ...)
; processing (DEFVAR *BUFFER-OFFSET*)
; processing (DEFVAR *BUFFER-SUBSTRING* ...)
; processing (DEFVAR *PREVIOUS-COMPILER-CONDITION* ...)
; processing (DEFUN HANDLE-NOTIFICATION-CONDITION ...)
; processing (DEFUN SIGNAL-COMPILER-CONDITION ...)
; processing (DEFUN REAL-CONDITION ...)
; processing (DEFUN CONDITION-REFERENCES ...)
; processing (DEFUN COMPILER-NOTE-LOCATION ...)
; processing (DEFUN COMPILING-FROM-BUFFER-P ...)
; processing (DEFUN COMPILING-FROM-FILE-P ...)
; processing (DEFUN COMPILING-FROM-GENERATED-CODE-P ...)
; processing (DEFUN LOCATE-COMPILER-NOTE ...)
; processing (DEFUN BRIEF-COMPILER-MESSAGE-FOR-EMACS ...)
; processing (DEFUN COMPILER-ERROR-CONTEXT ...)
; processing (DEFUN COMPILER-SOURCE-PATH ...)
; processing (DEFIMPLEMENTATION CALL-WITH-COMPILATION-HOOKS ...)
; processing (HANDLER-CASE (SB-EXT:RESTRICT-COMPILER-POLICY) ...)
; processing (DEFUN COMPILER-POLICY ...)
; processing (DEFUN (SETF COMPILER-POLICY) ...)
; processing (DEFMACRO WITH-COMPILER-POLICY ...)
; processing (DEFIMPLEMENTATION SLYNK-COMPILE-FILE ...)
; processing (SB-ALIEN:DEFINE-ALIEN-ROUTINE ("_tempnam" TEMPNAM) ...)
; processing (DEFUN TEMP-FILE-NAME ...)
; processing (DEFVAR *TRAP-LOAD-TIME-WARNINGS* ...)
; processing (DEFIMPLEMENTATION SLYNK-COMPILE-STRING ...)
; processing (DEFPARAMETER *DEFINITION-TYPES* ...)
; processing (DEFUN DEFINITION-SPECIFIER ...)
; processing (DEFUN MAKE-DSPEC ...)
; processing (DEFIMPLEMENTATION FIND-DEFINITIONS ...)
; processing (DEFIMPLEMENTATION FIND-SOURCE-LOCATION ...)
; processing (DEFMACRO WITH-DEFINITION-SOURCE ...)
; processing (DEFUN CATEGORIZE-DEFINITION-SOURCE ...)
; processing (DEFUN FORM-NUMBER-POSITION ...)
; processing (DEFUN FILE-FORM-NUMBER-POSITION ...)
; processing (DEFUN STRING-FORM-NUMBER-POSITION ...)
; processing (DEFUN DEFINITION-SOURCE-BUFFER-LOCATION ...)
; processing (DEFUN DEFINITION-SOURCE-FILE-LOCATION ...)
; processing (DEFUN DEFINITION-SOURCE-BUFFER-AND-FILE-LOCATION ...)
; processing (DEFUN DEFINITION-SOURCE-FOR-EMACS ...)
; processing (DEFUN SOURCE-FILE-POSITION ...)
; processing (DEFUN SOURCE-HINT-SNIPPET ...)
; processing (DEFUN FUNCTION-SOURCE-LOCATION ...)
; processing (DEFUN SETF-EXPANDER ...)
; processing (DEFIMPLEMENTATION DESCRIBE-SYMBOL-FOR-EMACS ...)
; processing (DEFIMPLEMENTATION DESCRIBE-DEFINITION ...)
; processing (DEFMACRO DEFXREF ...)
; processing (DEFXREF WHO-CALLS)
; processing (DEFXREF WHO-BINDS)
; processing (DEFXREF WHO-SETS)
; processing (DEFXREF WHO-REFERENCES)
; processing (DEFXREF WHO-MACROEXPANDS)
; processing (DEFXREF WHO-SPECIALIZES ...)
; processing (DEFUN SOURCE-LOCATION-FOR-XREF-DATA ...)
; processing (DEFIMPLEMENTATION LIST-CALLERS ...)
; processing (DEFIMPLEMENTATION LIST-CALLEES ...)
; processing (DEFUN SANITIZE-XREFS ...)
; processing (DEFUN IGNORED-XREF-FUNCTION-NAMES ...)
; processing (DEFUN FUNCTION-DSPEC ...)
; processing (DEFIMPLEMENTATION MACROEXPAND-ALL ...)
; processing (DEFUN MAKE-INVOKE-DEBUGGER-HOOK ...)
; processing (DEFUN SET-BREAK-HOOK ...)
; processing (DEFUN CALL-WITH-BREAK-HOOK ...)
; processing (DEFIMPLEMENTATION INSTALL-DEBUGGER-GLOBALLY ...)
; processing (DEFIMPLEMENTATION CONDITION-EXTRAS ...)
; processing (DEFUN EXTERNALIZE-REFERENCE ...)
; processing (DEFVAR *SLY-DB-STACK-TOP*)
; processing (DEFIMPLEMENTATION CALL-WITH-DEBUGGING-ENVIRONMENT ...)
; processing (DEFIMPLEMENTATION ACTIVATE-STEPPING ...)
; processing (DEFIMPLEMENTATION SLY-DB-STEPPER-CONDITION-P ...)
; processing (DEFIMPLEMENTATION SLY-DB-STEP-INTO ...)
; processing (DEFIMPLEMENTATION SLY-DB-STEP-NEXT ...)
; processing (DEFIMPLEMENTATION SLY-DB-STEP-OUT ...)
; processing (DEFIMPLEMENTATION CALL-WITH-DEBUGGER-HOOK ...)
; processing (DEFUN NTH-FRAME ...)
; processing (DEFIMPLEMENTATION COMPUTE-BACKTRACE ...)
; processing (DEFIMPLEMENTATION PRINT-FRAME ...)
; processing (DEFIMPLEMENTATION FRAME-RESTARTABLE-P ...)
; processing (DEFIMPLEMENTATION FRAME-ARGUMENTS ...)
; processing (DEFUN CODE-LOCATION-SOURCE-LOCATION ...)
; processing (DEFUN FILE-SOURCE-LOCATION ...)
; processing (DEFUN FALLBACK-SOURCE-LOCATION ...)
; processing (DEFUN LISP-SOURCE-LOCATION ...)
; processing (DEFUN EMACS-BUFFER-SOURCE-LOCATION ...)
; processing (DEFUN SOURCE-FILE-SOURCE-LOCATION ...)
; processing (DEFUN CODE-LOCATION-DEBUG-SOURCE-NAME ...)
; processing (DEFUN CODE-LOCATION-DEBUG-SOURCE-CREATED ...)
; processing (DEFUN CODE-LOCATION-DEBUG-FUN-FUN ...)
; processing (DEFUN CODE-LOCATION-HAS-DEBUG-BLOCK-INFO-P ...)
; processing (DEFUN STREAM-SOURCE-POSITION ...)
; processing (DEFUN STRING-SOURCE-POSITION ...)
; processing (DEFIMPLEMENTATION FRAME-SOURCE-LOCATION ...)
; processing (DEFVAR *KEEP-NON-VALID-LOCALS* ...)
; processing (DEFUN FRAME-DEBUG-VARS ...)
; processing (DEFUN DEBUG-VAR-VALUE ...)
; processing (DEFUN DEBUG-VAR-INFO ...)
; processing (DEFIMPLEMENTATION FRAME-LOCALS ...)
; processing (DEFIMPLEMENTATION FRAME-VAR-VALUE ...)
; processing (DEFIMPLEMENTATION FRAME-CATCH-TAGS ...)
; processing (DEFIMPLEMENTATION EVAL-IN-FRAME ...)
; processing (DEFIMPLEMENTATION FRAME-PACKAGE ...)
; processing (DEFIMPLEMENTATION RETURN-FROM-FRAME ...)
; processing (DEFIMPLEMENTATION RESTART-FRAME ...)
; processing (DEFIMPLEMENTATION PRINT-CONDITION ...)
; processing (DEFIMPLEMENTATION PROFILE ...)
; processing (DEFIMPLEMENTATION UNPROFILE ...)
; processing (DEFIMPLEMENTATION UNPROFILE-ALL ...)
; processing (DEFIMPLEMENTATION PROFILE-REPORT ...)
; processing (DEFIMPLEMENTATION PROFILE-RESET ...)
; processing (DEFIMPLEMENTATION PROFILED-FUNCTIONS ...)
; processing (DEFIMPLEMENTATION PROFILE-PACKAGE ...)
; processing (DEFMETHOD EMACS-INSPECT ...)
; processing (DEFMETHOD EMACS-INSPECT ...)
; processing (DEFMETHOD EMACS-INSPECT ...)
; processing (DEFMETHOD EMACS-INSPECT ...)
; processing (DEFMETHOD EMACS-INSPECT ...)
; processing (DEFMETHOD EMACS-INSPECT ...)
; processing (DEFVAR *THREAD-ID-COUNTER* ...)
; processing (DEFVAR *THREAD-ID-COUNTER-LOCK* ...)
; processing (DEFUN NEXT-THREAD-ID ...)
; processing (DEFVAR *THREAD-ID-MAP* ...)
; processing (DEFVAR *THREAD-ID-MAP-LOCK* ...)
; processing (DEFIMPLEMENTATION SPAWN ...)
; processing (DEFIMPLEMENTATION THREAD-ID ...)
; processing (DEFIMPLEMENTATION FIND-THREAD ...)
; processing (DEFIMPLEMENTATION THREAD-NAME ...)
; processing (DEFIMPLEMENTATION THREAD-STATUS ...)
; processing (DEFIMPLEMENTATION MAKE-LOCK ...)
; processing (DEFIMPLEMENTATION CALL-WITH-LOCK-HELD ...)
; processing (DEFIMPLEMENTATION CURRENT-THREAD ...)
; processing (DEFIMPLEMENTATION ALL-THREADS ...)
; processing (DEFIMPLEMENTATION INTERRUPT-THREAD ...)
; processing (DEFIMPLEMENTATION KILL-THREAD ...)
; processing (DEFIMPLEMENTATION THREAD-ALIVE-P ...)
; processing (DEFVAR *MAILBOX-LOCK* ...)
; processing (DEFVAR *MAILBOXES* ...)
; processing (DECLAIM (TYPE LIST ...))
; processing (DEFSTRUCT (MAILBOX #) ...)
; processing (DEFUN MAILBOX ...)
; processing (DEFIMPLEMENTATION WAKE-THREAD ...)
; processing (DEFIMPLEMENTATION SEND ...)
; processing (DEFIMPLEMENTATION RECEIVE-IF ...)
; processing (LET (# #) ...)
; processing (DEFIMPLEMENTATION QUIT-LISP ...)
; processing (DEFUN TOGGLE-TRACE-AUX ...)
; processing (DEFUN PROCESS-FSPEC ...)
; processing (DEFIMPLEMENTATION TOGGLE-TRACE ...)
; processing (DEFIMPLEMENTATION MAKE-WEAK-KEY-HASH-TABLE ...)
; processing (DEFIMPLEMENTATION MAKE-WEAK-VALUE-HASH-TABLE ...)
; processing (DEFIMPLEMENTATION HASH-TABLE-WEAKNESS ...)
; processing (DEFIMPLEMENTATION FLOAT-NAN-P ...)
; processing (DEFIMPLEMENTATION FLOAT-INFINITY-P ...)
; processing (DEFIMPLEMENTATION MAKE-FD-STREAM ...)
; processing (PUSHNEW (QUOTE DEINIT-LOG-OUTPUT) ...)
; processing (DEFIMPLEMENTATION WRAP ...)
; processing (DEFIMPLEMENTATION UNWRAP ...)
; processing (DEFIMPLEMENTATION WRAPPED-P ...)
; processing (DEFUN SBCL-WRAP ...)
; processing (DEFMETHOD SEXP-IN-BOUNDS-P ...)
; processing (DEFMETHOD SEXP-REF ...)

; wrote C:/Users/username/AppData/Local/cache/common-lisp/sbcl-2.1.0-win-x86/c/Users/username/AppData/Roaming/.emacs.d/elpa/sly-20220131.1646/slynk/backend/sbcl-tmp7LQ0A0VI.fasl
; compilation finished in 0:00:04.192

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {23A50001}>:
  COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "slynk" "backend" "sbcl">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "slynk" "backend" "sbcl">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "slynk" "backend" "sbcl">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4:                                 Retry ASDF operation.
  5:                                 Retry ASDF operation after resetting the
                                     configuration.
  6: [ABORT                        ] Exit debugger, returning to top level.

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "slynk" "backend" "sbcl">)))
   error finding frame source: Bogus form-number: the source file has probably
                               changed too much to cope with.
   source: NIL
0] 

As a comparison, SLIME works fine on both versions.  Hope this helps.

**Comment by roboticarm2000** [comment]
Now I'm wondering if it has to do with sly-20220131.1646 vs the previous version before I upgraded from Melpa :/

**Comment by joaotavora** [comment]
interesting.  Can you try with SLY's commit 2e00c3bd4bdf6658f258cc78b3254f0ec24591e5, before @daewok 's fix of #492 was merged?

**Comment by daewok** [comment]
This is definitely due to #492. Prior to that, *every* compilation warning was suppressed. I didn't catch this because it's a warning that's only produced on Windows.

It seems that `fd->handle` has been deprecated since SBCL 1.2.10. It's been the identity function since SBCL 1.1.2.

@joaotavora Would you like this warning to be muffled as well? Or should we remove the use of `fd->handle` ?

**Comment by joaotavora** [comment]
> @joaotavora Would you like this warning to be muffled as well? Or should we remove the use of fd->handle ?

What do you think?  I think that -- if you have Windows debugging capability -- then removing this warning is the and re-testing is definitely a nice thing.

But I also wonder if we shouldn't get back to muffling some warnings (but perhaps still print them).

**Comment by daewok** [comment]
@roboticarm2000 #502 should fix this. Can you give it a try to confirm?

**Comment by roboticarm2000** [comment]
502 fixed it.   Thanks!
