### ISSUE TITLE
Sly uses keybindings of the form "C-c letter" which are reserved for users

### ISSUE THREAD

**Issue by oantolin** [joaotavora/sly#526]
The default bindings for all of these:

- `sly-trace-dialog`
- `sly-import-symbol-at-point`
- `sly-export-symbol-at-point`
- `sly-inspect`
- `sly-edit-value`

are of the form `C-c` followed by a *letter* and the manual asks that packages refrain from using those bindings as they are reserved for users. Major modes are free to use the `C-c` prefix as long as they follow it with a key that is *not* a letter, in particular `C-c C-letter` or `C-c M-letter` are fine for major modes to use.

**Comment by joaotavora** [comment]
Yes, there was recently an issue complaining of the same. These were inherited from SLIME and are in the muscle memory of many long-time users such as me. So, you're right, but "won't fix".

**Comment by oantolin** [comment]
OK. They are of course easy to rebind in users's personal configuration anyway. Thanks for considering the issue!

**Comment by oantolin** [comment]
To get rid of the bindings for `sly-import/export-symbol-at-point` I wound up advising the function `sly-package-fu-init`. I wonder if there is a better way.
