### ISSUE TITLE
abcl not working

### ISSUE THREAD

**Issue by tdangerimp** [joaotavora/sly#537]
abcl not working. never connects.  sbcl works fine, though. I even tried doing a make-server-socket on a manually started abcl and then doing sly-connect and that didn't work either. Is there any material on how to troubleshoot connecting to a lisp?  I'm not finding. Thanks.

**Comment by joaotavora** [comment]
I think there's a pull request here somewhere significantly updating abcl
support. You may test that perhaps.

**Comment by joaotavora** [comment]
I just merged a PR that presumably fixes ABCL support in #485.  I haven't tested myself, as I don't have ABCL, but please do try it out and comment here.  If it doesn't work, I'll reopen the issue.
