### ISSUE TITLE
sly-db-invoke-restart-by-name fails because it tries to use unknown 'first instead of #'cl-first

### ISSUE THREAD

**Issue by gav451** [joaotavora/sly#580]
The patch [fix-sly-db-invoke-restart-by-name.patch](https://github.com/joaotavora/sly/files/11078909/fix-sly-db-invoke-restart-by-name.patch) fixes the bug.

**Comment by joaotavora** [comment]
Thanks, please submit this as a pull request!

**Comment by joaotavora** [comment]
Thanks, please submit this as a pull request (if possible).

**Comment by joaotavora** [comment]
Thanks, please submit this as a pull request (if possible).

**Comment by joaotavora** [comment]
Thanks!
