### ISSUE TITLE
Comma shortcut breaks down after a crash

### ISSUE THREAD

**Issue by PuercoPop** [joaotavora/sly#59]
After crashing the inferior lisp (sbcl in my case) the `, restart` shortcut breaks down, failing to restart the inferior-lisp an subsequent attemps to use the , shortcut fail as the process is nil.

**Comment by capitaomorte** [comment]
By "crashing the inferior lisp", do you mean having the debugger come up? Or like externally killing the process? 

In the latter case (where I `killall sbcl` from the terminal) I have indeed just seen the comma shortcut fail, but I would like to reproduce exactly your situation.

**Comment by PuercoPop** [comment]
I mean ldb being invoked. Currently running `(asdf:test-system :djula)` triggers a heap exahustion error you could try to reproduce it that way?.

**Comment by joaotavora** [comment]
Hey @PuercoPop, I'm going through the issues here and closing this one. I know this is ancient, but I just tested with:
```
kill -ABRT `pidof sbcl`
```
which causes `ldb` to popup. The command shortcut worked fine in the REPL and I was able to restart my lisp.

Let me know if you do still have this problem, though...
