### ISSUE TITLE
Connecting ad infinitum

### ISSUE THREAD

**Issue by Ikuyu** [joaotavora/sly#594]
No matter what I try, Sly keeps connecting ad infinitum.

I've reinstalled macOS Ventura on my MacBook Air M1, using this configuration in my emacs init:

(use-package sly
  :config
  (setq sly-net-coding-system 'utf-8-unix
        ;;sly-mrepl-pop-sylvester nil
        sly-contribs '(sly-fancy)
	inferior-lisp-program "clisp -q -ansi -modern -I -on-error abort"))

If I change the line:

inferior-lisp-program "clisp -q -ansi -modern -I -on-error abort"

to this:

 inferior-lisp-program "sbcl"

Sly connects. However I also had to manually add a history file:

$ touch ~/.sly-mrepl-history

What am I missing?

**Comment by jcguu95** [comment]
1. What happen if you run `clisp -q -ansi -modern -I -on-error abort` in your terminal?
2. If you didn't manually add a history file, what would happen?

**Comment by Ikuyu** [comment]
1. If I run `clisp -q -ansi -modern -I -on-error abort` from the terminal everything works as expected. The REPL loads fine.
2. If I run `M-x sly` without a history file, Sly says 'Cannot read history file...' (that is... if a choose SBCL as inferior lisp program). But if I choose CLISP, Sly keeps polling ad infinitum, whether a history file is present or not.

**Comment by LdBeth** [comment]
likely because of #595

**Comment by Ikuyu** [comment]
This helps, but now I get the message: 

Waiting for REPL creation ack for channel 1...
; Dedicated output stream setup (port 52013)
; Redirecting all output to this MREPL
*** - no-applicable-method: When calling
      #<standard-generic-function slynk-gray::reset-stream-line-column> with
      arguments (#<io unbuffered socket-stream character 127.0.0.1:52013>), no
      method is applicable.
cs-user> 

And the buffer is read-only.

**Comment by joaotavora** [comment]
This is with `clisp`, right?

**Comment by Ikuyu** [comment]
Yes this is with `clisp`.
