### ISSUE TITLE
Typo that prevents non SBCL lisps from starting slynk

### ISSUE THREAD

**Issue by LdBeth** [joaotavora/sly#595]
https://github.com/joaotavora/sly/blob/fa3bcf0237b420d1a3b1670eb35d7c5f96f94c62/slynk/slynk.lisp#L3222

This should be `slynk-mop:` instead of `sb-mop:`.

**Comment by joaotavora** [comment]
Thanks! Sorry about that, will fix in a minute.

**Comment by Ikuyu** [comment]
[
<img width="570" alt="Screenshot 2023-05-19 at 13 11 53" src="https://github.com/joaotavora/sly/assets/57272868/d74dd747-3955-4dc9-aaee-c783cef0e5a7">
](url)

**Comment by joaotavora** [comment]
?

**Comment by Ikuyu** [comment]
That's what I get after applying the fix locally on my machine.

**Comment by joaotavora** [comment]
I don't have your machine. It is yours. Please read CONTRIBUTING.md and  make a proper report and thanks in advance.

**Comment by LdBeth** [comment]
@Ikuyu apparently the CLISP backend suffers from bit rotten. I don't have CLISP so cannot do the troubleshoot myself, but after inspecting the source code of slynk I believe it is caused by a CLISP native stream class instead of `sly-output-stream` is been used. Hopefully this is enough hint for you to find the root of the cause.

But I would propose a simple workaround to change the function definition of `flush-listener-streams` in `slynk.lisp` to
```
(defun flush-listener-streams (listener)
  (with-slots (in out) listener
    (force-output out)
    #-(or armedbear lisp)
    (slynk-gray::reset-stream-line-column out)
    (clear-input in)))
```

**Comment by Ikuyu** [comment]
Your suggestion actually works.

Thank you!

--

**Comment by joaotavora** [comment]
I think I will implement something like this or similar.  See also #600
