### ISSUE TITLE
slynk not connected

### ISSUE THREAD

**Issue by lewisl** [joaotavora/sly#604]
I am on MacBook Pro M1 Max running Ventura.  Up to date Sublime Text 4. 

Installed the Slyblime plugin.  Ran upgrade to Python 3.8, which seemed to complete successfully.

Changed settings for inferior lisp to:
```
  "inferior_lisp_process": {
    "command": ["sbcl"],
    "autoclose": true,
    "loading_time": 3,
    "setup_time": 3
  },
```

Then run Sly: Start and connect to an inferior lisp instance.

It's hard to tell if anything happens.  There is no feedback at all in the sublime UI that anything has happened.  Activity Monitor shows that an sbcl instance has started.

Then in a tiny little .lisp file I try to run from the context menu: Sly/Compile top-level at cursor.  Status bar says "Slynk not connected."  Is there some way to tell if installing the plugin really installed Slynk.  I am not very good at sbcl yet so I don't know what to run in sbcl to see what is running.  I has asdf but don't know if that will tell me anything.

Since everything depends on Slynk nothing at all works.

I have no idea how to diagnose this.

**Comment by joaotavora** [comment]
Sorry, I don't have sublime text or a mac handy.  You have to report this to Slyblime. As far as I know Slyblime uses part of SLY (the Slynk server), but that's about all I know. We can ping @s-clerc here, but I'll close this for now since I can't give support to anything other than SLY/Emacs.

**Comment by lewisl** [comment]
OK.  have done...
