### ISSUE TITLE
Keybinds: C-c <letter> are reserved for users.

### ISSUE THREAD

**Issue by toddkfisher** [joaotavora/sly#605]
From the  Emacs docs (D.2):

> Don’t define C-c letter as a key in Lisp programs. Sequences consisting of C-c and a letter (either upper or lower case; ASCII or non- ASCII) are reserved for users; they are the only sequences reserved for users, so do not block them. Changing all the Emacs major modes to respect this convention was a lot of work; abandoning this convention would make that work  go to waste, and inconvenience users. Please comply with it.

Sly binds **C-c i** to `sly-import-symbol-at-point` by default.  There may be other Sly keybindings: **C-c** _letter_.

**Comment by joaotavora** [comment]
Dups #526

**Comment by toddkfisher** [comment]
That's okay.  I can totally understand how your muscle-memory is more important than following guidelines set forth in the Emacs manual.

**Comment by joaotavora** [comment]
Thanks for understanding :-)
