### ISSUE TITLE
How to disable that the REPL start with a drawing (Sylvester) 

### ISSUE THREAD

**Issue by E3D3** [joaotavora/sly#624]
How can I disable the ASCII art drawings when the REPL start ?

**Comment by joaotavora** [comment]
`(setq sly-mrepl-pop-sylvester nil)`

**Comment by wasamasa** [comment]
Wait, wait. Why is this a `defvar` and not a `defcustom`?

**Comment by joaotavora** [comment]
because only heartless cynics would want to customize those dear creatures away.  or dog people I guess.

**Comment by joaotavora** [comment]
sorry, sorry I make a mistake.  the exact demographic would be "dog people without a .emacs"

**Comment by E3D3** [comment]
Thanks.
I love cats but not in front of me when I'm working. It scares the mouse.
