### ISSUE TITLE
I have developed a simple way to search Common Lisp symbols with SLY; merge into this package or keep separate? 

### ISSUE THREAD

**Issue by enzuru** [joaotavora/sly#627]
Hi, I developed a way to search Common Lisp symbols with SLY and `completing-read`:

https://github.com/enzuru/completing-read-sly

This allows you to search through Common Lisp symbols like you can do with Emacs Lisp symbols with Ivy, vert&co, etc. This is particularly helpful for such a gigantic language like Common Lisp! The only requirement is SLY.

My plan was to publish this as a separate extension for each major Lisp IDE (Geiser + SLY + CIDER), but MELPA wanted me to see if I could submit them upstream instead:

https://github.com/melpa/melpa/pull/8850#issuecomment-1853495227

Is SLY interested in having this functionality, or should I maintain a separate package?

**Comment by enzuru** [comment]
Very simply, I can search a Clojure symbol that is defined by name, and then select it to get documentation. With something like Ivy or Vert&co (which puts completing-read on steroids), I can fuzzy search said name. Here is a picture.

![sly](https://github.com/joaotavora/sly/assets/723711/e752a9b5-704a-45b5-abe7-d8bb17029207)

By using completing-read, I can be mostly agnostic to the completion framework you use, even if you use none. (Not sure if Helm supports completing-read yet though...)

**Comment by enzuru** [comment]
Looks like I am just going to write a blog post about this instead, thanks

**Comment by joaotavora** [comment]
Good idea. The problem with apropos-list is that the list can be enormous, and transferring it to Emacs will take a heck of a long time. Other SLY methods don't have this problem (at least I worked to solve it in the past).
