### ISSUE TITLE
fails to load

### ISSUE THREAD

**Issue by Devon7** [joaotavora/sly#651]
Are all packages this stupidly impossible to load, or is it just sly?
```

$ LANG=C /Applications/Emacs-29.3.app/Contents/MacOS/Emacs-x86_64-10_14 --no-init-file --no-site-file --no-site-lisp

;;; Type q to quit the splash screen and switch to the *scratch* buffer

(list-packages)
;; ⋮
;;   sly                            1.0.43         installed             Sylvester the Cat's Common Lisp IDE
;; ⋮

(sly) ;; Debugger entered--Lisp error: (void-function sly)

(sly-mrepl-new) ;; Debugger entered--Lisp error: (void-function sly-mrepl-new)

(use-package "sly") ;;  ■  Error (use-package): Cannot load sly
t

(apropos "sly") ;;; nothing relevant

(package-install "sly") ;; Debugger entered--Lisp error: (error "Package ‘sly’ is unavailable")

(emacs-version)
"GNU Emacs 29.3 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G9323))
 of 2024-03-24"

(push "~/.emacs.d/elpa/sly-1.0.43/" load-path)
("~/.emacs.d/elpa/sly-1.0.43/" "/Applications/Emacs-29.3.app/Contents/Resources/lisp" "/Applications/Emacs-29.3.app/Contents/Resources/lisp/vc" "/Applications/Emacs-29.3.app/Contents/Resources/lisp/use-package" "/Applications/Emacs-29.3.app/Contents/Resources/lisp/url" "/Applications/Emacs-29.3.app/Contents/Resources/lisp/textmodes" "/Applications/Emacs-29.3.app/Contents/Resources/lisp/progmodes" "/Applications/Emacs-29.3.app/Contents/Resources/lisp/play" "/Applications/Emacs-29.3.app/Contents/Resources/lisp/org" "/Applications/Emacs-29.3.app/Contents/Resources/lisp/nxml" "/Applications/Emacs-29.3.app/Contents/Resources/lisp/net" "/Applications/Emacs-29.3.app/Contents/Resources/lisp/mh-e" ...)

(use-package "sly") ;; Loading sly...done
nil

(sly)
#<buffer *sly-started inferior-lisp for lisp*>
;;	; 
;;	;     |,\__/|
;;	;     |  o o|
;;	;     (   T )    May the source be with you!
;;	;    .^`--^'^.
;;	;    `.  ;  .'
;;	;    | | | | |
;;	;   ((_((|))_))
;;	;              hjw
;;	; 
;;	; Dedicated output stream setup (port 51452)
;;	; Redirecting all output to this MREPL
;;	; SLY 1.0.43 (#<MREPL mrepl-1-1>)
;;	CL-USER> 
```

**Comment by joaotavora** [comment]
Dunno, I think the problem is mostly idiots who can't read READMEs

**Comment by Devon7** [comment]
Sorry, the README is inadequate.  Let's hope this example will be helpful to others.

**Comment by joaotavora** [comment]
This is the most useless example I've ever seen.  What are you trying to do? You're not even initializing the package system

**Comment by monnier** [comment]
> Are all packages this stupidly impossible to load, or is it just sly?

AFAICT your problems are not related to Sly and indeed would apply to
all packages.  I suggest you file this as an Emacs bug instead.

But please try and explain why you're doing this.  E.g. Why did you
start Emacs with `--no-init-file --no-site-file --no-site-lisp`?
Why did you expect your user-installed packages to be activated despite
those command line options?

> (package-install "sly") ;; Debugger entered--Lisp error: (error "Package ‘sly’ is unavailable")

IIRC the problem here is that the error is misleading: it's not that the
package is unavailable but that the argument should be a symbol rather
than a string.

**Comment by Devon7** [comment]
Normally, "initializing the package system" is done automatically when Emacs starts, but disabling initializations (necessary for identifying bugs) breaks it (smells like a bug to me but now I know) - thanks, problem solved!

		Peace
			--Devon

P.S.  What I'm trying to do, is get lisp prompts.
If sly has other uses, do tell.

P.P.S.  I reported the string/symbol issue to bug-gnu-emacs

**Comment by joaotavora** [comment]
> Normally, "initializing the package system" is done automatically when Emacs starts,

Not if you actively prevent it from happening.  Then you have to add `-f package-initialize`

> If sly has other uses, do tell.

Apparently its bug tracker is good for embarrassing jackasses.

**Comment by monnier** [comment]
> Normally, "initializing the package system" is done automatically when
> Emacs starts, but disabling initializations (necessary for identifying
> bugs) breaks it (smells like a bug to me but now I know)

There are pros and cons, yes 🙁
You can "get what you want" with

    emacs -Q -f package-activate-all

FWIW, usually, when I need to isolate bugs, I like to be more precise, so I do

    emacs -Q -l ~/.emacs.d/elpa/<PKG1>-<VERS1>/<PKG1>-autoloads.el \
             -l ~/.emacs.d/elpa/<PKG2>-<VERS2>/<PKG2>-autoloads.el \
             ...

which only activates the specified packages (and doesn't eagerly
loads them).

**Comment by monnier** [comment]
> Not if you actively prevent it from happening.  Then you have to add
> `-f package-initialize`

Please don't.  This initializes another part of the package system (the
part responsible for downloading, installing, and uninstalling
packages, which incidentally should be initialized automatically when
needed so you should never need to explicitly call `package-initialize`).

`package-activate-all` is the function used during the normal
startup sequence.


        Stefan

**Comment by joaotavora** [comment]
Noted.  Make that `-f package-activate-all` 

(though `-Q -f package-initialize` has worked fine for me)

**Comment by monnier** [comment]
> Noted.  Make that `-f package-activate-all` 
> (though `-Q -f package-initialize` has worked fine for me)

Yes, it works as well.  And in some past it was the only option.
But `package-initialize` does more and is hence less well adapted to
a minimal setup to reproduce a bug (and it's slower, to boot).
