### ISSUE TITLE
Polling '/tmp/sly.5125' indefinitely

### ISSUE THREAD

**Issue by HectareaGalbis** [joaotavora/sly#661]
I was using sly normally. It was working out of the box. I don't know what I did exactly, but after restarting the lisp process sly is now unable to start. I see the next message:

```
...
[sly] Polling "/tmp/sly.5125" .. 57 (Abort with `M-x sly-abort-connection'.)
[sly] Polling "/tmp/sly.5125" .. 58 (Abort with `M-x sly-abort-connection'.)
[sly] Polling "/tmp/sly.5125" .. 59 (Abort with `M-x sly-abort-connection'.)
[sly] Polling "/tmp/sly.5125" .. 60 (Abort with `M-x sly-abort-connection'.)
[sly] Polling "/tmp/sly.5125" .. 61 (Abort with `M-x sly-abort-connection'.)
[sly] Cancelled connection attempt.  // <-- Evaluated 'sly-abort-connection'
```

What I did see is that the error only occurs when trying to use SBCL (the lisp I was using). I can still open sly with other lisp like CLISP.

The file `/tmp/sly.5125` doesn't exist on my computer even when sly is trying to start. 

I reinstalled sly with `use-package` and even I restarted my computer but the problem persists.

**Comment by HectareaGalbis** [comment]
After a while, sly is connecting correctly again. I don't know waht happened. Sorry if this issue was useless.

**Comment by aadcg** [comment]
You can look at the inferior lisp buffer in those cases.
