### ISSUE TITLE
Import `slime-asdf` into `sly-asdf`

### ISSUE THREAD

**Issue by joaotavora** [joaotavora/sly#75]
See #71 for a description and a discussion.

**Comment by mmgeorge** [comment]
FYI, I ported `slime-asdf` as an external contrib [here](https://github.com/mmgeorge/sly-asdf)

**Comment by svetlyak40wt** [comment]
@mmgeorge I think it will be great to create an "External contribs" section in SLY's README.md

What do you think?

**Comment by joaotavora** [comment]
This can be done, yes. If there are at least two or three

**Comment by svetlyak40wt** [comment]
I know at least these two:

* https://github.com/joaotavora/sly-named-readtables
* https://github.com/40ants/sly-package-inferred

With sly-asdf it already three!

I'll make a pull request now!

**Comment by svetlyak40wt** [comment]
I also have not published yet sly-log4cl (in WIP status).

Oh, and found a https://github.com/joaotavora/sly-quicklisp!

**Comment by svetlyak40wt** [comment]
Done!

Here is the pull: https://github.com/joaotavora/sly/pull/225

**Comment by mmgeorge** [comment]
@svetlyak40wt sounds good! Thanks

**Comment by svetlyak40wt** [comment]
This issue should be closed now, because https://github.com/joaotavora/sly/pull/225 was merged.
