### ISSUE TITLE
Running code that calls `READ` from non-interactive `sly-eval`

### ISSUE THREAD

**Issue by ryukinix** [joaotavora/sly#80]
When I use lisp eval with some code whose use `(read)` in some place are expected to receive the input... and this okay.  But which place I can write this? I try on the sly REPL and doesn't works. How I do proceed that?

On the first try I get — after running some expression with (read) — at minibuffer:
`[sly] Listener waiting for input to read`

Nice, but if I try write the input on REPL: 
![erro-delicioso](https://cloud.githubusercontent.com/assets/7642878/13378401/e9dee85a-dde3-11e5-8ffc-f10d12ebfc4e.png)

Later, I try eval something again and got:
`[sly] Some output saved for later insertion`

And, more worst yet, a annoying part if I try interrupt command <kbd>C-c C-b </kbd> I got a [crazy error](http://i.imgur.com/YhqlsK8.png). In the end I have to restart the sly.

**Comment by capitaomorte** [comment]
Hmm interesting. I'll have a look as soon as I can.

**Comment by capitaomorte** [comment]
To interact with a program that uses `read`, you should run this program in a REPL. 

That is an interactive interface, but the direct evaluation of a form in a lisp buffer is not.

I assume you're trying to eval the expression directly. I don't think that will work, but I will investigate.

This works.

```
CL-USER> (defun add-five ()
           (print "Please enter a number:")
           (let ((num (read)))
             (print "When I add five I got")
             (print (+ num 5))))
WARNING: redefining COMMON-LISP-USER::ADD-FIVE in DEFUN
ADD-FIVE
CL-USER> (add-five)

"Please enter a number:" 3

"When I add five I got" 
8 
8
CL-USER> (add-five)

"Please enter a number:" 123

"When I add five I got" 
128 
128
CL-USER> (add-five)

"Please enter a number:" 'something


"When I add five I got" 
; Debugger entered on #<SIMPLE-TYPE-ERROR expected-type: NUMBER datum: 'SOMETHING>
[1] CL-USER> 
```

At this point, if I quit the debugger, I am back at the REPL.

**Comment by ryukinix** [comment]
Thanks for the awesome extension and the clarify about this! Exists an easily way (shortcut) to copy an selected expressions to sly REPL?

Ps.: [pt] Este seu nickname é demais! [/pt] :laughing:

**Comment by capitaomorte** [comment]
> Thanks for the awesome extension and the clarify about this! Exists an easily way (shortcut) to copy an selected expressions to sly REPL?

* to be honest, I don't know. But if there isn't, there really should be. So also marking this issue a feature request. There is something that can make you jump to the repl very quickly. I use it a lot `C-c ~`. It will synch the package and the default directory. But will not paste the expression near point. Perhaps it should.

* The other thing I'm going to do is prevent `(read)` calls originating from non-interactive contexts to issue such confusing errors. They will still issue errors, just easier to understand for everybody.

> Ps.: [pt] Este seu nickname é demais! [/pt] :laughing:

é um bocado infantil, para dizer a verdade... se pudesse mudava, mas agora tenho muitos repositórios ligados a ele.

**Comment by ryukinix** [comment]
Well, I'm just checking here. I'm go back to lisp right now (oh yeah!) and I'm very happy to see you continue do maintence for this project. How I can help you? I'm trying use my efforts in something about common lisp and this project is really great, at least for me.

You have something whose I can do and can help you?

[pt] Engraçado, você mudou seu nickname. [/pt]

**Comment by joaotavora** [comment]
@ryukinix, if you want to help, it depends on your skill set and what would motivate you the most. Here's a very summarized list:

* Have a look at the outstanding issue list and tell me which ones you understand and would like to work on.

* With very little Elisp and Common Lisp experience:all around testing of SLY's features, especially what distinguishes it from SLIME, the multiple inspectors, the SLY stickers feature, the completion system, etc. Report bugs, suggest small fixes, and write documentation.

* With some more Elisp and Common Lisp experience: leverage an existing generic, implementation-agostic profiling library such as [this one](https://github.com/TBRSS/metering/blob/master/metering.lisp) or   improve upon one that existed earlier in this repository [here][(https://github.com/joaotavora/sly/blob/master/contrib/slynk-profiler.lisp])and make something like the SLY trace dialog, but for profiling functions.

* With considerable Elisp and Javascript knowledge, write the equivalent of [swankjs](https://github.com/swank-js/swank-js), but for using the modernized interfaces of Slynk, perhaps refactoring Slynk behaviour as needed to adapt to the Javascript reality.

Can you think of anything else?

**Comment by ryukinix** [comment]
Closed due lack of activity (> year 1).

**Comment by Thovthe** [comment]
Wasn't this supposed to track a feature too?  If so, why close due to inactivity?

>>Thanks for the awesome extension and the clarify about this! Exists an easily way (shortcut) to copy an selected expressions to sly REPL?
>
>to be honest, I don't know. But if there isn't, there really should be. So also marking this issue a feature request. 

Related to READ interactivity on evaluation with sly-eval-last-expression C-x C-e it might be good to have a option to print the input to the REPL.  That way if I test out a function for a command line application that takes prompts it shows the input like it might in a shell.

For example I have this function:
```
(defun lettest ()
  (let* ((prompt1 "~%What's your maximum breath hold?~%")
		 (max-hold (progn (format t prompt1) (read)))
		 (prompt2 "~%What do you want the breath up duration to start at?~%")
		 (start (progn (format t prompt2) (read))))
	(format t "~%Max-Hold is ~S Start-Point is ~S" max-hold start)))
```
Right now it looks like this in the REPL:
```
What's your maximum breath hold?

What do you want the breath up duration to start at?

Max-Hold is 1 Start-Point is 2
```
It could look something like this:
```
What's your maximum breath hold?
1
What do you want the breath up duration to start at?
2
Max-Hold is 1 Start-Point is 2
```
I'm pretty new to CL so maybe it's me doing something wrong that makes me think this would be nice.
