### ISSUE TITLE
Spin off hyperspec

### ISSUE THREAD

**Issue by tarsius** [joaotavora/sly#86]
Currently both `sly` and `slime` bundle diverging versions of `hyperspec`. It would be nice if this library could be split of into a separate repository which would then be be maintained by the maintainers of both projects.

If that isn't an option, then maybe you could prefix the library name and all the symbols it defines with `sly-`?

Thanks for considering.

**Comment by capitaomorte** [comment]
That's a great idea! perhaps bundle it in `/lib` though.

**Comment by tarsius** [comment]
Actually I also don't use `package.el` and I still don't like bundled libraries ;-)

It doesn't bother me if I have to install a dependency, but maybe that's because I have written a tool to give me a hand with that. I plan to release `borg.el` on Monday, but have been planning to release it very soon for the last few weeks without success, so we'll see how it plays out this time around. That's part of the reason it took me so long to follow up on this, I wanted to release that first, because it might be something you might enjoy too - and which might change your perspective on this.

Anyway, if you keep bundling package which are also being distributed separately (or like in this case *should* be distributed separately), then I would suggest you do it like this:

* Put the bundled library or libraries into a separate directory which is named something like `bundled/` or `third-party/`.
* Prevent that directory from being added to the `load-path` by adding the file `<directory>/.nosearch`.
* Load  the feature like this:

```lisp
(or (require 'hyperspec nil t)
    (require 'hyperspec "bundled/hyperspec")
```

I.e. first try to load the potentially separately installed version and only if that fails load the bundled version. 

> That's a great idea!

What do you plan to do to make it happen?
